-- Deep research expansion for Point Lookout Lighthouse
-- Before: 416 chars, 1 source
-- After: ~3800 chars, 8 sources

UPDATE places
SET ghost_story = 'Point Lookout Lighthouse, built in 1830 at the confluence of the Potomac River and Chesapeake Bay, has earned the title of "Most Haunted Lighthouse in America." Its dark reputation stems from the Civil War, when Hammond General Hospital was established nearby in 1862, followed by Camp Hoffman in 1863—the largest Union POW camp for Confederate prisoners. The camp, designed for 10,000, held up to 52,000 prisoners in open-air conditions with contaminated water, spoiled food, and freezing winter tents. Between 3,000 and 8,000 Confederate soldiers died from disease, exposure, and war wounds, buried in mass graves near the lighthouse.

The lighthouse''s first keeper, James Davis, died just two months after the light was first lit on September 30, 1830. His daughter Ann Davis took over and served capably for 17 years. She is now the lighthouse''s most frequently encountered spirit—appearing at the top of the stairs in a blue skirt and white blouse, her voice captured on EVP recordings saying "this is my home." Ann remained devoted to the lighthouse until her death, found lying in the lantern room after dying while performing her duties.

In October 1878, the steamship Express sank in a raging storm off Point Lookout, killing 22 passengers and crew. Second Mate Joseph Haney attempted to row ashore for help but drowned. Days later, his body washed up on the beach. Park Superintendent Gerald Sword witnessed Haney''s ghost in the 1970s—a man in a sack coat and floppy hat walking toward the house during a storm. When Sword opened the door, the figure floated through the porch wall and vanished toward the bay. Residents have reported knocking at the door during storms, finding no one there but puddles of water leading to the beach.

Pioneer paranormal researcher Dr. Hans Holzer conducted the first investigation on January 14, 1980, at Sword''s invitation. His team recorded 24 distinct voices—male and female—singing and conversing throughout the lighthouse. One chilling EVP captured a Union guard''s command: "Fire if they get too close to you." The Maryland Committee for Psychical Research followed with additional investigations, capturing a woman''s voice singing in the north hallway and a desperate plea from the basement: "Let me out or get out."

Laura Berg, who lived alone in the lighthouse from 1980-1981, experienced nightly footsteps outside her bedroom door, books flying off shelves, and awful stenches appearing in various rooms. She heard heavy boots clomping on floorboards at night, a woman singing merrily, and ghostly men chatting and laughing. One night, dancing lights appeared above her bed. Smelling smoke, she discovered a space heater had caught fire—the spirits, perhaps Ann Davis herself, had saved her life and the lighthouse. Berg later co-founded the Point Lookout Lighthouse Preservation Society and became Maryland''s Secretary of State.

Gerald Sword documented his own extraordinary experiences: kitchen walls glowing for ten minutes, snoring sounds in the empty kitchen for two weeks straight, voices during storms, and his dog mysteriously appearing outside a locked porch. His Belgian Shepherd regularly lunged at invisible figures. A famous photograph from a 1970s seance shows a spectral Confederate soldier standing behind Laura Berg as she holds a candle—gaunt, bedraggled, in tattered Civil War-era clothing.

Other spirits include a phantom woman searching for a long-gone cemetery, a confused soldier looking for the battlefield, transparent figures in the basement, and a young blonde man with blue eyes believed to have been murdered. A Civil War soldier with a long rifle patrols the grounds. Mediums have sensed an angry woman who contemplated throwing herself down the stairs, and someone in "agony" in the middle room—possibly a suffering prisoner. The lighthouse, now a museum open since 2025, continues to host paranormal investigation nights for those brave enough to spend the night with Maryland''s most restless spirits.',
    sources = '["https://www.lighthousefriends.com/light.asp?ID=436","https://dnr.maryland.gov/Pages/Spirits-of-Point-Lookout.aspx","https://www.ptlookoutlighthouse.com/overview.shtml","https://annapolisghosttour.com/point-lookout-state-park/","https://www.chesapeakebay.net/news/blog/six-lighthouses-in-the-chesapeake-bay-with-eerie-pasts","https://en.wikipedia.org/wiki/Point_Lookout_Light","https://www.baltimoresun.com/2007/10/27/a-grisly-past-continues-to-haunt-point-lookout/","https://watershedchronicle.wordpress.com/2011/10/19/the-13-days-of-halloween-the-ghosts-of-st-marys-county/"]',
    source_count = 8,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'point-lookout-lighthouse';
