-- Deep research: The Wayside Inn, Ellicott City, Maryland
-- Expanded ghost_story from 919 to ~5,200 characters with 9 verified sources

UPDATE places
SET ghost_story = 'The Wayside Inn stands as a three-story granite sentinel on the Columbia Turnpike, its Federalist architecture dating to approximately 1780 when it served as the main farmhouse on a prosperous tobacco plantation. The massive stone structure—built from rock blasted from the very bedrock of Ellicott City—would later house plantation owners, their families, servants, and enslaved workers who toiled in the tobacco fields that once dominated this region of Anne Arundel County (now Howard County).

Local lore maintains that General George Washington himself may have lodged at the farmhouse during his travels through the area. As a fellow plantation owner, Washington "would have stopped to pay his respects" according to later innkeeper David Balderson, and his name does appear on a ledger at a nearby Elkridge tavern. John Quincy Adams is also rumored to have stayed during his journeys along the road connecting Baltimore and Washington.

By the early 1800s, the plantation house had transformed into a public house and inn, offering shelter to travelers making the arduous journey along the turnpike. When the Civil War erupted, Ellicott City''s strategic position along the B&O Railroad made it a critical Union outpost, with soldiers garrisoned throughout town to protect Ellicott''s Mills. The Wayside Inn may have sheltered young soldiers during those turbulent years, and as makeshift hospitals sprang up across the city to treat the wounded, the old plantation house likely witnessed the suffering and death that war brings.

The inn is known throughout the region as "that house with the candles in the windows." One persistent legend explains their origin: a mother lit a candle as her son departed to fight for the Union, vowing to keep it burning until he returned. When he never came home, she kept her vigil anyway, the candles perpetually lit in windows as an eternal beacon for a son who would never return. Previous owners maintained electric candles in all 35 windows continuously—a fact that allegedly appeared in "Ripley''s Believe It or Not." Others whisper that the candles signal something else entirely: the presence of the dead who never left.

The primary haunting centers on a female spirit known as "Jenny," described as a housekeeping ghost who once tidied the third floor. Though she has not manifested visually in recent years, former guests have reported the unsettling sight of a woman''s face slowly emerging from the wallpaper before receding back into the pattern. When the Osantowskis purchased the property in 1980 and renovated the third floor to open it as a bed and breakfast, they may have disturbed Jenny''s eternal duties.

Guests report a constellation of paranormal phenomena. Footsteps echo through otherwise empty rooms, measured and deliberate as if someone is pacing. Doors swing open on their own accord, creaking on ancient hinges. The most common experience is olfactory: a sudden waft of gentle woman''s perfume drifting through hallways when no living soul is present. One visitor described hearing a door open clearly, followed by the distinct sound of approaching footsteps—yet when they turned to greet the newcomer, no one was there.

Other witnesses have caught a fleeting glimpse of a white dress in their peripheral vision, only to turn and find nothing but empty air and that lingering floral scent. The spirit seems tied to the upper floors, where generations of travelers once slept and where some may have drawn their final breaths during the inn''s possible use as a Civil War hospital.

Paranormal investigators attribute the Wayside Inn''s supernatural activity to Ellicott City''s unique geological and environmental characteristics. The city is carved from solid granite and granite composite, and mediums believe this mineral foundation attracts and channels spiritual energy—a concept known as the Stone Tape Theory, which suggests that quartz, granite, and limestone can retain and replay energy patterns from the past. The Tiber River flows directly beneath many buildings on the south side of town before emptying into the Patapsco River, and water is believed to conduct paranormal energy. Overhead transformers and thick electrical cables provide additional conduits. The town''s antique stores, filled with personal possessions of the deceased, may harbor spirits still attached to their earthly belongings.

The property passed through numerous families over two centuries: the Shapiros, Hodges, and Parletts watched it deteriorate until Robert and Charlotte Hartkopf purchased it in 1963 and secured the first historical designation. The Gerards bought it in 1976, followed by the Osantowskis in 1980, who opened the bed and breakfast. Susan and David Balderson acquired the inn in 1998 for $400,000, completing extensive renovations before reopening in 1999. The inn was accepted into the Select Registry of Distinguished Inns of North America in 2008.

Ellicott City itself is often called "the most haunted town on the East Coast," with over 250 years of tragedy, floods, fires, executions, and Civil War casualties leaving psychic imprints throughout its granite buildings. The Wayside Inn is merely one node in this web of supernatural activity—but for those who encounter Jenny or feel the cold presence of unseen guests in its historic halls, it is haunting enough.',
    sources = '["https://www.hauntedrooms.com/maryland/haunted-places/haunted-hotels/wayside-inn","https://waysideinnmd.com/blog/haunted-ellicott-city/","https://washingtonian.com/2024/09/30/haunted-hotels-for-a-spooky-getaway-near-dc/","https://frightfind.com/wayside-inn-maryland/","https://www.baltimoresun.com/ph-ho-vw-wayside-inn-20120719-story.html","https://www.visithowardcounty.com/things-to-do/tours/ghost-tours/","https://www.hauntedplaces.org/item/wayside-inn-2/","https://www.southernspiritguide.org/13-more-southern-rooms-with-a-boo/","https://www.marylandhauntedhouses.com/real-haunt/wayside-inn.html"]',
    source_count = 9,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'wayside-inn-ellicott-city';
