-- Deep research: Governor Calvert House, Annapolis, Maryland
-- Expanded from 343 chars, 1 source to comprehensive history with 7 sources

UPDATE places
SET ghost_story = 'The Governor Calvert House at 58 State Circle stands as one of Annapolis''s most haunted landmarks, with over 300 years of spectral history. Built in the late 17th century, the property earned its name when Captain Charles Calvert, Maryland''s 14th Proprietary Governor, occupied it from 1720 to 1727. Charles had converted to Anglicanism to help restore his family''s control of Maryland after Protestant-Catholic conflicts caused the Crown to seize the colony. His cousin Benedict Leonard Calvert replaced him as governor in 1727, forcing Charles from his beloved home in a contentious handover of power.

Both Calverts died tragically young. Benedict, described as troubled and a heavy drinker who "takes more physik than anyone I ever knew," succumbed to tuberculosis in 1732 at age 31, dying aboard the family ship while returning to England. Charles died in 1734 suffering from early senility. Neither could move on from this house, and guests continue to see apparitions in 18th-century clothing meandering through the hallways, possibly checking on their prized possession hidden beneath the floors.

Archaeological excavations in 1982-1984 by the University of Maryland and Historic Annapolis Foundation uncovered the building''s most remarkable secret: an ancient hypocaust, a Roman-style underground heating system of brick channels connecting to a fireplace. Scholars believe Charles Calvert maintained an orangery here, an opulent greenhouse for cultivating citrus fruits that displayed wealth and power. This hypocaust is believed to be the oldest example in North America. Today, visitors can view it through a distinctive glass floor in the sitting room, but many report something far more unsettling: unfamiliar faces appearing in the glass, reflections of invisible spirits roaming the room or perhaps entities trapped within the glass itself.

The building served many purposes over the centuries: a mercantile firm in 1766, state barracks in 1784, a printing press office in 1843, the mayor''s residence in the 1850s, and apartments in the early 1900s. In the 1970s, Paul Pearson converted it into a boutique hotel. During the 1980s renovations, so much strange activity occurred that a paranormal investigation team was called in. Their equipment reportedly hit the highest levels possible, confirming an intense ghostly presence.

The most notorious spirit is Dominic, a male entity witnessed in multiple bedrooms engaged in disturbing voyeuristic behavior. When a medium communicated with Dominic, they discovered something chilling: he is fully aware that he is dead but deliberately chooses to remain, enjoying his ability to watch guests undress from the shadows. Some accounts say he was a disgruntled hotel employee who died in the 1940s; others claim he took his own life. All agree he is devilish and perverted, taking full advantage of his eternal existence.

A woman from the 1940s, rumored to have died by suicide, also wanders the hallways after dark. Strange sounds emanate from behind the sealed latch key door to the attic. TVs turn on and off during the night, a phenomenon so common that the hotel clerk confirms it as a regular occurrence. One playful spirit persisted in this trick three times until a bewildered guest shouted "OK, you have our attention now," at which point it stopped immediately.

The most sinister haunting centers on Room 3202, where demonic terrors await. A couple staying during the COVID pandemic reported a harrowing night. The husband kept noticing a strange oily burnt odor that his wife couldn''t smell. Both experienced vivid, simultaneous nightmares: one involving a horrific murder, another featuring a demon-like creature, mostly man but with animal features. The husband moaned in severe pain and shouted angrily in his sleep, highly unusual behavior. They woke repeatedly throughout the night sensing a dark presence watching over them, and reported a terrible night''s sleep despite the comfortable bed. Guests have reported waking up in agony, painfully tortured by this demon-like presence.',
    sources = '["https://annapolisghosttour.com/the-governor-calvert-house/", "https://tourbaltimoreghosts.com/the-haunted-and-historic-governor-calvert-house/", "https://www.hauntedrooms.com/maryland/haunted-places/haunted-hotels/governor-calvert-house", "https://usghostadventures.com/haunted-cities/top-10-most-haunted-places/top-ten-most-haunted-places-in-annapolis/", "https://www.marylandhauntedhouses.com/real-haunt/governor-calvert-house.html", "https://en.wikipedia.org/wiki/Benedict_Leonard_Calvert", "https://www.tripadvisor.com/ShowUserReviews-g29494-d89317-r762952280-Historic_Inns_Of_Annapolis-Annapolis_Maryland.html"]',
    source_count = 7,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'governor-calvert-house';
