-- Deep research update for Pry House Field Hospital Museum
-- Expanding ghost story from ~1,155 chars to ~4,500+ chars with verified sources

UPDATE places SET
  ghost_story = 'The Pry House stands as one of the most actively haunted sites on the Antietam battlefield, bearing witness to the bloodiest single day in American history. Philip Pry built this two-story brick house in 1844 on a rise overlooking Antietam Creek, using bricks fired on his own property. When Union forces arrived on September 16, 1862, General George B. McClellan commandeered the house as his headquarters, watching the battle unfold from the rooftop through a telescope while officers used tent stakes as rests.

As casualties mounted on September 17th—over 22,000 in a single day—the Pry farmhouse and barn transformed into a field hospital. Dr. Jonathan Letterman, Medical Director of the Army of the Potomac, established his medical headquarters here, coordinating the evacuation and treatment of thousands of wounded. The barn alone treated at least 1,500 soldiers. Surgeons performed amputations without anesthesia, and screams of agony echoed across the property as men died by the dozens.

Among the wounded was Major General Israel B. Richardson, struck by shell fragment while directing artillery fire at Bloody Lane. Though his wound was initially deemed survivable, he was placed in an upstairs bedroom in McClellan''s headquarters. His wife Frances "Fannie" Richardson traveled from Michigan with her sister-in-law Marcella to nurse him. In October, Fannie wrote that "Israel is slowly but steadily improving [but he] has grown very thin and very weak. He is very much depressed, not at all like himself." President Abraham Lincoln personally visited Richardson on October 4, 1862, promising him command of the Army of the Potomac if he recovered. He never did. Pneumonia set in, and on November 3, 1862—after six weeks of devoted care from his wife—General Richardson died in that upstairs room.

The haunting began dramatically in 1976 when the house caught fire, gutting the entire interior. While firefighters battled the blaze, several reported seeing a woman in 19th-century clothing standing at a second-floor window—the very room where General Richardson had died. When the fire was extinguished, they discovered the floor around that window had completely collapsed. No one could have been standing there. No bodies were found in the ruins.

During restoration, workers commissioned to rebuild the house witnessed the same impossible sight: a woman in period dress standing in the upstairs window, though the second floor had not yet been reconstructed. One contracting crew was so terrified by the spectral figure that they abandoned the project entirely, forcing the National Park Service to hire replacement workers.

Museum director George Wunderlich experienced the paranormal firsthand. On his first day hauling junk from the restored house, he opened all the doors to air out the building. Each door slammed shut in sequence, from front to back. A breeze might explain one door, but not all of them. He opened them again. This time, they slammed shut from back to front. Doors shutting and locking on their own became a recurring phenomenon.

The most compelling witness may be George''s 12-year-old son. Alone on the second floor one day, he came downstairs and asked his father who the woman was and how she did that. He had watched a woman in 19th-century clothes walk through a room upstairs—then disappear directly through the wall. This is the room where Mrs. Richardson has been seen most frequently, the very bedroom where she maintained her devoted vigil as her husband slowly died.

During a meeting of park personnel, one staff member''s wife encountered a woman in old-fashioned clothing descending the staircase. She asked her husband who the lady in the long dress was. He had no idea who she was talking about—no one fitting that description was in the house.

The Pry House continues to generate paranormal reports: unexplained noises, flickering lights, and screams echoing through empty rooms. Phantom footsteps ascend and descend the staircase—perhaps the worried pacing of Frances Richardson checking on her dying husband, or generals anxiously awaiting news from the battlefield. A loud banging noise has been heard from the front upstairs hallway. Visitors report sudden temperature drops, an overwhelming sense of melancholy, and the distinct feeling of being watched.

Faint commands are sometimes heard being screamed, like ghostly echoes of orders given on the battlefield. The barn, too, has its spirits—singing and disembodied voices have been reported where over a thousand soldiers once lay wounded and dying. Some believe the intense suffering that occurred here has left a permanent imprint, trapping the spirits of soldiers, surgeons, and one devoted wife who watched helplessly as her husband slipped away.',
  sources = '["https://www.civilwarmed.org/pry/about-the-pry-house/", "https://www.nps.gov/anti/planyourvisit/pryhouse.htm", "https://www.civilwarmed.org/richardson/", "http://www.panicd.com/pry-house-field-hospital-museum.htm", "https://www.roadrunner.travel/tours/paranormal-activity-at-the-pry-house/", "https://www.ourhauntedtravels.com/post/visiting-the-pry-house", "https://www.fhwa.dot.gov/infrastructure/back1105.cfm", "https://annapolisghosttour.com/antietam-national-battlefield/", "https://www.battlefields.org/learn/biographies/israel-bush-richardson", "https://www.nationalparkstraveler.org/2007/10/haunted-house-antietam-national-battlefield"]',
  source_count = 10,
  updated_at = '2026-01-30'
WHERE slug = 'pry-house-field-hospital';
