-- Deep research: The Maryland Inn (Annapolis, MD)
-- Expanded from 449 chars / 1 source to ~3,800 chars / 9 sources

UPDATE places SET
  ghost_story = 'The Maryland Inn has witnessed over 250 years of American history since Thomas Hyde built it in 1772, and it is said that every room in this four-story, thirty-nine room hotel has its own ghost. The inn hosted delegates who watched George Washington resign his military commission in December 1783 and Congressional members who ratified the Treaty of Paris in January 1784 — guests included Benjamin Franklin, Thomas Jefferson, Alexander Hamilton, and the Marquis de Lafayette.

The most famous haunting involves Navy Captain Charles Campbell and his intended bride, known only as "The Bride." According to legend, Campbell proposed around 1805 but wanted to earn more money before the wedding. He set off to sea and rose to the rank of captain. After twelve years apart, in 1817, Campbell wrote that he was finally coming home. He arrived in Annapolis and walked up Main Street from City Dock. When he spotted his soon-to-be wife waiting in the window of the Maryland Inn, he stepped into the street for a better look — and was crushed by a runaway horse-drawn cart too heavy to stop on the cobblestone hill. The Bride allegedly witnessed everything from the window and threw herself to her death in a fit of sorrow, both dying right outside the historic inn.

Today guests in Room 405 report anxious footsteps pacing back and forth on hardwood floors at night. Some have awakened to find a presence sitting at the foot of their bed, or felt The Bride''s weight lean into the mattress as her tapping foot sounds beside them. The room''s window is known to fly open or slam shut on its own. Many have seen the wispy apparition of The Bride pacing back and forth, seemingly gathering courage to jump. Meanwhile, Captain Campbell appears downstairs at Drummer''s Lot Pub in his naval uniform, standing with a beer by the fireplace or smoking a pipe alone before vanishing. The scent of tobacco lingers long after the bar closes. According to authors Mike Carter and Julia Dray in "Haunted Annapolis: Ghosts of the Capital City," though both spirits occupy the same hotel, they are never seen together — a sad reminder that even in death, the desperate lovers will never be reunited.

Other spirits haunt the inn''s halls. A woman dressed all in black frequents the same staircase where she fell to her untimely death. Unseen children scamper down hallways, giggling as they rush past unsuspecting visitors. A rowdy group of drunken Union soldiers has been heard — Annapolis was a key disembarkation point for Union forces during the Civil War. Guests report disembodied singing, perhaps the soldiers'' wartime tunes. A Revolutionary War soldier haunts the basement, the oldest part of the building, frequently heard singing sea shanties in a strong yet distant voice. Shadowy figures in Revolutionary War-era uniforms and 19th-century clothing have been glimpsed throughout the property.

Staff and guests report phantom tobacco smoke in the empty dining room, objects moving out of place, voices in vacant rooms, cold spots, and the scent of perfume. One skeptic witnessed a rocking chair moving on the front porch, accompanied by the strong smell of pipe tobacco. Julia, a bartender who worked at the pub for forty years, reported guests encountering a phantom cat curling up at their feet. Another guest reported a woman crawling across his bed in the middle of the night. TVs turn on and switch channels on their own, leaving even non-believers unnerved. The inn''s iron-gated old basement wine cellar is a particular hotspot — figures in ancient uniforms have been seen emerging from its direction.',
  sources = '["https://usghostadventures.com/annapolis-ghost-tour/the-maryland-inn/","https://annapolisghosttour.com/the-spirits-of-the-maryland-inn/","https://www.hauntedrooms.com/maryland/haunted-places/haunted-hotels/maryland-inn-annapolis","https://www.historichotels.org/us/hotels-resorts/historic-inns-of-annapolis/ghost-stories.php","https://www.hauntedplaces.org/item/the-maryland-inn/","https://www.marylandhauntedhouses.com/real-haunt/the-maryland-inn.html","https://www.chesapeakeliving.com/annapolis-haunted-houses/","https://en.wikipedia.org/wiki/Historic_Inns_of_Annapolis","https://whatsupmag.com/news/eerie-tales-haunted-annapolis/"]',
  source_count = 9,
  updated_at = '2026-01-30'
WHERE slug = 'maryland-inn-annapolis';
