-- Deep research update for Jonathan Hager House
UPDATE places
SET ghost_story = 'Jonathan Hager, a German immigrant who arrived in Philadelphia in 1736 aboard the ship Harle, built this limestone homestead in 1739 on 200 acres he purchased from Daniel Dulaney for about 30 cents an acre. He named the property "Hager''s Fancy" and presented it to his bride Elizabeth Kershner in 1740. The distinctive two-and-a-half-story house features 22-inch-thick limestone walls and was built over two freshwater springs that run through the cellar at a constant 40 degrees Fahrenheit, serving as both a water source and natural refrigeration. Hager founded the town of Elizabethtown (later Hagerstown) in 1762, served in the French and Indian War, and was the first German-born American elected to the Maryland Colonial Legislature. He died tragically on November 6, 1775, crushed by a wooden roof beam while supervising construction of the German Reformed Church he had donated land for.

The house passed through the Rohrer family (relatives of the Hagers) until Michael Hammond purchased it in 1813. The Hammond era brought unspeakable tragedy - four of Michael and Catherine Hammond''s grown children died within a three-month period in 1844, likely from an epidemic, along with three infant children and other family members who perished between 1838 and 1844. The Civil War-era Downin family later occupied the house. At least 13 people are documented to have died within these walls over its 280-year history.

Forbes has named the Jonathan Hager House the most haunted place in Maryland, and the reported paranormal activity is extensive. The nursery is the most active location - a cradle and rocking chair rock on their own, temperatures rise and fall without explanation, and during a ghost tour a woman fainted there. Visitors report an overwhelming feeling of dread and sudden temperature drops in this room. A corn-cob doll mysteriously moves to different locations throughout the house, believed to be manipulated by the spirits of the Downin children, who are also blamed for turning off lights and causing cameras to malfunction.

Multiple apparitions have been identified. A "Lady in Green" is seen gazing pensively from windows or as a fleeting flash of her green dress in the hallways. A "Man in Black," possibly a Hammond family member, appears on the porch smoking a pipe and has been spotted walking the grounds of City Park. A little girl spirit shows a peculiar affinity for female guests. Visitors have reported being poked by unseen hands, feeling sensations of a toddler tugging at their clothing, experiencing sharp neck pains, and smelling phantom alcohol in the basement. Cabinet doors with functioning latches open on their own. In the cellar, visitors hear footsteps and the sound of heavy objects being dragged across the stone floor. A psychic visiting the house reported sensing a strong presence concentrated in the basement. Curators and tour guides have accumulated decades of stories involving disembodied voices, phantom footsteps, and the pervasive sensation of being watched. The City of Hagerstown offers annual lantern-lit ghost tours that consistently sell out, where guides share these chilling tales passed down through generations of staff who have experienced the paranormal firsthand.',
    sources = '["https://radiofreehubcity.com/2024/10/09/hager-house-one-of-marylands-most-haunted-places/","https://www.marylandhauntedhouses.com/real-haunt/johnathan-hager-house-museum.html","https://www.hagerstownmd.org/1129/Ghost-Tour","https://www.hauntedplaces.org/item/johnathan-hager-house-museum/","https://en.wikipedia.org/wiki/Jonathan_Hager","https://washingtoncountyhistoricaltrust.org/120-hagers-fancy-circa-1739-hagerstown-md/","https://thishauntedplace.com/hager-house/","https://www.yahoo.com/gma/whos-haunting-home-hagerstowns-founder-120038682.html"]',
    source_count = 8,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'jonathan-hager-house';
