-- Deep research update for Fort McHenry, Baltimore, MD
-- Sources: Baltimore Sun, Southern Spirit Guide, Tour Baltimore Ghosts, Maryland in the War of 1812, NPS, US Ghost Adventures

UPDATE places SET
  ghost_story = 'Fort McHenry''s star-shaped walls have witnessed over two centuries of death and tragedy, leaving behind some of Baltimore''s most active hauntings. During the famous 25-hour British bombardment on September 13-14, 1814—the battle that inspired Francis Scott Key to write "The Star-Spangled Banner"—Lieutenant Levi Clagett and Sergeant John Clemm were manning a cannon on Bastion Three when one of 1,500 British bombs made a direct hit, killing them instantly. Clemm, described as "a young man of most amiable character, gentlemanly manners and real courage," was killed when a two-inch chunk of shrapnel ripped through him. Their deaths were among the four defenders killed that night.

Clagett''s ghost has become one of the fort''s most frequently reported apparitions. Visitors regularly inquire at the visitor center about "the reenactor" they saw walking Clagett''s Bastion, only to be told no actors were present. During preparations for President Gerald Ford''s visit, Secret Service agents observed a uniformed soldier walking the bastion where Clagett and Clemm died—though no one should have been there. Witnesses describe a military man in a uniform "only used briefly by Americans," and are "dumbfounded when told that there were no actors in costume on the grounds that day."

The fort''s dark history continued through the Civil War, when it earned the nickname "The Baltimore Bastille." Nearly 7,000 Confederate prisoners were held in the casemates and cells, including Francis Scott Key''s own grandson. Over 2,000 political prisoners—including Baltimore''s mayor, police commissioners, newspaper editors, and 31 members of the Maryland legislature arrested to prevent them from voting on secession—were detained here without trial. Thirty-three Confederate prisoners died at the fort. At least three men were executed, including a Union soldier hanged for murder.

Private John Drew''s tragic suicide in 1880 created another restless spirit. Drew fell asleep during guard duty, was arrested, and faced court-martial. While imprisoned, a guard carelessly placed his weapon within Drew''s reach. Overcome with shame, Drew grabbed the gun and shot himself. Since then, at least a dozen visitors have reported seeing a man in a soldier''s cape pacing "endlessly back and forth" along the outer battery where he was derelict in his duties. Others feel an inexplicable chill within the cell where he took his life, and some claim "if you rub your hand along the wall, there''s a warm spot that you can feel."

Near the Orpheus statue honoring Francis Scott Key, a visitor witnessed a uniformed figure appearing to float in mid-air. Research revealed this location was the site of an 1862 execution—a young private convicted of murdering a fellow soldier was hanged there, his feet dangling above the ground.

The most aggressive spirit is a woman in white who haunts the barracks. Believed to be the wife of a noncommissioned officer whose children died during an epidemic in the 1820s, she takes her sorrow out on the living. An artist was knocked unconscious by an invisible force, describing the sensation as "being struck with a frying pan." A park ranger experienced an attempted push down the stairs by a woman in period clothing. Re-enactors have spotted "the figure of a woman in a Victorian era-looking dress, looking out the window, and then she disappeared."

During World War I, Fort McHenry became a massive military hospital complex. Approximately 300 cases of influenza were reported during the devastating 1918 Spanish Flu epidemic. Nurses at the fort''s hospital "were among the first to succumb to the epidemic" as the disease ravaged military installations.

Psychic Dorothy Bathgate, brought in to investigate, accurately identified locations of wounded soldiers and mortuaries without prior knowledge. She described a bearded man on Clagett''s Bastion—later research confirmed a Hasidic Jewish merchant had served there, permitted to keep his beard for religious reasons. Former Director of Visitor Services Warren Bielenberg stated "70 to 80 percent of the things she said were substantiated later." After challenging John Drew''s spirit, he reported hearing "a tap like a fingernail at the window."

Park rangers hear footsteps in empty corridors and find lights turned on after they''ve been shut off. Staff discontinued Halloween candlelight tours because "the supernatural was taking over." The fort is so haunted that management requires paranormal investigators to file a "special use permit" application to document evidence—they clearly don''t want the fort known primarily for its ghosts. Today, docents "remain tight-lipped about their experiences during the day, but secretly admit to experiencing paranormal phenomenon that defies logical explanation." The spirits of soldiers from 1812, the Civil War, and beyond continue their eternal watch over this hallowed ground.',
  sources = '["https://www.baltimoresun.com/news/bs-xpm-1996-10-31-1996305005-story.html", "http://www.southernspiritguide.org/the-heavn-rescued-land-fort-mchenry-baltimore-maryland/", "https://tourbaltimoreghosts.com/haunted-history-of-fort-mchenry/", "https://maryland1812.com/2011/05/31/levi-claggett-john-clemm-fallen-soldiers-of-fort-mchenry/", "https://usghostadventures.com/baltimore-ghost-tour/top-10-most-haunted-places-in-baltimore/", "https://www.nps.gov/fomc/learn/historyculture/the-baltimore-bastille.htm", "https://www.influenzaarchive.org/cities/city-baltimore.html"]',
  source_count = 7
WHERE slug = 'fort-mchenry';
