-- Deep research: Rodgers House, Havre de Grace, Maryland
-- Expanded from 823 chars to ~4,800 chars with 8 verified sources

UPDATE places
SET ghost_story = 'The Elizabeth Rodgers House at 226 North Washington Street is Havre de Grace''s oldest documented structure, dating to 1788 and the only eighteenth-century building to survive the British burning of the town during the War of 1812. Colonel John Rodgers (1726-1791), a Scottish immigrant who fought in the Revolutionary War, and his wife Elizabeth were among the first settlers in what was then called "Susquehanna Lower Ferry." They operated a tavern and ferry service here, and George Washington himself recorded dining with Colonel Rodgers in 1787 during his travels between Philadelphia and Baltimore.

The Rodgers family produced one of America''s most distinguished naval dynasties. Their son, Commodore John Rodgers Jr., became a national hero after firing the first shot of the War of 1812 aboard USS President on June 23, 1812, six days after Congress declared war. The Commodore commanded the frigate in a running eight-hour battle against HMS Belvidera, during which one of President''s bow chaser guns burst, breaking his leg among other casualties. Over four wartime cruises, Rodgers captured 23 British prizes.

But while the Commodore was at sea in 1813, the British targeted his hometown. On May 3, 1813, before dawn, Rear Admiral George Cockburn launched a devastating assault on Havre de Grace. A squadron of 19 barges carrying approximately 400 British troops attacked the sleeping town of just 250 residents. They used terrifying Congreve rockets that made horrible whizzing and popping sounds to sow chaos. The town''s militia of barely 20 men fled, except for one heroic figure: John O''Neill, who manned the battery guns single-handedly until wounded and captured. His 15-year-old daughter Matilda later rowed out to Admiral Cockburn''s ship to plead for her father''s life, so impressing the Admiral that he released O''Neill and gave the girl his gold snuff box.

The British went house to house, burning and looting. Between 20-40 of the town''s approximately 60 dwellings were destroyed. Eyewitnesses reported "distressed people, women and children half naked" fleeing into the countryside. But they reserved special attention for the Rodgers home. Rev. James Jones Wilmer, the Episcopal clergyman and former Chaplain of the U.S. Senate who witnessed the attack, documented in his 1813 Narrative that "the enemy set fire three times to Mrs. Rodgers'' house...but it fortunately each time was extinguished, though they defaced and mutilated much." Elizabeth Rodgers'' house became one of the few structures to survive the inferno, perhaps protected by neighbors or sheer luck—or perhaps something else.

The Commodore''s mother, wife, and two sisters had fled to the nearby home of Mark Pringle, a wealthy gentleman. When a British detachment arrived to burn Pringle''s residence as well, Mrs. Goldsborough (one of the Commodore''s sisters) interceded with the commanding officer, pleading that she had an aged mother inside. The house was spared.

Today, the Elizabeth Rodgers House carries echoes of that traumatic night. The old Rodgers House Tavern was a gathering place for locals and travelers, but remnants of sorrow and despair cling to the site—perhaps from the heartache of Elizabeth Rodgers, who ran the establishment alone after her husband''s death in 1791, only to face the terror of the British attack two decades later. Strange noises and ghostly apparitions have been reported in and around the haunted grounds.

The most spine-tingling account involves a former employee whose terrifying encounter sent her fleeing the building, never to return. She claimed to have seen a man in colonial attire—perhaps Colonel John Rodgers himself, still watching over the tavern he built, or one of the many patrons who passed through during the Revolutionary era. Some speculate the hauntings could be echoes of those frantic hours on May 3, 1813, when the town burned and residents ran for their lives.

Near the old pier tiers—remnants of a 1900s boardwalk along the waterfront—locals report seeing apparitions on moonlit nights, walking over the place where the boardwalk used to be. These phantom figures are believed to be victims of the British raid, lost sailors, or perhaps spirits connected to the Rodgers family''s long association with the ferry and shipping trade.

The Elizabeth Rodgers House remained in the Rodgers family for nearly a century, until 1881. The naval dynasty it produced included Commodore John Rodgers Jr.; his son Rear Admiral John Rodgers II, who commanded ironclads in the Civil War; Rear Admiral John Augustus Rodgers (1848-1933); and naval aviator John Rodgers (1881-1926), who in 1911 became the first man in America to visit his parents by airplane at the family''s nearby estate, Sion Hill. Today the building has served as a drug store, steakhouse, and tavern, but the spirits of the Rodgers family—and perhaps the terrors of 1813—remain.',
    sources = '["https://usghostadventures.com/havre-de-grace-ghost-tour/", "https://www.letsroam.com/ghost-tour/havre-de-grace-md", "https://sah-archipedia.org/buildings/MD-01-CM75", "https://home.nps.gov/stsp/learn/historyculture/attack-on-havre-de-grace.htm", "https://en.wikipedia.org/wiki/Raid_on_Havre_de_Grace", "https://www.history.navy.mil/our-collections/art/exhibits/conflicts-and-operations/the-war-of-1812/the-little-belt-affair/commodore-john-rodgers.html", "https://en.wikipedia.org/wiki/Sion_Hill", "https://www.cecildaily.com/our_cecil/rodgers-family-left-mark-through-military-service/article_4f5aad5a-b476-5728-86ed-280094980e65.html"]',
    source_count = 8,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'rodgers-house-havre-de-grace';
