-- Deep research expansion for Concord Point Lighthouse in Havre de Grace, Maryland
-- Expanding ghost_story from 916 to ~4,800 characters with 11 verified sources

UPDATE places
SET ghost_story = 'Concord Point Lighthouse, completed in November 1827 by master builder John Donahoo using granite quarried from nearby Port Deposit, guards the point where the Susquehanna River enters the Chesapeake Bay. The thirty-six-foot conical tower, with walls three feet thick at the base, stands as Maryland''s second-oldest lighthouse and a monument to one man''s extraordinary courage.

John O''Neill, an Irish immigrant who arrived in America in 1786 at age eighteen, earned the title "Defender of Havre de Grace" on May 3, 1813. When British Admiral Sir George Cockburn''s squadron attacked the town during the War of 1812, O''Neill commanded approximately four dozen militiamen at the Potato Battery—a small parapet with three cannons at Concord Point. As British ships opened fire, O''Neill''s men abandoned their posts. Rather than retreat, O''Neill loaded and fired the cannons himself. "The grape shot flew thick about me," he later recounted. "When I fired her, she recoiled and ran over my thigh." Wounded but undaunted, he continued firing his musket until captured.

The story might have ended there but for fifteen-year-old Matilda O''Neill. Learning of her father''s capture aboard HMS Maidstone, she rowed out alone to confront Admiral Cockburn. When Cockburn declared O''Neill a civilian with no right to fire on British forces, Matilda argued that Maryland did not provide uniforms for its militia officers and offered to produce her father''s commission. Cockburn granted her exactly one hour. She rowed back to town, found the papers, and returned in time. The impressed admiral released O''Neill and handed Matilda a gold-lined tortoise shell snuffbox, saying: "Keep this for remembrance of Admiral George Cockburn, who admires loyalty and bravery in his enemies as he rewards the same virtues in his men."

In recognition of his heroism, President John Quincy Adams appointed O''Neill as the lighthouse''s first keeper in 1827, selecting him over seven other applicants—including the lighthouse''s builder, John Donahoo—at an annual salary of $350. O''Neill served until his death on January 26, 1838, and was buried at Angel Hill Cemetery. Remarkably, four generations of O''Neills kept the light: his son John O''Neill Jr. (1861-1863), daughter-in-law Esther O''Neill (1863-1881), and grandson Henry E. O''Neill (1881-1919). Henry''s dedication was legendary—at seventy-seven, he invested his $300 funeral savings in liberty bonds during World War I, an act that impressed President Woodrow Wilson.

The first documented paranormal report appeared in The Fayetteville News on February 15, 1889. A keeper described encountering an apparition in the lantern room: "The head of the man, devil, woman, or whatever it was, appeared to rest against the wire frame around the lantern. The top of the head was covered in black, and the eyes and yellowish-looking inch or so of the forehead above them appeared set in a frame of black. Its eyes were as big as those of a cow, and sparkled just like two big diamonds." The keeper noted he could not look at the figure''s eyes long, as they affected him more than the lantern''s flame itself. Most peculiar was the scent that accompanied the apparition: "The place which generally smells of oil was then filled with a perfume like a flower garden."

This entity became known as the "Perfumed Ghost"—a somber woman whose presence is announced by an overwhelming floral fragrance. Ghost tour guides describe her as bound to the lighthouse by "tragic love," though her identity remains unknown. Some speculate she may be connected to one of the O''Neill family women who spent their lives tending the light.

Author Ed Okonowicz, who has collected ghostlore from the Chesapeake region for decades, documented ongoing activity at the site. Locals walking near the lighthouse at night have reported seeing "a slow-moving shadow in the upper windows of the light tower." A dark figure has also been encountered near the memorial cannon at the tower''s base—perhaps John O''Neill himself, still standing guard at the battery he defended alone nearly two centuries ago.

In 1994, another dark chapter was added when a murder victim''s body was discovered on the lighthouse grounds. Author Amelia Cotter, in her book Maryland Ghosts: Paranormal Encounters in the Free State, notes that his spirit may have joined those already inhabiting the site.

The lighthouse was decommissioned by the Coast Guard in 1975. The Friends of Concord Point Lighthouse restored the tower in 1981 and installed a fifth-order Fresnel lens in 1983 (now preserved in the keeper''s house museum). Today, Havre de Haunts offers rare nighttime tours where visitors can climb the iron ship''s ladder to the lantern room and breathe in the mysterious floral scent that occasionally wafts through when the coast is clear.',
    sources = '["https://www.southernspiritguide.org/a-perfumed-ghost-havre-de-grace-maryland/","https://www.lighthousefriends.com/light.asp?ID=411","https://usghostadventures.com/havre-de-grace-ghost-tour/","https://www.hauntscout.com/places/united-states/maryland/havre-de-grace/concord-point-lighthouse/","https://en.wikipedia.org/wiki/John_O%27Neill_(lighthouse_keeper)","https://cheslights.org/keeper-bio-john-oneill/","https://theclio.com/entry/123216","https://www.cecildaily.com/our_cecil/havre-de-grace-s-warrior-princess-of-1813/","https://www.concordpointlighthouse.org/","https://www.nps.gov/places/concord-point-lighthouse.htm","https://explorehavredegrace.com/event/havre-de-haunts-concord-point-tour/"]',
    source_count = 11,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'concord-point-lighthouse';
