-- Seed data for tour_operators table
-- Generated by researcher agent on 2026-01-22
-- Updated with verified pricing, URLs, and descriptions
--
-- Coverage: Top 10 most popular haunted destinations
-- 1. New Orleans, LA (5 operators)
-- 2. Savannah, GA (5 operators)
-- 3. Salem, MA (5 operators)
-- 4. St. Augustine, FL (5 operators)
-- 5. Charleston, SC (5 operators)
-- 6. Gettysburg, PA (5 operators)
-- 7. San Antonio, TX (5 operators)
-- 8. Key West, FL (4 operators)
-- 9. Chicago, IL (4 operators)
-- 10. Nashville/Franklin, TN (4 operators)
--
-- Total: 47 tour operators

-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS tour_operators (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  website TEXT,
  booking_url TEXT,
  description TEXT,
  price_range TEXT,
  tour_types TEXT,
  image_url TEXT,
  featured BOOLEAN DEFAULT FALSE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Clear existing data for clean insert
DELETE FROM tour_operators;

-- =====================================================
-- NEW ORLEANS, LA - Most famous ghost tour city
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('French Quarter Phantoms', 'New Orleans', 'LA',
   'https://www.frenchquarterphantoms.com/',
   'https://www.frenchquarterphantoms.com/ghost-and-vampire-tour',
   'Voted New Orleans #1 Haunted Tour 8 years in a row and named one of TripAdvisor''s Top Ten Ghost Tours in the World. The award-winning Ghost and Vampire Combo Tour is about 1 hour 45 minutes through the French Quarter. Tours depart from The Voodoo Lounge with a two-for-one hurricane drink special included.',
   '$22-25', 'Ghost & Vampire tours, Garden District tours, Cemetery tours, Treme tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Haunted History Tours', 'New Orleans', 'LA',
   'https://hauntedhistorytours.com/',
   'https://hauntedhistorytours.com/',
   'The original New Orleans ghost tour company since 1995 and the largest, longest-operating walking tour company in the city. Two-hour tours run nightly rain or shine. Featured on A&E, History Channel, and Discovery Channel. Adults $25, children $14, under 5 free.',
   '$14-25', 'Ghost tours, Vampire tours, Cemetery tours, Garden District tours, Haunted pub crawls, Bus tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost City Tours New Orleans', 'New Orleans', 'LA',
   'https://ghostcitytours.com/new-orleans/',
   'https://ghostcitytours.com/new-orleans/',
   'Part of the nationwide Ghost City Tours network with over 9 million guests since 2012. Offers 90-minute Ghosts of New Orleans Tour for all ages. Prices don''t fluctuate during busy seasons. Money-back guarantee and free reschedules.',
   '$10-20', 'Ghost walking tours, Haunted pub crawls, Adults-only tours', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('New Orleans Legendary Walking Tours', 'New Orleans', 'LA',
   'https://www.neworleanslegendarywalkingtours.com/',
   'https://www.neworleanslegendarywalkingtours.com/new-orleans-tours/new-orleans-ghost-tour',
   'Explores the haunted history and spine-chilling tales of the city''s most eerie locations. Tours traverse the narrow, gas-lit streets of the French Quarter, including visits to the infamous LaLaurie Mansion and the Sultan''s Palace.',
   '$25-35', 'Ghost tours, Voodoo tours, French Quarter walking tours', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Nightly Spirits New Orleans', 'New Orleans', 'LA',
   'https://nightlyspirits.com/new-orleans-ghost-tours/',
   'https://nightlyspirits.com/new-orleans-ghost-tours/',
   'Rated top ghost tour in America by USA Today. Haunted pub tours stop at famous bars while sharing ghost stories and local history. 2.5-hour tours through the French Quarter for ages 21+.',
   '$28-35', 'Haunted pub crawls, Ghost walking tours', FALSE);

-- =====================================================
-- SAVANNAH, GA - "America's Most Haunted City"
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost City Tours Savannah', 'Savannah', 'GA',
   'https://ghostcitytours.com/ghost-tours/savannah-ghost-tours/',
   'https://ghostcitytours.com/savannah/',
   'Savannah''s #1 Tour Company since 2012 with over 500,000 guests. Prices don''t fluctuate during busy seasons with no hidden fees. Adults from $19.95, children from $9.95. All tours are pet-friendly. Offers money-back guarantee. Tours run 7 nights per week.',
   '$10-20', 'Grave Tales tour, Beyond Good and Evil adults-only tour, Haunted pub crawls, Dead of Night tour', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Genteel & Bard', 'Savannah', 'GA',
   'https://genteelandbard.com/',
   'https://genteelandbard.com/best-savannah-walking-haunted-ghost-tours-fun-things-to-do',
   'Savannah''s audio-enhanced walking tour company where guides wear microphones and guests receive complimentary earbuds for crystal-clear audio up to 100 feet away. The Dark History & Ghost Encounter Tour covers about a mile of the Historic District over approximately 2 hours.',
   '$30-40', 'Ghost Encounter tours, Dark History tours, History walking tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('6th Sense World', 'Savannah', 'GA',
   'https://6thsenseworld.com/',
   'https://6thsenseworld.com/ghost-tours/sixth-sense-savannah-tours/',
   'Woman-owned tour company with over two decades of experience. Winner of TripAdvisor''s 2024 Travelers'' Choice Award (Top 10% Worldwide) and USA TODAY''s Top 10 Tours list. Pioneered ghost storytelling in Savannah''s southern Historic District since 2002. Offers both family-friendly (7pm) and adults-only (9:30pm) options.',
   '$30-40', 'Ghost tours, Bonaventure Cemetery tours, America''s Most Haunted City tour', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Sorrel Weed House', 'Savannah', 'GA',
   'https://sorrelweedhouse.com/',
   'https://sorrelweedhouse.com/',
   'One of the first homes in Georgia designated as a State Landmark and one of the most haunted houses in Savannah. Offers 75-minute ghost tours ($35) exploring dimly lit hallways with tales of murder, suicide, and slavery. Paranormal investigations ($75) for adults 18+ at 10:30pm. History tours $14.',
   '$14-75', 'History tours, Ghost tours, Paranormal investigations', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Savannah History & Haunts', 'Savannah', 'GA',
   'https://www.savannahhistoryandhaunts.com/',
   'https://www.savannahhistoryandhaunts.com/',
   'Candlelit historical ghost walking tour through Savannah''s streets. A 90-minute experience blending documented history with paranormal encounters in one of America''s most haunted cities.',
   '$25-35', 'Candlelit walking tours, Historical ghost tours', FALSE);

-- =====================================================
-- SALEM, MA - Witch trials history
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Spellbound Tours', 'Salem', 'MA',
   'https://spellboundtours.com/',
   'https://spellboundtours.com/spellbound-tour/',
   'Founded in 2000 by a certified parapsychologist, one of Salem''s oldest and most reputable tours. Explores ghosts, vampire folklore, true crime, and UFO sightings beyond the 1692 Witch Trials. Trains guests in scientific ghost detection methods. Adults $21, seniors/students $10, kids $7.',
   '$7-21', 'Witch tours, Ghost tours, Voodoo and Vampire tours, Paranormal detection tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Salem Historical Tours / Haunted Footsteps', 'Salem', 'MA',
   'https://www.salemhistoricaltours.com/',
   'https://www.salemhistoricaltours.com/haunted-footsteps-ghost-tour',
   'Salem''s first and finest ghostly stroll since 1997, the oldest permanent walking tour company in the city. The Haunted Footsteps Ghost Tour is a 90-minute lantern-lit experience featuring documented paranormal activity, chilling cemeteries, and tales of murder. Note: this is NOT a witch trials tour.',
   '$20-28', 'Haunted Footsteps ghost tours, History walking tours, Daytime witch trials tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Witch City Walking Tours', 'Salem', 'MA',
   'https://witchcitywalkingtours.com/',
   'https://witchcitywalkingtours.com/',
   'Rated as the top walking tour in Salem. A 2-hour experience of captivating history, supernatural tales, and the truth of the 1692 Salem Witch Trials. Takes visitors off the beaten path to lesser-known sights. Also offers Salem''s spookiest adults-only walking tour with tales of deception, torture, and murder.',
   '$25-35', 'Walking tours, Ghost tours, Adults-only tours, Witch trials history', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Salem Night Tour', 'Salem', 'MA',
   'https://www.salemghosttours.com/',
   'https://www.salemghosttours.com/',
   'Voted one of the 10 Best Ghost Tours in the US by USA Today''s "10 Best" five years in a row. Covers haunts, darker history, ghost stories, and the Salem Witch trials at night.',
   '$20-30', 'Night ghost tours, Witch trials tours, Haunted walking tours', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Salem Ghosts', 'Salem', 'MA',
   'https://salemghosts.com/',
   'https://salemghosts.com/',
   'Visits Salem''s most haunted and historic sites, following the spectral footsteps of judges, witches, and the wrongly condemned who still haunt the night. Tours held nightly rain or shine, meeting outside Salem Five Bank at 210 Essex St.',
   '$20-30', 'Ghost tours, Historic site tours, Witch history tours', FALSE);

-- =====================================================
-- ST. AUGUSTINE, FL - America's oldest city (450+ years)
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost Tours of St. Augustine', 'St. Augustine', 'FL',
   'http://www.ghosttoursofstaugustine.net/',
   'http://www.ghosttoursofstaugustine.net/tours---booking.html',
   'The ORIGINAL award-winning ghost tours, featured on the History Channel and Travel Channel. Started ghost touring in St. Augustine over 30 years ago and wrote the first books on the city''s ghosts that other companies still use for training.',
   '$25-35', 'Ghost walking tours, Haunted pub crawls, Paranormal investigations', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghosts & Gravestones St. Augustine', 'St. Augustine', 'FL',
   'https://www.ghostsandgravestones.com/st-augustine',
   'https://www.ghostsandgravestones.com/st-augustine/tickets',
   'Trolley ghost tour exploring the darker side of the Nation''s Oldest City. Includes stops at Potter''s Wax Museum Chamber of Horrors and the Old Jail (listed on Florida and National Register of Haunted Places, built by same company as Alcatraz). Adults $28.99, kids 6-12 $14.99. Rated PG-13.',
   '$15-29', 'Trolley ghost tours, Old Jail tours, Haunted history rides', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('GhoSt Augustine', 'St. Augustine', 'FL',
   'https://ghostaugustine.com/',
   'https://ghostaugustine.com/st-augustine-haunted-tours/',
   'Founded in 2001, independently owned. Started using and selling the K2 meter in 2001 and saved it from discontinuation in 2004 by investing in its production and supplying TAPS (TV''s Ghost Hunters). Offers non-theatrical ghost tours that avoid large crowds. Total Paranormal experience available.',
   '$39-79', 'Ghost walking tours, Paranormal investigations, Haunted pub tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('A Ghostly Encounter', 'St. Augustine', 'FL',
   'https://staugustineghosttours.net/',
   'https://staugustineghosttours.net/',
   'Award-winning 90-minute unscripted walking tour with professionally licensed guides weaving stories told from one generation to the next. Has exclusive access to the Oldest Wooden School House on St. George Street for a unique paranormal investigation with cutting-edge ghost-hunting tools.',
   '$25-35', 'Ghost walking tours, Paranormal investigations at Oldest Wooden School House', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Nightly Spirits St. Augustine', 'St. Augustine', 'FL',
   'https://nightlyspirits.com/st-augustine-ghost-tours/',
   'https://nightlyspirits.com/st-augustine-ghost-tours/',
   'Voted a top-rated ghost tour in America by USA Today two years in a row. Historic Haunted Booze & Boos Tours explore the spookiest places while stopping at several local bars to discover their haunted and historic past.',
   '$35-45', 'Haunted pub crawls, Booze & Boos tours, Ghost walking tours', FALSE);

-- =====================================================
-- CHARLESTON, SC - Historic haunted city
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Bulldog Tours', 'Charleston', 'SC',
   'https://www.bulldogtours.com/',
   'https://www.bulldogtours.com/tours/ghost',
   'Voted Charleston''s #1 Food, Ghost & History Tours. Licensed guides offer exclusive access to the city''s most alluring places including the Old Jail. USS Yorktown tour featured on SYFY''s Ghost Hunters. A portion of ticket purchases goes to preserving historic landmarks. Adults from $39, children 4-12 from $29.',
   '$29-39', 'Ghost & Graveyard tours, Haunted Jail tours, Dark Side of Charleston (R-rated), Ghost & Dungeon tours, Haunted Arsenal tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Tour Charleston LLC / The Ghosts of Charleston', 'Charleston', 'SC',
   'https://tourcharleston.com/',
   'https://tourcharleston.com/all-tours/the-ghosts-of-charleston-tour/',
   'No other tour company has attracted more media attention since starting in 1996. Recommended by The New York Times, Wall Street Journal, USA Today, Southern Living, and National Geographic Traveler. 90-minute tours recount stories from the best-selling book with exclusive nighttime access to the Unitarian Church Graveyard. Adults $25, students $19, children 7-12 $15.',
   '$15-25', 'Ghosts of Charleston walking tours, Graveyard tours, History tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost City Tours Charleston', 'Charleston', 'SC',
   'https://ghostcitytours.com/charleston/',
   'https://ghostcitytours.com/charleston/',
   'Part of the Ghost City network with over 9 million guests since 2012. The Death and Depravity Ghost Tour is Charleston''s #1 adults-only ghost tour with an unmatched 4.9-star rating. Also offers family-friendly options and top-rated Haunted Pub Crawl.',
   '$15-25', 'Death and Depravity adults-only tours, Family-friendly ghost tours, Haunted pub crawls', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Old Charleston Walking Tours / Pleasing Terrors', 'Charleston', 'SC',
   'https://oldcharlestontours.com/',
   'https://oldcharlestontours.com/ticket-info/1',
   'The Pleasing Terrors Ghost Tour is consistently rated one of Charleston''s best on TripAdvisor and Yelp. Created by Mike Brown, the city''s most experienced ghost tour guide with over 20 years of experience. He also hosts the Pleasing Terrors Podcast with 1.5+ million downloads in 100+ countries.',
   '$25-35', 'Pleasing Terrors ghost tours, Historical walking tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghostwalk Charleston', 'Charleston', 'SC',
   'https://www.ghostwalk.net/',
   'https://www.ghostwalk.net/',
   'The original ghost tour of Charleston with over 40 years of experience telling the real stories behind one of the most haunted cities in America. Family-friendly and pet-friendly tours.',
   '$20-30', 'Ghost walking tours, Historic haunted tours', FALSE);

-- =====================================================
-- GETTYSBURG, PA - Civil War battlefield ghost tours
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Mark Nesbitt''s Ghosts of Gettysburg', 'Gettysburg', 'PA',
   'https://ghostsofgettysburg.com/',
   'https://ghostsofgettysburg.com/our-tours/',
   'The original Ghost Tour in Gettysburg by former National Park Ranger and bestselling author Mark Nesbitt. Based on the famous Ghosts of Gettysburg book series. Period-dressed guides with candlelit lanterns lead 75-minute tours through downtown.',
   '$5-18', 'Candlelit walking tours, Author-led tours, Battlefield tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Gettysburg Battlefield Tours / Ghostly Images', 'Gettysburg', 'PA',
   'https://www.gettysburgbattlefieldtours.com/ghost-tours/',
   'https://www.gettysburgbattlefieldtours.com/ghost-tours/',
   'Only ghost tour that takes you inside two historic haunted homes. Offers Spirits of Jennie Wade Tour, Haunted Orphanage Tour, Ghost Bus Tours, midnight tours, and professional ghost hunts with Black Lantern Paranormal.',
   '$20-75', 'Walking tours, Bus tours, Paranormal investigations, Indoor haunted tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost City Tours Gettysburg', 'Gettysburg', 'PA',
   'https://ghostcitytours.com/gettysburg/',
   'https://ghostcitytours.com/gettysburg/',
   'Blood on the Battlefield is Gettysburg''s #1 adults-only ghost tour with a 4.8-star rating. Explores the darker truths of human nature and horrors of war. Starts at Ghost City Store on Lincoln Square.',
   '$15-25', 'Adults-only battlefield tours, Ghost walking tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Farnsworth House Ghost Tours', 'Gettysburg', 'PA',
   'https://www.farnsworthhouseinn.com/',
   'https://www.farnsworthhouseinn.com/',
   'Tours of one of the most haunted buildings in Gettysburg, an actual Civil War-era inn still in operation. Confederate sharpshooters occupied the house during the battle. Unique indoor haunted experience in a building with documented paranormal activity.',
   '$15-30', 'Indoor ghost tours, Historic inn tours, Mourning theater', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Civil War Ghosts Gettysburg', 'Gettysburg', 'PA',
   'https://gettysburgghosts.com/',
   'https://gettysburgghosts.com/',
   'Nightly ghost tours rain or shine exploring the haunted Welty House and Historic Jennie Wade Birthplace. Little Round Top featured as one of America''s most hallowed and haunting sites.',
   '$20-35', 'Walking tours, Battlefield tours, Historic homes tours', FALSE);

-- =====================================================
-- SAN ANTONIO, TX - Alamo area tours
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Alamo City Ghost Tours', 'San Antonio', 'TX',
   'https://alamocityghosttours.com/',
   'https://alamocityghosttours.com/',
   'Tours start at San Fernando Cathedral with state-of-the-art ghost-hunting equipment provided. Explores ghostly legends and paranormal activity around the Alamo, downtown churches, and the River Walk.',
   '$25-40', 'Ghost walking tours, Paranormal equipment tours, Alamo tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('RJA Ghost Tours', 'San Antonio', 'TX',
   'https://www.rjaghosttours.com/',
   'https://www.rjaghosttours.com/',
   'Authentic ghost tours led by Certified Paranormal Investigators. Nightly tours covering the Alamo hauntings, local folklore, and mysterious locations throughout downtown San Antonio.',
   '$25-35', 'Ghost walking tours, Paranormal investigation tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('River City Ghosts', 'San Antonio', 'TX',
   'https://rivercityghosts.com/',
   'https://rivercityghosts.com/',
   'Explores haunted San Antonio including the Alamo ghosts and the Menger Hotel where history never checks out. Nightly tours rain or shine. Features the city''s 300-year haunted history along the River Walk.',
   '$25-35', 'Ghost walking tours, River Walk tours, History tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Bad Wolf Ghost Tours / Sisters Grimm', 'San Antonio', 'TX',
   'https://badwolfghosttours.com/',
   'https://badwolfghosttours.com/',
   'San Antonio Ghost Walk explores downtown''s oldest and most haunted locations including the Alamo and River Walk. Also offers a Haunted Pub Crawl (21+) and Haunted Dinner Tour at the Emily Morgan Hotel.',
   '$25-65', 'Ghost walking tours, Haunted pub crawls, Haunted dinner tours', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('The Alamo Ghost Hunt Tour', 'San Antonio', 'TX',
   'https://www.viator.com/tours/San-Antonio/The-Alamo-Ghost-Hunt-Interactive-Ghost-Tour-in-San-Antonio/d5475-24479P1',
   'https://www.viator.com/tours/San-Antonio/The-Alamo-Ghost-Hunt-Interactive-Ghost-Tour-in-San-Antonio/d5475-24479P1',
   'Interactive ghost hunt using EMF devices and dowsing rods. Well-informed guides share the history of old buildings and the Alamo. Guests actively participate in investigating paranormal activity.',
   '$30-45', 'Interactive ghost hunts, Equipment-provided tours, Alamo tours', FALSE);

-- =====================================================
-- KEY WEST, FL - Island ghost tours
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Sloan''s Key West Ghost Tours / Haunted Key West', 'Key West', 'FL',
   'https://www.hauntedkeywest.com/',
   'https://www.hauntedkeywest.com/',
   'The only tour where you can meet Robert the Doll, the world''s most haunted doll. Run by David L. Sloan, author of Ghosts of Key West. Offers VIP Fort East Martello Ghost Tour, Robert the Doll Experience, and firehouse paranormal investigations.',
   '$25-75', 'Robert the Doll tours, Fort ghost tours, Paranormal investigations', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghosts & Gravestones Key West', 'Key West', 'FL',
   'https://www.ghostsandgravestones.com/key-west',
   'https://www.ghostsandgravestones.com/key-west',
   'Voted Top Ten Best Ghost Tour by USA Today Readers'' Choice. The Trolley of the Doomed experience features a 17th-century gravedigger guide. Includes stops at the Key West Shipwreck Treasure Museum.',
   '$35-45', 'Trolley tours, Theatrical ghost tours, Museum stops', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Key West Ghost and Mysteries Tour', 'Key West', 'FL',
   'https://keywestghostandmysteriestour.com/',
   'https://keywestghostandmysteriestour.com/',
   'Over 20 years researching Key West''s haunted history. Personal and interactive tours with guides sharing documented and personal paranormal experiences. Key West derives from "cayo hueso" meaning Island of Bones.',
   '$25-35', 'Ghost walking tours, History tours, Mystery tours', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Key West Ghost Hunt', 'Key West', 'FL',
   'https://ghosthuntkeywest.com/',
   'https://ghosthuntkeywest.com/',
   'The original and best haunted tours in Key West with ghost hunting equipment provided to all guests. Interactive paranormal experiences exploring the Island of Bones after dark.',
   '$30-45', 'Ghost hunt tours, Equipment-provided tours, Interactive tours', FALSE);

-- =====================================================
-- CHICAGO, IL - Gangster/ghost tours
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Chicago Gangsters and Ghosts Tours', 'Chicago', 'IL',
   'https://gangstersandghosts.com/',
   'https://gangstersandghosts.com/',
   'Step back a century into lawless Chicago where crime syndicates fought for territory. Historical tours bringing ghost stories to life alongside gangster history from the Roaring Twenties. Covers speakeasies, Al Capone haunts, and haunted landmarks.',
   '$25-35', 'Gangster history tours, Ghost walking tours, Prohibition tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('American Ghost Walks - Chicago Hauntings', 'Chicago', 'IL',
   'https://www.americanghostwalks.com/chicago',
   'https://www.americanghostwalks.com/chicago',
   'Now in their 24th year offering the Original Chicago Hauntings Ghost Bus Tour. 3-hour luxury coach tour visiting Iroquois Theater, St. Valentine''s Day Massacre site, and Congress Plaza Hotel. Multiple bus and walking tour options available.',
   '$35-89', 'Ghost bus tours, Walking tours, Cemetery tours, Pub crawls', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Nightly Spirits Chicago', 'Chicago', 'IL',
   'https://nightlyspirits.com/chicago-ghost-tours/',
   'https://nightlyspirits.com/chicago-ghost-tours/',
   'Ghostly pub tours exploring haunted bars, alleys, and buildings. Visit Prohibition-era sites frequented by John Dillinger and Al Capone. 2.5-hour tours with drinks at each haunted bar stop.',
   '$28-35', 'Haunted pub crawls, Gangster tours, Ghost walking tours', FALSE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Chicago Crime Tours', 'Chicago', 'IL',
   'https://www.chicagocrimetours.com/',
   'https://www.chicagocrimetours.com/',
   'Bus tours focusing on Chicago''s organized crime history. Visit sites connected to Al Capone, John Dillinger, and the St. Valentine''s Day Massacre. True crime history combined with documented ghost sightings.',
   '$40-60', 'Crime history bus tours, Gangster tours, Ghost tours', FALSE);

-- =====================================================
-- NASHVILLE / FRANKLIN, TN - Civil War ghost tours
-- =====================================================

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Franklin on Foot', 'Franklin', 'TN',
   'https://www.franklinonfoot.com/',
   'https://www.franklinonfoot.com/ghosttour',
   'Sharing local ghost stories since 2003. Haunted Franklin tour explores ghosts on brick-lined streets including Civil War spy spirits, Confederate soldiers, and departed socialites. 90-minute walking tours through one of the bloodiest Civil War battle sites.',
   '$20-30', 'Ghost walking tours, Civil War tours, History tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost City Tours Franklin', 'Franklin', 'TN',
   'https://ghostcitytours.com/franklin/',
   'https://ghostcitytours.com/franklin/',
   'Ghosts of Franklin Tour through the heart of town where echoes of the Civil War still resonate. Visit sites where thousands of soldiers died in just five hours during one of the war''s bloodiest battles (Battle of Franklin, 1864).',
   '$15-25', 'Ghost walking tours, Civil War battlefield tours', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Nashville Ghost Tours / Amerighost', 'Nashville', 'TN',
   'https://www.amerighost.com/nashville-ghost-tours',
   'https://www.amerighost.com/nashville-ghost-tours',
   'First locally owned Nashville ghost tour since 2003. Offers Haunted Downtown (lantern tour of Ryman Auditorium, Capitol, Printers Alley), Haunted Tavern Tour, and Haunted Hearse Tour in a 10-passenger converted hearse.',
   '$17-35', 'Lantern walking tours, Haunted hearse tours, Pub crawls', TRUE);

INSERT INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('US Ghost Adventures Nashville', 'Nashville', 'TN',
   'https://usghostadventures.com/nashville-ghost-tour/',
   'https://usghostadventures.com/nashville-ghost-tour/',
   'One-hour tours covering Nashville''s Civil War haunted history. Features The Gray Man sightings at Ryman Auditorium and buildings transformed into makeshift hospitals that still harbor restless spirits.',
   '$25-30', 'Ghost walking tours, Civil War tours', FALSE);
