-- Seed data for Kentucky haunted places
-- Generated by researcher agent on 2026-01-21

-- ==========================================
-- LOUISVILLE AREA (~15 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('waverly-hills-sanatorium', 'Waverly Hills Sanatorium', 'Louisville', '4400 Paralee Lane', 'KY', 38.1656, -85.8425, 'hospital',
   'Perhaps the most famous haunted building in Kentucky, this former tuberculosis hospital opened in 1910 and expanded to a massive facility by 1926. An estimated 63,000 patients died here before it closed in 1961, making it one of the most paranormally active locations in America.',
   'The sanatorium''s "Death Tunnel" - a 500-foot underground passage used to discreetly remove corpses - is the epicenter of paranormal activity. The ghost of a nurse who hanged herself in Room 502 is frequently seen. A little boy named Timmy plays ball with visitors, and the shadowy "Creeper" crawls along walls and ceilings. Disembodied screams, footsteps, and apparitions are so common that Waverly Hills has been featured on Ghost Hunters, Ghost Adventures, and Most Haunted.',
   1910, 'https://www.hauntedrooms.com/kentucky/haunted-places'),

  ('bobby-mackeys-music-world', 'Bobby Mackey''s Music World', 'Wilder', '44 Licking Pike', 'KY', 39.0456, -84.4928, 'other',
   'Called "The Most Haunted Nightclub in America," this honky-tonk bar in northern Kentucky was built on the site of a 19th-century slaughterhouse. Before becoming a country music venue in 1978, the building witnessed Satanic rituals, a gruesome decapitation murder, and multiple suicides.',
   'In 1896, Pearl Bryan was decapitated by her lover Scott Jackson, and her head was never found - some say it was thrown down the well in the basement, which is now called a "Portal to Hell." Patrons have been scratched, pushed, and even possessed. Former caretaker Carl Lawson was reportedly exorcised in the building, and his voice has been captured on EVPs after his death. Country singer Bobby Mackey has witnessed so much activity he posts a warning sign at the entrance.',
   1978, 'https://kyforky.com/blogs/journal/haunted-places'),

  ('seelbach-hilton-hotel', 'The Seelbach Hilton Hotel', 'Louisville', '500 South 4th Street', 'KY', 38.2497, -85.7564, 'hotel',
   'This grand Beaux-Arts hotel opened in 1905 and quickly became one of the finest in the nation. F. Scott Fitzgerald was so impressed he used it as the setting for Tom and Daisy Buchanan''s wedding in The Great Gatsby. The hotel also hosted gangsters like Al Capone during Prohibition.',
   'The most famous ghost is Patricia Wilson, the "Lady in Blue." In 1936, she came to the Seelbach to reconcile with her estranged husband, but he died in a car accident on his way to meet her. Devastated, she was found dead at the bottom of the service elevator shaft. Her apparition in a blue chiffon dress haunts the 8th floor, and guests report the scent of lilac perfume and feeling a presence touch their shoulder in the elevator.',
   1905, 'https://usghostadventures.com/americas-most-haunted-hotels-and-inns/the-haunted-seelbach-hotel/'),

  ('cave-hill-cemetery', 'Cave Hill Cemetery', 'Louisville', '701 Baxter Avenue', 'KY', 38.2456, -85.7178, 'cemetery',
   'This stunning 296-acre Victorian cemetery established in 1848 is the final resting place of Colonel Sanders, Muhammad Ali, and George Rogers Clark. With 138,000 graves amid Gothic mausoleums and ancient oaks, it''s considered one of the most beautiful - and most haunted - cemeteries in Kentucky.',
   'The "Lady in Black" is a grieving Civil War widow who wanders the grounds at night carrying flowers, leaving cold breezes in her wake. A little girl named Evelyth, who died at age seven, has been seen playing among the headstones. Green orbs hover over graves, disembodied whispers are heard near the mausoleums, and some visitors report being pushed or touched by unseen hands.',
   1848, 'https://www.kentuckyhauntedhouses.com/real-haunt/cave-hill-cemetery.html'),

  ('belle-of-louisville', 'Belle of Louisville', 'Louisville', '401 West River Road', 'KY', 38.2586, -85.7700, 'other',
   'This authentic steamboat launched in 1914 is the oldest operating Mississippi-style steamboat in existence. During World War II, Captain Ben Winters installed gambling equipment on board, but a police raid led to his fatal heart attack - and he never left.',
   'Captain Ben Winters died of a heart attack during the police raid, and employees say he haunts the boat to this day. His apparition has been seen on the deck and in the pilot house. Strange sounds, footsteps, and cold spots are reported throughout the vessel. Some believe other spirits from the steamboat''s long history also remain aboard.',
   1914, 'https://www.hauntedrooms.com/kentucky/louisville/haunted-places'),

  ('conrad-caldwell-house', 'Conrad-Caldwell House', 'Louisville', '1402 St. James Court', 'KY', 38.2367, -85.7639, 'mansion',
   'Built in the 1890s in the heart of Old Louisville, this stunning Richardsonian Romanesque mansion is one of the finest examples of Victorian architecture in America. The ornate home features gargoyles, elaborate stonework, and multiple stories of paranormal activity.',
   'Tour guides report hearing things moving in the attic when no one is there. Cold spots that feel like embracing hugs suddenly surround visitors. Footsteps echo through empty hallways, and apparitions have been seen in period clothing. The mansion''s dark, ornate interior provides the perfect atmosphere for the spirits that never left.',
   1893, 'https://www.gothichorrorstories.com/haunted-travels/ohio-river-valley/louisville/haunted-old-louisville/'),

  ('dupont-mansion', 'DuPont Mansion Bed and Breakfast', 'Louisville', '1317 South Fourth Street', 'KY', 38.2344, -85.7628, 'hotel',
   'This elegant Italianate mansion in Old Louisville was once home to the prominent DuPont family. Alfred Victor DuPont, known as "Uncle Vic," was the patriarch who oversaw the family''s Louisville operations in the late 1800s.',
   'Uncle Vic''s ghost is said to haunt the mansion, particularly his former bedroom. After one of the DuPont brothers was murdered by a prostitute, witnesses claim his spirit haunts nearby Central Park. Guests at the bed and breakfast report footsteps, doors opening and closing, and the sensation of being watched by unseen eyes.',
   1879, 'https://www.gothichorrorstories.com/haunted-travels/ohio-river-valley/louisville/haunted-old-louisville/'),

  ('witches-tree', 'The Witches'' Tree', 'Louisville', '6th Street and Park Avenue', 'KY', 38.2378, -85.7617, 'other',
   'This gnarled, twisted oak tree in Central Park is one of Louisville''s most iconic supernatural landmarks. Covered in beads, charms, and trinkets left by visitors, the tree stands as a monument to a legendary curse placed by witches in 1889.',
   'According to legend, witches in Old Louisville held their meetings beneath a great oak tree. In 1889, the city decided to cut it down, and the witches warned of terrible consequences. When the tree was felled anyway, the witches cursed the spot. From the stump grew this knotted, twisted tree that seems to defy nature. People now leave offerings for good luck and toss beads on branches to make wishes, believing the witches still watch over their gathering place.',
   1889, 'https://www.wdrb.com/news/haunted-old-louisville-legends-ghosts-and-the-witches-tree/article_80b407ba-f6b7-4797-86df-5127172303b6.html'),

  ('louisville-palace-theatre', 'Louisville Palace Theatre', 'Louisville', '625 South Fourth Street', 'KY', 38.2486, -85.7576, 'theater',
   'This ornate Spanish Baroque movie palace opened in 1928 and is one of the most beautiful theaters in America. With its elaborate ceiling depicting a night sky and ornate plasterwork, the Louisville Palace is a masterpiece of theatrical design - and reportedly home to several spirits.',
   'The grand theater is considered one of the most haunted buildings in Louisville. Spectral figures have been seen wandering backstage and in the balcony areas. Employees report cold spots, unexplained sounds, and the feeling of being watched. The spirits seem particularly active during rehearsals and late-night events.',
   1928, 'https://www.gotolouisville.com/blog/spectral-spots-around-louisville/'),

  ('speed-art-museum', 'Speed Art Museum', 'Louisville', '2035 South Third Street', 'KY', 38.2178, -85.7611, 'museum',
   'Kentucky''s oldest and largest art museum was established in 1927 by Hattie Bishop Speed as a memorial to her husband J.B. Speed. The museum houses over 13,000 works spanning 6,000 years of human history.',
   'Hattie Bishop Speed, an ultra-organized perfectionist, reportedly still watches over her museum. Her apparition in a white dress has been seen floating through the galleries, examining the art on display. Security cameras have captured her cloudy form, and employees report the scent of lavender and lights flickering in her playful presence. She seems to approve of how her museum has been maintained.',
   1927, 'https://www.gotolouisville.com/blog/spectral-spots-around-louisville/'),

  ('sauerkraut-cave', 'Sauerkraut Cave', 'Louisville', 'E.P. Tom Sawyer State Park', 'KY', 38.2897, -85.5492, 'other',
   'Located in E.P. Tom Sawyer State Park, this cave is the last remnant of the Lakeland Asylum (later Central State Hospital), where horrific early experiments on the mentally ill took place. The cave was used to store goods including sauerkraut.',
   'Patients from Lakeland Asylum attempted to escape through underground tunnels that exited through Sauerkraut Cave. Many never made it out, dying in the dark passages. Though the asylum was demolished, visitors to the cave report eerie voices, unexplained phenomena, and the sensation of being watched by tortured souls who never found freedom.',
   1873, 'https://www.kentuckyhauntedhouses.com/real-haunt/sauerkraut-cave.html'),

  ('louisville-bourbon-inn', 'Louisville Bourbon Inn', 'Louisville', '1332 South Fourth Street', 'KY', 38.2339, -85.7625, 'hotel',
   'This elegant bed and breakfast in Old Louisville occupies a beautifully restored Victorian mansion. The inn combines Southern hospitality with the neighborhood''s rich haunted history.',
   'The ghost of Annie Whipple, a nanny from the 1880s, is said to roam the inn. According to legend, when a child in her care fell gravely ill, Annie desperately tried to summon a doctor from beyond the grave to save the child. Her devoted spirit remains, watching over guests and the home she loved.',
   1880, 'https://www.gothichorrorstories.com/haunted-travels/ohio-river-valley/louisville/haunted-old-louisville/');

-- ==========================================
-- LEXINGTON AREA (~8 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('mary-todd-lincoln-house', 'Mary Todd Lincoln House', 'Lexington', '578 West Main Street', 'KY', 38.0506, -84.5047, 'mansion',
   'This Georgian-style brick house was the childhood home of Mary Todd, who would become the wife of President Abraham Lincoln. Built in 1806, it''s the first historic site restored in honor of a First Lady and is open for tours from March through November.',
   'Mary Todd''s life was filled with tragedy - the deaths of three sons, her husband''s assassination, and her own struggles with mental illness. Visitors and staff report strange occurrences including unexplained noises, disembodied voices, and the sensation of being touched. Children have reported seeing a woman''s spirit in Mary''s former bedroom, and rocking chairs move on their own. Her apparition has been glimpsed in reflective surfaces.',
   1806, 'https://usghostadventures.com/lexington-ghost-tour/'),

  ('ashland-henry-clay-estate', 'Ashland - The Henry Clay Estate', 'Lexington', '120 Sycamore Road', 'KY', 38.0256, -84.4869, 'mansion',
   'This elegant estate was home to Henry Clay, "The Great Compromiser," one of the most influential American statesmen of the 19th century. Clay served as Secretary of State, Speaker of the House, and three-time presidential candidate.',
   'Henry Clay himself is said to haunt his beloved Ashland. His ghost - a white-haired apparition in a black frock coat - has been seen in the old red parlor room (now his study), leaning against the fireplace mantel and gazing at mementos of his achievements. Flickering lights, disembodied footsteps, and unexplained cold spots are common. Clay seems to approve of how Ashland has been preserved.',
   1806, 'https://www.hauntedrooms.com/kentucky/lexington/haunted-places'),

  ('transylvania-university', 'Transylvania University - Old Morrison', 'Lexington', '300 North Broadway', 'KY', 38.0522, -84.4983, 'university',
   'Founded in 1780, Transylvania is the 16th oldest institution of higher learning in America. Old Morrison, the iconic Greek Revival administration building, has twice burned and been rebuilt, leading many to believe it''s cursed.',
   'Professor Constantine Rafinesque, a brilliant but eccentric botanist, was fired in 1826 under disputed circumstances. Standing in Old Morrison''s doorway, he cursed the university in an ancient dead language: "Damn thee and thy school!" The curse strikes every seven years - including two fires that destroyed Old Morrison. A student who died by suicide still haunts the building. In 1924, Rafinesque''s remains were reinterred on campus to end the curse, but strange occurrences continue.',
   1780, 'https://lextoday.6amcity.com/the-curse-of-constantine-rafinesque-lexington-ky'),

  ('lexington-opera-house', 'Lexington Opera House', 'Lexington', '401 West Short Street', 'KY', 38.0494, -84.5011, 'theater',
   'Built in 1886, this beautifully restored Victorian opera house has hosted performances for over 135 years. The ornate theater is renowned for its excellent acoustics and intimate atmosphere - and its resident ghost.',
   'The "Man in Gray" is the Lexington Opera House''s famous phantom. This spectral figure, dressed in gray period clothing, appears in the balcony during rehearsals, watching the performers below. His identity remains unknown, but he seems content to observe the shows from his favorite seat for eternity.',
   1886, 'https://www.hauntedrooms.com/kentucky/lexington/haunted-places'),

  ('gratz-park-inn', 'Gratz Park Inn', 'Lexington', '120 West Second Street', 'KY', 38.0503, -84.4994, 'hotel',
   'This historic inn in downtown Lexington occupies a beautifully restored building in the elegant Gratz Park neighborhood. The hotel combines modern amenities with 19th-century charm - and multiple resident ghosts.',
   'Several spirits call the Gratz Park Inn home. A lady in a white dress and matching hat glides through the halls. A young girl runs through the corridors playing jacks. An elderly man''s ghost turns televisions on and off. Drunken partygoers from a bygone era have been heard celebrating, and a sad-looking man''s apparition appears on the lower level.',
   1916, 'https://www.kentuckyhauntedhouses.com/real-haunt/gratz-park-inn.html'),

  ('bodley-bullock-house', 'Bodley-Bullock House', 'Lexington', '200 Market Street', 'KY', 38.0475, -84.4978, 'mansion',
   'This Federal-style mansion, built in 1814, is one of Lexington''s oldest and most distinguished homes. The house has served as a residence for prominent families and witnessed nearly two centuries of Kentucky history.',
   'The Bodley-Bullock House is reportedly haunted by former residents who refused to leave. Visitors report cold spots, unexplained sounds, and the feeling of being watched. Apparitions in period clothing have been glimpsed in the windows and doorways. The house''s long history has left multiple spirits in residence.',
   1814, 'https://www.hauntedplaces.org/lexington-ky/'),

  ('lexington-cemetery', 'Lexington Cemetery', 'Lexington', '833 West Main Street', 'KY', 38.0517, -84.5153, 'cemetery',
   'Established in 1848, this 170-acre Victorian cemetery is one of the oldest and most beautiful in Kentucky. The grounds feature stunning monuments, ancient trees, and the graves of Henry Clay, John Hunt Morgan, and other notable Kentuckians.',
   'Visitors to Lexington Cemetery report seeing apparitions among the monuments, particularly near the graves of Civil War soldiers. Unexplained lights have been photographed hovering over headstones. The sound of horses'' hooves echoes through empty paths - possibly the cavalry of John Hunt Morgan still riding. Cold spots and the sensation of unseen presences are common.',
   1848, 'https://www.hauntedplaces.org/lexington-ky/'),

  ('hunt-morgan-house', 'Hunt-Morgan House', 'Lexington', '201 North Mill Street', 'KY', 38.0525, -84.4961, 'mansion',
   'Built in 1814, this Federal-style mansion was home to John Wesley Hunt, Kentucky''s first millionaire, and later to his great-grandson, Confederate General John Hunt Morgan, the "Thunderbolt of the Confederacy."',
   'The ghost of John Hunt Morgan, who was killed in 1864, is said to return to his childhood home. His apparition in Confederate gray has been seen on the grounds. The spirits of enslaved people who worked in the house are also believed to remain. Visitors report cold spots, footsteps, and the feeling of being watched by those who lived and died here.',
   1814, 'https://www.hauntedplaces.org/lexington-ky/');

-- ==========================================
-- BARDSTOWN AREA (~5 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('old-talbott-tavern', 'Old Talbott Tavern', 'Bardstown', '107 West Stephen Foster Avenue', 'KY', 37.8092, -85.4669, 'restaurant',
   'Opened in 1779, the Old Talbott Tavern is one of the oldest western stagecoach stops in America. This historic inn has hosted Daniel Boone, Abraham Lincoln, French King Louis Philippe, and the outlaw Jesse James.',
   'Jesse James is the tavern''s most famous ghost. Legend says he fired his pistol at a figure in his room, only to watch it vanish. His menacing laugh echoes through the building. The spirits of six Talbott children who died in the 1880s - including one who fell down the stairs and another who hanged herself - also haunt the inn. The "Lady in White" floats past windows and through the dining room. The Daniel Boone Room is considered the most haunted.',
   1779, 'https://talbotttavern.com/ghost-encounters/'),

  ('my-old-kentucky-home', 'My Old Kentucky Home (Federal Hill)', 'Bardstown', '501 East Stephen Foster Avenue', 'KY', 37.8067, -85.4533, 'mansion',
   'This stately 1818 mansion inspired Stephen Foster''s beloved song "My Old Kentucky Home" - now the official state song. Built by Judge John Rowan, the house witnessed tremendous tragedy including the deaths of eight family members and eight enslaved people from cholera in a single 24-hour period.',
   'Judge Rowan''s adult son fell from his bedroom window to his death on the property. His grieving mother is said to roam the halls, forever searching for her lost child. The mass cholera deaths left an indelible mark on the mansion. Visitors report cold spots, unexplained sounds, and sightings of apparitions in period dress throughout the house.',
   1818, 'https://visitbardstown.com/6-historic-and-spooky-places-to-visit-in-bardstown-kentucky/'),

  ('jailers-inn', 'Jailer''s Inn Bed and Breakfast', 'Bardstown', '111 West Stephen Foster Avenue', 'KY', 37.8092, -85.4678, 'prison',
   'Kentucky''s oldest operating jail complex operated from 1797 to 1987 before being converted to an eccentric bed and breakfast. The Travel Channel named it one of the 10 Most Haunted Places in the United States.',
   'Mrs. McKay, one of the original jailers, is the most frequently seen ghost. She appears at the foot of beds, watching over sleeping guests with such regularity that some pack up and leave in the middle of the night. Ghost hunter Patti Starr believes Esther, who followed her husband to jail in spirit form, is the most active presence. The courtyard where the gallows stood is particularly haunted. Guests feel presences sitting beside them and ghostly touches.',
   1797, 'https://www.kentuckyhauntedhouses.com/real-haunt/jailers-inn-bed-breakfast.html'),

  ('pioneer-cemetery-bardstown', 'Pioneer Cemetery', 'Bardstown', '4th Street', 'KY', 37.8089, -85.4686, 'cemetery',
   'Located directly behind the Jailer''s Inn, this ancient burial ground dates to the 1700s and hasn''t been used since the 1850s. Chest tombs and weathered headstones mark the final resting places of Bardstown''s earliest settlers.',
   'The cemetery''s proximity to the old jail and gallows has left it imbued with supernatural energy. Visitors report seeing apparitions among the aged monuments, particularly at twilight. Unexplained lights, cold spots, and the sensation of being watched are common. Some believe the spirits of executed prisoners wander here.',
   1780, 'https://bourbonmanor.com/blog/haunted-places-in-kentucky-bardstown/'),

  ('springhill-winery', 'Springhill Winery and Plantation B&B', 'Bloomfield', '3205 Springfield Road', 'KY', 37.8711, -85.3297, 'mansion',
   'This stately 1857 plantation combines a working winery with a bed and breakfast in a historic antebellum mansion. The property has witnessed over 165 years of Kentucky history.',
   'The plantation''s Civil War era and enslaved past have left spiritual imprints on the property. Guests report paranormal activity throughout the mansion, including unexplained sounds, cold spots, and apparitions. The combination of elegant hospitality and haunted history makes it a unique destination.',
   1857, 'https://bourbonmanor.com/blog/ghost-tours-historic-bardstown/');

-- ==========================================
-- FRANKFORT AREA (~4 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('liberty-hall', 'Liberty Hall', 'Frankfort', '202 Wilkinson Street', 'KY', 38.1983, -84.8733, 'mansion',
   'Built in 1796 by John Brown, Kentucky''s first U.S. Senator, Liberty Hall is one of the finest Georgian-style mansions in the state. The house and gardens are now a historic site and museum.',
   'The "Gray Lady" is Kentucky''s most famous ghost. Margaretta Varick came to visit her niece in 1817 but died just three days after arriving. By 1822, family members reported seeing "old Aunt Varick" in ghostly form. In the 1880s, Mary Mason "Mame" Scott awoke three nights in a row to find a tall, gray-veiled figure at the foot of her bed. A 1965 photograph captured a vaporous figure on the stairs. Two other ghosts - a Spanish opera singer who vanished in the garden in 1805 and a British soldier from 1812 - also haunt the grounds.',
   1796, 'https://libertyhall.org/more/haunted-history'),

  ('old-state-capitol', 'Old State Capitol Building', 'Frankfort', '300 West Broadway', 'KY', 38.1997, -84.8764, 'museum',
   'This National Historic Landmark served as Kentucky''s Capitol from 1830 to 1910, designed by Kentucky''s first professional architect, Gideon Shryock. The building witnessed the assassination of Governor William Goebel in 1900 - the only sitting governor ever assassinated in U.S. history.',
   'Governor William Goebel was shot on January 30, 1900, just steps from the Capitol. His blood stained the street and his spirit has never left. His apparition paces alongside the building, particularly near the infamous "conjure chest" - a cursed piece of furniture inside. Mysterious gunshots have been heard from the rear arsenal building. The violence surrounding the 1900 election left an indelible supernatural mark.',
   1830, 'https://spectrumnews1.com/ky/louisville/news/2021/10/15/the-old-capitol-building-said-to-be-haunted'),

  ('buffalo-trace-distillery', 'Buffalo Trace Distillery', 'Frankfort', '113 Great Buffalo Trace', 'KY', 38.2108, -84.8622, 'other',
   'America''s oldest continuously operating distillery has been making bourbon on this site since 1775, sitting on an ancient buffalo crossing along the Kentucky River. Ghost Hunters featured the distillery in 2011.',
   'Colonel Albert B. Blanton, who guided the distillery through Prohibition by selling "medicinal" bourbon, died at Stony Point mansion in 1959 but never left. Security guards see his apparition and hear voices in his former meeting room. Warehouse C, dating to the late 1800s, is the most haunted - tour guides hear heavy boots walking above them but find no one there. Security guard Zack Evans saw an old man in worker''s clothing every day for a week, but surveillance footage showed no one was there.',
   1775, 'https://www.kentuckyhauntedhouses.com/real-haunt/buffalo-trace-distillery.html'),

  ('frankfort-cemetery', 'Frankfort Cemetery', 'Frankfort', '215 East Main Street', 'KY', 38.2003, -84.8678, 'cemetery',
   'Established in 1844 on a bluff overlooking the Kentucky River, this historic cemetery is the final resting place of Daniel Boone, Theodore O''Hara (author of "The Bivouac of the Dead"), and Governor William Goebel.',
   'Daniel Boone''s grave draws visitors from around the world, and some report feeling his pioneering spirit watching over the cemetery. The grave of assassinated Governor Goebel is said to emanate supernatural energy. Unexplained lights, cold spots, and apparitions in period clothing have been reported throughout the grounds.',
   1844, 'https://www.kentuckyafterdark.com/locations/frankfort-ky');

-- ==========================================
-- MAMMOTH CAVE AREA (~3 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('mammoth-cave', 'Mammoth Cave National Park', 'Mammoth Cave', '1 Mammoth Cave Parkway', 'KY', 37.1870, -86.1008, 'other',
   'The longest known cave system in the world, with over 400 miles of explored passages, has been a tourist attraction since 1816. The cave''s constant 54-degree temperature and unique atmosphere have made it the site of both wonder and tragedy.',
   'In the 1840s, Dr. John Croghan built huts inside the cave to treat tuberculosis patients - all 15 got worse and two died within the first year. Their phantom coughs still echo through the passages. Stephen Bishop, an enslaved guide who mapped much of the cave, is seen leading phantom tours. Floyd Collins, who died trapped in nearby Crystal Cave in 1925, calls for help from beyond the grave. Melissa, a woman who allegedly abandoned a suitor in the cave without a lamp, searches for his spirit. Park rangers have documented over 150 paranormal events.',
   1816, 'https://www.nationalparkstraveler.org/2009/10/mammoth-cave-national-park-harbors-more-few-ghost-stories4820'),

  ('lost-river-cave', 'Lost River Cave', 'Bowling Green', '2818 Nashville Road', 'KY', 36.9453, -86.4753, 'other',
   'This unique underground river cave has served Native Americans, Civil War soldiers, a milling operation, and even a 1930s nightclub. The cave was known as "Dead Man''s Cave" or "Purgatory Cave" before its current name.',
   'Civil War soldiers who died on the property are said to remain. The cave''s time as a wild Prohibition-era nightclub left spiritual residue. Multiple buildings on the property mysteriously burned down throughout history. The "Lost Tales of the Underground" tour reveals the cave''s darker history, including stories of death and disappearance in its depths.',
   1933, 'https://www.wbko.com/2024/10/29/hometown-haunting-lost-river-cave-reveals-dark-history-new-specialty-tour/'),

  ('octagon-hall', 'Octagon Hall Museum', 'Franklin', '6040 Bowling Green Road', 'KY', 36.6958, -86.5533, 'mansion',
   'This distinctive eight-sided house was built in 1847 by 33rd degree Mason Andrew Jackson Caldwell. During the Civil War, the Confederate sympathizer hid soldiers in walls, under stairs, and in bricked-up basement passages.',
   'Confederate soldiers hidden in the house died there and never left. A young girl named Mary burned to death when her dress caught fire. Visitors hear mysterious dragging sounds like wounded soldiers and see shadow figures staring from windows. The spirit of a soldier has been photographed in the driveway. Featured on Ghost Hunters, My Ghost Story, and Most Terrifying Places in America.',
   1847, 'https://www.octagonhallmuseum.com/paranormal');

-- ==========================================
-- CIVIL WAR SITES (~4 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('perryville-battlefield', 'Perryville Battlefield State Historic Site', 'Perryville', '1825 Battlefield Road', 'KY', 37.6667, -84.9722, 'battlefield',
   'The site of Kentucky''s largest and bloodiest Civil War battle on October 8, 1862. Over 7,600 soldiers were killed or wounded, and Confederate corpses were left to rot on the field - a mass grave holds 300 Confederate soldiers.',
   'Park Manager Bryan Bush says, "We''re really haunted. So much stuff happens around here, we don''t even pay attention anymore." Bugle calls and regimental bands play at night. A Confederate soldier named Sam walks out of the opera house in full uniform, crosses the street, and vanishes. Two reenactors were visited in their tent by a soldier demanding to know about missing men - both names they gave matched soldiers killed at Perryville. Ghost Adventures captured EVPs saying "Jefferson Davis" when asked about their president.',
   1862, 'https://www.perryvillebattlefield.org/html/paranormal_tours.html'),

  ('white-hall', 'White Hall State Historic Site', 'Richmond', '500 White Hall Shrine Road', 'KY', 37.8397, -84.3200, 'mansion',
   'This 44-room mansion was expanded in the 1860s by Cassius Marcellus Clay, the fiery abolitionist, duelist, and friend of Abraham Lincoln who later served as ambassador to Russia. The original 1799 structure was built by his father, General Green Clay.',
   'Cassius Clay lived to 93 and seems to have never left. Tour guides report doors and shutters opening themselves, furniture moving without assistance, and piano and violin music from instruments that no longer work. Three ghostly apparitions have been spotted, along with the smell of flowers and candle lights moving through rooms. The upper window once contained a mysterious image of an enslaved woman - visible until UV coating obscured it in 2007.',
   1799, 'https://www.kentuckyhauntedhouses.com/real-haunt/white-hall.html'),

  ('camp-nelson', 'Camp Nelson National Monument', 'Nicholasville', '6614 Danville Road', 'KY', 37.7886, -84.5986, 'battlefield',
   'Established in 1863 as a Union Army supply depot, Camp Nelson became one of the largest recruitment and training centers for African American soldiers. It also served as a refugee camp for the families of enslaved men who joined the army.',
   'Park rangers have seen apparitions of an African American family in Civil War-era clothing who vanished before their eyes. The hardships faced by the refugee families - hunger, disease, and exposure - left spiritual imprints on the land. Visitors report unexplained phenomena connected to the site''s role in the struggle for freedom.',
   1863, 'https://maplehillmanor.com/blog/2025/03/haunted-places-in-kentucky/'),

  ('colville-covered-bridge', 'Colville Covered Bridge', 'Millersburg', 'Colville Road', 'KY', 38.2894, -84.1500, 'other',
   'Built in 1877 by Jacob Bower, this picturesque 124-foot covered bridge over Hinkston Creek is one of Kentucky''s few remaining historic covered bridges. Its rural setting and age have made it the subject of numerous ghost stories.',
   'Strange shadows are seen inside the bridge at night, and lights shine up through the floorboards as if from headlights submerged in the water below. Drivers report seeing phantom headlights in their rearview mirrors that vanish as if a ghostly car veered into the creek. The Bluegrass Ghost Chasers investigated and captured an unfamiliar laugh on their recorders. Urban legends speak of hangings and decapitations at the bridge.',
   1877, 'https://fox56news.com/news/spirit-of-bluegrass/ghost-stories-linked-to-kentucky-covered-bridge/');

-- ==========================================
-- NORTHERN KENTUCKY (~3 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('carneal-house', 'The Carneal House', 'Covington', '405 East Second Street', 'KY', 39.0833, -84.5086, 'mansion',
   'The oldest house in Covington, this 1815 mansion was built by Thomas Carneal, an early Kentucky land speculator and businessman. The elegant home witnessed nearly two centuries of Northern Kentucky history.',
   'The "Grey Lady" is Covington''s most famous ghost, haunting the Carneal House where a gruesome suicide occurred. Her apparition drifts through the rooms, appearing to visitors on ghost tours. Some say she is searching for something - or someone - she lost in life.',
   1815, 'https://linknky.com/uncategorized/2017/10/30/ghost-stories-historic-spots-covington-and-newport/'),

  ('shinkle-house', 'The Shinkle House', 'Covington', 'Garrard Street', 'KY', 39.0875, -84.5083, 'mansion',
   'This elegant Victorian mansion was home to Amos Shinkle, who built the iconic Roebling Suspension Bridge connecting Covington to Cincinnati. The house later served as a bed and breakfast in the 1980s and 1990s.',
   'Sarah Shinkle''s spirit never left her bedroom. Former owners Bernie Moorman and Don Nash operated a B&B there, and Nash once left Sarah''s room after perfecting the bedding, only to return moments later to find a distinct butt impression on the bed - as if someone invisible had sat down. The ghostly indentation appeared before his eyes.',
   1860, 'https://linknky.com/uncategorized/2017/10/30/ghost-stories-historic-spots-covington-and-newport/'),

  ('booth-memorial-hospital', 'Booth Memorial Hospital (Former)', 'Covington', 'Pike Street', 'KY', 39.0839, -84.5128, 'hospital',
   'This former Salvation Army hospital served the Covington community for decades before closing. The building''s long history of births, deaths, and medical care left supernatural residue.',
   'Local police responding to calls at the abandoned hospital had terrifying encounters with ghostly nurses still making their rounds. Residents near the site continue to report encounters with spectral medical staff. The spirits seem unaware they have passed, continuing their duties from beyond the grave.',
   1913, 'https://linknky.com/uncategorized/2017/10/30/ghost-stories-historic-spots-covington-and-newport/');

-- ==========================================
-- HARRODSBURG/DANVILLE AREA (~2 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('shaker-village-pleasant-hill', 'Shaker Village of Pleasant Hill', 'Harrodsburg', '3501 Lexington Road', 'KY', 37.8142, -84.7397, 'other',
   'The largest restored Shaker village in America encompasses 3,000 acres with 34 original buildings. The celibate religious community flourished here from 1805 until the last Shaker left in 1923.',
   'Ghostly babies are heard crying at night near the pond - according to dark legend, the Shakers drowned unwanted children there. A security guard saw a man in Shaker clothing walking the main street in the early morning hours, but when he investigated, no one was there. The Tanyard House is particularly haunted, with heavy boots walking through hallways and visitors experiencing severe physical reactions in the attic. Room 194 in the West building is notoriously haunted.',
   1805, 'https://www.kentuckyhauntedhouses.com/real-haunt/shaker-village-pleasant-hill.html'),

  ('old-fort-harrod', 'Old Fort Harrod State Park', 'Harrodsburg', '100 South College Street', 'KY', 37.7650, -84.8442, 'museum',
   'A reconstruction of the first permanent English settlement west of the Alleghenies, established by James Harrod in 1774. The fort represents the dangerous frontier life of Kentucky''s earliest pioneers.',
   'The spirits of pioneers who lived and died defending this frontier outpost are said to linger. Visitors report seeing figures in buckskin and feeling the presence of those who fought Native American raids and endured the harsh conditions of early Kentucky settlement. The replica fort seems to have absorbed the energy of those desperate times.',
   1774, 'https://www.kentuckyafterdark.com/locations/harrodsburg-ky');

-- ==========================================
-- ADDITIONAL NOTABLE LOCATIONS (~3 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url)
VALUES
  ('airdrie-iron-works', 'Airdrie Iron Works Ruins', 'Paradise', 'Green River Road', 'KY', 37.2717, -86.9992, 'other',
   'The crumbling remains of an 1855 iron foundry named after Airdrie, Scotland look like a deteriorating medieval castle on the banks of the Green River. Robert Alexander brought Scottish miners to work the furnace, but the operation failed after only three runs.',
   'Stories abound of convict laborers tortured in the coal and iron mines. On certain nights, the sounds of iron chains being dragged over stone steps echo through the ruins as the ghosts of prisoners relive their suffering. Some claim a prisoner was thrown into the furnace as an example to others, and his screams can still be heard. A headless woman searching for her head is also said to wander the site.',
   1855, 'https://www.kykinfolk.com/muhlenberg/local-history/airdrie_ghost.htm'),

  ('western-kentucky-university', 'Western Kentucky University', 'Bowling Green', 'Big Red Way', 'KY', 36.9863, -86.4558, 'university',
   'Founded in 1906, WKU sits on a hilltop known as "The Hill" above Bowling Green. The campus has such a reputation for hauntings that it was featured on Ghost Hunters and has its own official ghost stories page.',
   'A hermit with a blue lantern supposedly lives in the caverns running beneath campus and comes up into Van Meter Hall. The blue light is seen throughout the building. Potter Hall''s ghostly resident is a young woman who died there. The Colonnade was the site of a tragic death, and the spirit remains. McLean Hall has multiple ghosts. The "Hilltop History and Haunts Tour" explores the campus''s paranormal heritage.',
   1906, 'https://www.visitbgky.com/sp/halloween/'),

  ('maple-hill-manor', 'Maple Hill Manor Bed and Breakfast', 'Springfield', '2941 Perryville Road', 'KY', 37.7114, -85.1917, 'hotel',
   'This stunning 1851 Greek Revival plantation house is now an award-winning bed and breakfast. The antebellum mansion witnessed the Civil War and has retained its historic charm - along with several resident spirits.',
   'Guests report paranormal activity throughout the manor, including footsteps in empty hallways, doors opening and closing, and the feeling of unseen presences. The spirits seem friendly, adding to the historic atmosphere rather than frightening visitors. The manor''s role during the Civil War may account for some of the supernatural activity.',
   1851, 'https://maplehillmanor.com/blog/2025/03/haunted-places-in-kentucky/');
