-- Seed data for tour_operators table - Batch 2
-- Generated by researcher agent on 2026-01-22
--
-- Coverage: Next tier of haunted destinations (10 cities)
-- 1. Boston, MA (6 operators)
-- 2. Philadelphia, PA (6 operators)
-- 3. San Francisco, CA (5 operators)
-- 4. San Diego, CA (5 operators)
-- 5. Los Angeles, CA (5 operators)
-- 6. Williamsburg, VA (5 operators)
-- 7. Richmond, VA (5 operators)
-- 8. Baltimore, MD (5 operators)
-- 9. New Haven, CT (4 operators)
-- 10. Memphis, TN (4 operators)
--
-- Total: 50 tour operators

-- =====================================================
-- BOSTON, MA - Freedom Trail, Colonial history, Omni Parker House
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Boston Ghosts', 'Boston', 'MA',
   'https://bostonghosts.com/',
   'https://bostonghosts.com/boston-ghost-tour/',
   'Part of US Ghost Adventures network offering authentic ghost tours detailing the tragic, mysterious, and haunted past of Massachusetts historic capital. Tours explore Boston Common, Granary Burying Ground, and the Founding Fathers legacy. Also offers Blazing the Freedom Trail Tour covering the Boston Massacre and Sons of Liberty.',
   '$25-35', 'walking, history, Freedom Trail, pub crawl', TRUE),

  ('Haunted Boston Ghost Tours', 'Boston', 'MA',
   'https://www.tripadvisor.com/Attraction_Review-g60745-d1770868-Reviews-Haunted_Boston_Ghost_Tours-Boston_Massachusetts.html',
   'https://www.tripadvisor.com/Attraction_Review-g60745-d1770868-Reviews-Haunted_Boston_Ghost_Tours-Boston_Massachusetts.html',
   'The oldest established ghost walking tour in Boston, founded in 2005. Spellbinding storytelling by lantern-light through nearly two decades of sharing Bostons dark, otherworldly, yet true history. Tours meet weeknights at 8pm at the Central Burying Ground in Boston Commons.',
   '$20-30', 'walking, lantern, history', TRUE),

  ('Freedom Trail Foundation Lantern Tour', 'Boston', 'MA',
   'https://www.thefreedomtrail.org/tours/lantern',
   'https://www.thefreedomtrail.org/tours/lantern',
   'Official Freedom Trail experience uncovering the grim, macabre history and mystery of the trail. Led by darkly cloaked Freedom Trail Players sharing true accounts of grave robbing, cold-blooded killings, fatal sword duels, pirate graves, scandalous murders, and witch hangings. Recommended for ages 12 and up.',
   '$20-30', 'walking, lantern, history, official', TRUE),

  ('Nightly Spirits', 'Boston', 'MA',
   'https://nightlyspirits.com/boston-ghost-tours/',
   'https://nightlyspirits.com/boston/boston-booze-and-boos-tour/',
   'Boston Booze and Boos Tour begins at Last Hurrah inside the Omni Parker House, Americas most haunted hotel. Two and a half hour journey through the city visiting 3-4 haunted bars. Purchase of alcohol not included or required. All guests must be 21+.',
   '$28-35', 'pub crawl, walking', FALSE),

  ('Ghost City Tours', 'Boston', 'MA',
   'https://ghostcitytours.com/ghost-tours/boston-ghost-tours/',
   'https://ghostcitytours.com/ghost-tours/boston-ghost-tours/',
   'Haunted Pub Crawl chasing the spirits of our Founding Fathers while exploring Bostons most historic and haunted bars. Must be 21+ to join. 15% group discount for 12 or more. Features storytelling-first haunted experiences.',
   '$25-35', 'pub crawl, walking, history', FALSE),

  ('Dark Side of Boston Ghost Tour', 'Boston', 'MA',
   'https://freetoursbyfoot.com/boston-ghost-tour/',
   'https://freetoursbyfoot.com/boston-ghost-tour/',
   'Journey through the long-feared sinister underbelly of Boston, from one of the citys oldest cemeteries to sites connected to Edgar Allan Poe to a famed haunted hotel. Stops include Central Burial Ground, Boston Common history from public hangings to Revolutionary War gatherings.',
   '$15-25', 'walking, history, pay-what-you-wish', FALSE);

-- =====================================================
-- PHILADELPHIA, PA - Eastern State Penitentiary, Independence Hall
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghost City Tours', 'Philadelphia', 'PA',
   'https://ghostcitytours.com/philadelphia/',
   'https://book.peek.com/s/9715797d-9695-489a-815f-991918aff13b/Nx8Jk',
   'Award-winning ghost tours exploring Philadelphias haunted history. The Founding Phantoms Ghost Tour is adults-only (16+) with a near-perfect 4.9-star rating from 98,000+ tours. Operating since 2012 with storytelling-first haunted experiences at Independence Mall.',
   '$29.99-34.99', 'walking, adults-only, history', TRUE),

  ('Grim Philly Twilight Tours', 'Philadelphia', 'PA',
   'https://www.grimphilly.com/',
   'https://www.grimphilly.com/ghosts',
   'R-rated, uncensored night tours led by college professors and published authors. Nine tours covering ghosts, sex, vampire lore, serial killers, gangsters, prohibition, pirates, and the Jersey Devil. TripAdvisor Travelers Choice BEST of the BEST Award given to less than 1% of activities worldwide.',
   '$25-40', 'walking, adults-only, history, boat', TRUE),

  ('Spirits of 76 Ghost Tours', 'Philadelphia', 'PA',
   'https://www.spiritsof76.com/',
   'https://www.spiritsof76.com/',
   'One Part History, Two Parts Haunt! 75-minute outdoor walking adventure visiting 20+ scary sites. Experience monuments by moonlight and cobblestone streets of Old City. See film locations from The Sixth Sense and National Treasure. Established 2007 by The Constitutional Walking Tour.',
   '$20-30', 'walking, history, family', TRUE),

  ('Philly Ghosts', 'Philadelphia', 'PA',
   'https://phillyghosts.com/',
   'https://phillyghosts.com/',
   'Experience the haunted side of the City of Brotherly Love with Philadelphias ghostly revolution and restless souls from Americas founding history. Featured in USA Today, Huffington Post, and Sirius. Offers ghost tours, haunted pub crawls, and Rockstars of the Revolution tours.',
   '$25-35', 'walking, pub crawl, history', FALSE),

  ('Ghost Tour of Philadelphia', 'Philadelphia', 'PA',
   'https://www.ghosttour.com/',
   'https://www.ghosttour.com/',
   'Professional ghost tours in Philadelphia, Lancaster, and Douglassville PA. Explore haunted locations including Eastern State Penitentiary area and historic Old City. One of the original ghost tour companies in the Philadelphia region.',
   '$20-30', 'walking, history', FALSE),

  ('Eastern State Penitentiary', 'Philadelphia', 'PA',
   'https://easternstate.org/',
   'https://easternstate.org/events',
   'Self-guided and special event tours of one of Americas most notorious prisons and considered the most haunted site in Pennsylvania. Featured on Ghost Hunters and Most Haunted. Wednesday evening events May-July with immersive experiences and behind-the-scenes access. Halloween Nights September-November.',
   '$17-55', 'audio tour, investigation, Halloween', FALSE);

-- =====================================================
-- SAN FRANCISCO, CA - Alcatraz, Chinatown, Victorian mansions
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('San Francisco Ghost Hunt Walking Tour', 'San Francisco', 'CA',
   'https://www.sfghosthunt.com/',
   'https://www.sfghosthunt.com/',
   'The first and original San Francisco Ghost Hunt since 1998. Four-time Best of the Bay Winner. Lantern-lit stroll through Pacific Heights, one of the few neighborhoods to survive the 1906 Earthquake. 90-minute tour exploring haunted Victorian mansions including Chambers Mansion poltergeists.',
   '$25-35', 'walking, lantern, Victorian', TRUE),

  ('SF Ghosts', 'San Francisco', 'CA',
   'https://sfghosts.com/',
   'https://sfghosts.com/',
   'Part of US Ghost Adventures network exploring spirits lost to fire, madness, and murder. Features phantoms of Chinatown and the doomed of Nob Hill. Offers San Francisco Ghost Tour, Gold Rush history tour, Haunted Pub Crawl, and food tours with knowledgeable, interactive guides.',
   '$25-35', 'walking, pub crawl, Chinatown', TRUE),

  ('The Haunt Ghost Tours', 'San Francisco', 'CA',
   'https://thehauntghosttours.com/tours/san-francisco/',
   'https://thehauntghosttours.com/tours/san-francisco/',
   'Top-rated ghost tours led by real paranormal investigators with exclusive access to the San Remo Hotel for after-dark ghost hunting. Enjoy a haunted cocktail, hear true crime tales, and explore eerie corridors using modern ghost hunting tools including EMF meters.',
   '$35-55', 'walking, investigation, equipment', TRUE),

  ('Haunted Haight Walking Tour', 'San Francisco', 'CA',
   'https://www.tripadvisor.com/Attractions-g60713-Activities-c42-t226-San_Francisco_California.html',
   'https://www.viator.com/San-Francisco-tours/Ghost-and-Vampire-Tours/d651-g4-c118',
   'Supernatural occurrences and mysterious events in SFs Haight Ashbury District. A paranormal investigator shows you how to use ghost hunting gear. Walk past locations where infamous murderers and cult leaders used to live. Tour starts at 7pm, mostly on Fridays.',
   '$30-40', 'walking, investigation, Haight-Ashbury', FALSE),

  ('Alcatraz Night Tour', 'San Francisco', 'CA',
   'https://www.cityexperiences.com/san-francisco/city-cruises/alcatraz/',
   'https://alcatrazticketing.com/alcatraz-night-tours/',
   'Official Alcatraz Night Tours Tuesday-Saturday lasting 2.5 hours. Includes round-trip ferry, award-winning Cellhouse audio tour, and guided docent talks to areas not available during the day including A Block and second floor cells. Cell Block D long rumored to be haunted.',
   '$33-55', 'ferry, audio tour, prison, night tour', FALSE);

-- =====================================================
-- SAN DIEGO, CA - Whaley House, Old Town, Gaslamp Quarter
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Whaley House Museum', 'San Diego', 'CA',
   'https://www.whaleyhousesandiego.com/',
   'https://www.whaleyhousesandiego.com/tickets/',
   'Americas Most Haunted House per Travel Channel, sitting on the original Old Town gallows site. Daytime museum tours plus Haunted Evening Tours (30-40 minutes, PG-13) and exclusive after-hours Paranormal Investigations with access to rooms where the Whaleys lived and died. Featured on Ghost Adventures and Ghost Files.',
   '$25-85', 'museum, evening tour, investigation', TRUE),

  ('Haunted San Diego Tours', 'San Diego', 'CA',
   'https://hauntedsandiegotours.com/',
   'https://checkout.xola.app/#buttons/616719e51e02cb5ba34ccd76',
   '#1 rated local ghost tour since 2006. The only tour that goes INSIDE multiple documented haunted locations with exclusive after-dark access to Villa Montezuma, Horton Grand Hotel, Davis-Horton House, and El Campo Santo Cemetery. Custom coffin-decorated bus and intimate group sizes.',
   '$35-75', 'bus, walking, investigation, exclusive access', TRUE),

  ('Ghosts and Gravestones San Diego', 'San Diego', 'CA',
   'https://www.ghostsandgravestones.com/san-diego',
   'https://www.trolleytours.com/san-diego/ghosts-gravestones-tickets',
   'Board the Trolley of the Doomed to the Whaley House Courtyard, then walk through El Campo Santo Cemetery and Pioneer Park. Learn about gunslingers, gamblers, and ladies of the night. 90-minute tour, PG-13 rated. Boards at Old Town Market.',
   '$30-42', 'trolley, cemetery, Old Town', TRUE),

  ('Old Town Haunted Ghost Tour', 'San Diego', 'CA',
   'https://hauntedsdoldtowntours.com/',
   'https://hauntedsdoldtowntours.com/',
   'The Original Old Town Haunted Ghost Tour with exclusive permission to enter Heritage Park after the gates are locked. Explores the infamous Whaley House Grounds with tragic and terrifying true stories that made this location a nexus for paranormal activity.',
   '$25-35', 'walking, Old Town, Heritage Park', FALSE),

  ('San Diego Ghost Tours', 'San Diego', 'CA',
   'https://www.sandiegoghosttours.com/',
   'https://www.sandiegoghosttours.com/',
   'Established ghost tour company exploring Old Town San Diego after dark with stories of Yankees, pirates, and California history. Learn about Yankee Jim Robinson executed on the Whaley House grounds in 1852 and other spirits who never left.',
   '$25-35', 'walking, Old Town, history', FALSE);

-- =====================================================
-- LOS ANGELES, CA - Hollywood haunts, Cecil Hotel
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('LA Ghosts', 'Los Angeles', 'CA',
   'https://laghosttour.com/',
   'https://laghosttour.com/',
   'Part of US Ghost Adventures exploring haunted Hollywood where dreams die, spirits linger, and LAs dark past lives on. Features murder, mayhem, and Marilyn Monroe at the Roosevelt Hotel. Also offers Ultimate Dead of Night Ghost Tour, Haunted Pub Crawl, and Celebrities Underground Tour.',
   '$25-45', 'walking, pub crawl, Hollywood', TRUE),

  ('American Ghost Walks - LA Hauntings', 'Los Angeles', 'CA',
   'https://www.americanghostwalks.com/tour/los-angeles-hauntings-ghost-bus-tour',
   'https://www.americanghostwalks.com/tour/los-angeles-hauntings-ghost-bus-tour',
   'The only bus tour in LA specializing in haunted tales and paranormal experiences. 3-hour fully narrated tour covering Hollywood Forever Cemetery, LA City Hall, the Cecil Hotel, Charlie Chaplin Studios. Stories of Richard Ramirez, Hillside Strangler, and Black Dahlia. Meets at The Formosa Cafe.',
   '$64-75', 'bus, Hollywood, downtown', TRUE),

  ('The Real Los Angeles Tours - DTLA Murder Mystery', 'Los Angeles', 'CA',
   'https://www.thereallosangelestours.com/tours/dtla-murder-mystery-ghost-tour/',
   'https://www.viator.com/tours/Los-Angeles/DTLA-Murder-Mystery-Ghost-Tour/d645-122204P4',
   'Investigate the seedy underbelly of downtown LAs past visiting the infamous Hotel Cecil where the Night Stalker stayed and the Barclay Hotel. Also covers Black Dahlia and Manson murders with stops at haunted bars for cocktails.',
   '$35-50', 'walking, downtown, true crime, pub', TRUE),

  ('Haunted Hollywood Walking Tour', 'Los Angeles', 'CA',
   'https://www.americanghostwalks.com/tour/hollywood-ghost-walk',
   'https://www.americanghostwalks.com/tour/hollywood-ghost-walk',
   'Walk the star-studded streets of Hollywood after dark learning about celebrity ghosts and tragic deaths. Visit the Roosevelt Hotel where Marilyn Monroe and Montgomery Clift haunt the halls. Stories of the Pantages Theatre, Knickerbocker Hotel, and more.',
   '$35-45', 'walking, Hollywood, celebrity ghosts', FALSE),

  ('The Haunt Ghost Tours - LA', 'Los Angeles', 'CA',
   'https://thehauntghosttours.com/',
   'https://thehauntghosttours.com/',
   'Top-rated ghost tours led by real paranormal investigators with hands-on ghost hunting using authentic equipment. Explore LAs most mysterious locations and dark history with true crime tales and expert paranormal guidance.',
   '$35-55', 'walking, investigation, equipment', FALSE);

-- =====================================================
-- WILLIAMSBURG, VA - Colonial ghosts, Revolutionary War
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Colonial Ghosts', 'Williamsburg', 'VA',
   'https://colonialghosts.com/',
   'https://colonialghosts.com/',
   'Top 10 Ghost Tours in the US, recognized by Huffington Post and Southern Living Magazine. Best of Williamsburg Tour Operator. Up to 18 ghost stories on location, more than any other tour. Fact-checked and verified stories through Colonial Williamsburg and College of William and Mary. EMF detectors available for rent.',
   '$26-74', 'walking, history, equipment rental', TRUE),

  ('Haunted Williamsburg', 'Williamsburg', 'VA',
   'https://www.colonialwilliamsburg.org/events/evening-program-haunted-williamsburg/',
   'https://www.colonialwilliamsburg.org/events/evening-program-haunted-williamsburg/',
   'Official ghost tour experience of Colonial Williamsburg. One-hour candlelit walking tour beginning at the Courthouse. Explore the haunted history of Americas largest living history museum with costumed interpreters sharing colonial-era ghost stories.',
   '$20-30', 'walking, candlelit, official', TRUE),

  ('Spooks and Legends Haunted Tours', 'Williamsburg', 'VA',
   'https://www.spooksandlegends.com/',
   'https://www.spooksandlegends.com/',
   'Williamsburgs favorite tour since 2010. Dead of Night Tour is a two-hour ghost hunt with real paranormal gear including PSB7 Spirit Box, EMF Meters, Dowsing Rods, and Rem Pods. Explore hotspots like Peyton Randolph House and Public Gaol. Children 6 and under FREE.',
   '$20-45', 'walking, ghost hunt, equipment', TRUE),

  ('The Original Ghost Tour of Williamsburg', 'Williamsburg', 'VA',
   'https://theghosttour.com/',
   'https://theghosttour.com/',
   'Virginias Oldest Ghost Tour exploring cobblestone streets and shadowy alleyways with knowledgeable guides sharing chilling tales of colonial spirits and mysterious occurrences. Walking tours through historic Williamsburg after dark.',
   '$20-30', 'walking, history, colonial', FALSE),

  ('Williamsburg Ghost Tour', 'Williamsburg', 'VA',
   'https://williamsburgghosttour.com/',
   'https://www.viator.com/tours/Williamsburg/The-Original-Ghost-of-Williamsburg/d33617-140722P3',
   'Candlelit guided ghost tour exploring lesser-known haunted side of the historic streets. Visit parts of the town most tourists would not be comfortable visiting and hear about the Battle of Williamsburg where 70,000 soldiers clashed in 1862.',
   '$25-35', 'walking, candlelit, Civil War', FALSE);

-- =====================================================
-- RICHMOND, VA - Civil War history, Hollywood Cemetery
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Richmond Ghosts', 'Richmond', 'VA',
   'https://rvaghosts.com/',
   'https://rvaghosts.com/all-tours/',
   'Richmond Ghost Tours where Civil War spirits still roam. Offers Sinister Secrets of Shockoe Bottom, Hollywood Cemetery Tour, and Haunted Pub Crawl. Explore haunted buildings, tunnels, and grounds from Americas bloodiest conflict. Booking direct saves $5/person.',
   '$25-35', 'walking, cemetery, pub crawl, Civil War', TRUE),

  ('Haunts of Richmond', 'Richmond', 'VA',
   'https://www.hauntsofrichmond.com/',
   'https://www.hauntsofrichmond.com/',
   'The Original Richmond Ghost Tour Company since 2004. Professional guides for haunted walks through six of Richmonds most historic neighborhoods. Church Hill Chillers tour includes spirit spymaster Elizabeth Van Lew, Edgar Allan Poes first and last love, and Civil War hospital haunts.',
   '$27-30', 'walking, Church Hill, history', TRUE),

  ('US Ghost Adventures - Richmond', 'Richmond', 'VA',
   'https://usghostadventures.com/richmond-ghost-tour/',
   'https://usghostadventures.com/richmond-ghost-tour/',
   'Explore Richmonds haunted past from the Civil War to the legend of the Richmond Vampire. Tours visit Hollywood Cemetery where Jefferson Davis rests and the infamous Church Hill Tunnel where a blood-covered creature emerged from the 1925 collapse.',
   '$25-35', 'walking, cemetery, Civil War', TRUE),

  ('Shadows of Shockoe Ghost Tour', 'Richmond', 'VA',
   'https://www.viator.com/tours/Richmond/Shadows-of-Shockoe-Ghost-Tour/d23016-72104P1',
   'https://www.viator.com/tours/Richmond/Shadows-of-Shockoe-Ghost-Tour/d23016-72104P1',
   '90-minute walking tour through Richmonds Shockoe Bottom exploring some of Americas oldest and most haunted buildings. Visit 8-12 locations with educated local guides sharing tales of restless spirits from centuries of history.',
   '$25-30', 'walking, Shockoe Bottom', FALSE),

  ('Lizzie Borden Ghost Tours - Richmond', 'Richmond', 'VA',
   'https://lizzie-borden.com/ghost-tours/richmond/',
   'https://lizzie-borden.com/ghost-tours/richmond/',
   'Explore Richmonds haunted Civil War history where wounded soldiers hospital buildings still harbor restless spirits. Part of the Lizzie Borden national ghost tour network offering experiences in over 100 American cities.',
   '$25-35', 'walking, Civil War, history', FALSE);

-- =====================================================
-- BALTIMORE, MD - Poes grave, Fells Point
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Baltimore Ghost Tours', 'Baltimore', 'MD',
   'https://baltimoreghosttours.com/',
   'https://fareharbor.com/embeds/book/baltimorewickedhistorytour/',
   'The Original and Top Rated ghost tours since 2001. Locally owned with professional local actors as guides. Original Fells Point GhostWalk and Mt Vernon GhostWalk (all ages), plus 21+ Haunted Pub Tours. Published book on Baltimore ghost stories. Friday and Saturday nights March-December.',
   '$20-29', 'walking, pub crawl, history', TRUE),

  ('Baltimore Ghosts', 'Baltimore', 'MD',
   'https://tourbaltimoreghosts.com/',
   'https://tourbaltimoreghosts.com/',
   'Part of US Ghost Adventures unlocking haunted secrets of Fells Point where sailors drank, died, and never left. Stand in the gaze of Edgar Allan Poes ghost and visit the Horse You Came In On Saloon, the oldest continually operating saloon in the US and Poes final stop.',
   '$25-35', 'walking, Fells Point, Poe', TRUE),

  ('Fells Point Wicked History Pub Tour', 'Baltimore', 'MD',
   'https://baltimoreghosttours.com/fellspointghosttour/',
   'https://www.viator.com/tours/Baltimore/The-Fells-Point-Wicked-History-Walking-Tour/d4375-75466P2',
   'Explore the wicked history of Fells Point, one of the oldest ports in the country. Visit Maxs Taphouse (former slaughterhouse and brothel), the Admiral Fell Inn with phantom butlers, and haunted saloons. 21+ only.',
   '$29-35', 'pub crawl, history, 21+', TRUE),

  ('Baltimore Bewitched Ghost Tour', 'Baltimore', 'MD',
   'https://www.viator.com/tours/Baltimore/Baltimore-Haunted-Walking-Ghost-Tour/d4375-272083P1',
   'https://www.viator.com/tours/Baltimore/Baltimore-Haunted-Walking-Ghost-Tour/d4375-272083P1',
   'Raven Bones and Ballads Ghost Tour exploring Edgar Allan Poes Baltimore. Visit Westminster Hall where Poe is buried and locations connected to his mysterious death. Learn about the Poe Toaster tradition and the gothic authors haunted legacy.',
   '$30-40', 'walking, Poe, history', FALSE),

  ('Lizzie Borden Ghost Tours - Baltimore', 'Baltimore', 'MD',
   'https://lizzie-borden.com/ghost-tours/baltimore/',
   'https://lizzie-borden.com/ghost-tours/baltimore/',
   'Explore Baltimores haunted waterfront and the mystery of Edgar Allan Poes final days. Many believe his spirit still wanders between Fells Point bars and his former home. Part of the national Lizzie Borden ghost tour network.',
   '$25-35', 'walking, Poe, Fells Point', FALSE);

-- =====================================================
-- NEW HAVEN, CT - Yale campus, colonial history
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Ghosts of New Haven', 'New Haven', 'CT',
   'https://ghostsofnewhaven.com/',
   'https://fareharbor.com/embeds/book/ghostsofnewhaven/items/calendar/',
   'New Havens longest-running ghost tour company. Night walks through spookiest sites including Skull and Bones Society, New Haven City Hall, Public Library, the Green, and Grove Street Cemetery. Featured in NBC Universal and New York Times. Five-star TripAdvisor ratings.',
   '$20-25', 'walking, Yale, history', TRUE),

  ('US Ghost Adventures - New Haven', 'New Haven', 'CT',
   'https://usghostadventures.com/new-haven-ghost-tour/',
   'https://usghostadventures.com/new-haven-ghost-tour/',
   'Venture into Elm Citys sordid history to uncover unexplained phenomena. 1-hour tours across 1-mile including bonus extended tour option. Explore Yales haunted campus with gothic architecture and phantom events like sudden temperature drops.',
   '$25-35', 'walking, Yale, paranormal', TRUE),

  ('New Haven Haunted Pub Crawl', 'New Haven', 'CT',
   'https://ghostsofnewhaven.com/',
   'https://ghostsofnewhaven.com/',
   'Two-hour ghost pub crawl with tales of the city, legends of the Flying Dutchman, and truth behind the Skull and Bones Society. Visit at least three pubs while passing haunted landmarks like Grove Street Cemetery. 21+ only.',
   '$30-40', 'pub crawl, Yale, 21+', TRUE),

  ('Ghosts of New England - New Haven', 'New Haven', 'CT',
   'https://www.ghostsofnewengland.com/ghosts-of-new-haven-ct-haunted-tours/',
   'https://www.ghostsofnewengland.com/ghosts-of-new-haven-ct-haunted-tours/',
   'Part of the Ghosts of New England network exploring Connecticuts most haunted city. Walking tours through downtown and Yale campus sharing colonial-era ghost stories and the dark history of one of Americas oldest settlements.',
   '$20-30', 'walking, Yale, colonial', FALSE);

-- =====================================================
-- MEMPHIS, TN - Orpheum Theatre, Beale Street, Elvis history
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Backbeat Tours', 'Memphis', 'TN',
   'https://www.backbeattours.com/tours/memphis-ghost-tour/',
   'https://fareharbor.com/embeds/book/backbeattours/',
   'Memphis Ghost Tours offering 90-minute walking experience through South Main Historic District. Visit the Orpheum Theater home of ghost Mary in seat C5, John Alexander Austin House haunted by star-crossed lovers, and Ernestine and Hazels former brothel with haunted jukebox. Check in at 197 Beale Street.',
   '$27-35', 'walking, Beale Street, theater', TRUE),

  ('US Ghost Adventures - Memphis', 'Memphis', 'TN',
   'https://usghostadventures.com/memphis-ghost-tour/',
   'https://usghostadventures.com/memphis-ghost-tour/',
   '#1 rated ghost tour in Memphis. Tours meet at the Lorraine Motel exploring Memphiss darker history of vice, voodoo, phantoms, and lost souls. 1-hour tours across 1 mile with bonus extended tour option to additional haunted locations.',
   '$25-35', 'walking, Beale Street, history', TRUE),

  ('Lizzie Borden Ghost Tours - Memphis', 'Memphis', 'TN',
   'https://lizzie-borden.com/ghost-tours/memphis/',
   'https://lizzie-borden.com/ghost-tours/memphis/',
   'Explore Memphiss haunted history including the Lorraine Motel, the nationally known Peabody Hotel with spirits on the 11th floor, and locations connected to the citys dark past. Part of the Lizzie Borden national ghost tour network.',
   '$25-35', 'walking, history', TRUE),

  ('Memphis True Crime Tour', 'Memphis', 'TN',
   'https://www.backbeattours.com/',
   'https://www.backbeattours.com/',
   'Backbeat Tours true crime experience exploring Memphiss dark underbelly. Stories of murder, mayhem, and mystery from the blues city. Combined with musical heritage storytelling from professional guides who are musicians themselves.',
   '$27-35', 'walking, true crime, music history', FALSE);
