-- Seed data for Maryland haunted places (batch 2)
-- Generated by researcher agent on 2026-01-23
-- Adds 16 new places to bring MD from 24 to 40

-- ==========================================
-- ELLICOTT CITY AREA (~4 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url, sources, source_count)
VALUES
  ('lilburn-mansion', 'Lilburn Mansion', 'Ellicott City', '4744 Montgomery Road', 'MD', 39.2673, -76.7943, 'mansion',
   'A striking Gothic Revival mansion built in 1857 by iron magnate Henry Richard Hazelhurst, Lilburn is considered the most haunted residence in Ellicott City.',
   'Henry Richard Hazelhurst built Lilburn in 1857 and made a fortune in the iron trade during the Civil War. Tragedy struck repeatedly as he lost his wife and several children — one daughter reportedly died in childbirth inside the mansion. Hazelhurst outlived most of his family, dying in 1900 at age 85. After a Christmas fire in 1923, the gothic tower''s peaked spires were replaced with stone battlements, and paranormal activity intensified. Housekeepers have seen the apparition of a young girl in a chiffon dress playing in various rooms, and the same entity has been observed walking down a hallway accompanied by a male figure. The heavy dining room chandelier began swinging violently during a 1960 family event with no explanation. Cigar smoke drifts through the library when no one is smoking, sealed windows open by themselves, and a child''s crying emanates from an upstairs bedroom — one family''s dog refused to enter the second-floor room.',
   1857, 'https://www.hauntedrooms.com/maryland/haunted-places/haunted-hotels/wayside-inn',
   '["https://dorseyfamilyhomes.com/blog/haunted-ellicott-city/","https://www.hauntworld.com/real-haunted-house-in-ellicott-city-maryland-the-ghost-of-lilburn--in-ellicott-maryland","https://midatlanticdaytrips.com/2022/09/walk-the-mile-with-the-most-ghosts-in-haunted-ellicott-city/"]', 3),

  ('patapsco-female-institute', 'Patapsco Female Institute', 'Ellicott City', '3655 Church Road', 'MD', 39.2694, -76.7978, 'other',
   'The haunted ruins of a 19th-century girls'' boarding school, now a historic park where ghostly apparitions of students in white gowns are regularly reported.',
   'Built in the 1830s by architect Charles Timus, the Patapsco Female Institute was a prestigious boarding school for girls aged 12 to 18. Several students reportedly died of pneumonia during harsh Maryland winters, and their spirits are said to still wander the grounds. Visitors have claimed to see apparitions of schoolgirls wearing long white gowns drifting through the ruins. One visitor, separated from her group, watched a young woman in a long gown walk out of the front doors, down the stone steps, and across the lawn before abruptly vanishing. Another witness saw what appeared to be a workman on top of the building — when she pointed him out, her companion saw nothing, and the figure had disappeared. The ghost known as Annie is the most frequently sighted, and the ruins are a popular stop on Ellicott City ghost tours.',
   1837, 'https://www.onlyinyourstate.com/experiences/maryland/haunted-town-md',
   '["https://www.onlyinyourstate.com/experiences/maryland/haunted-town-md","https://stephanieverni.com/2011/11/14/ellicott-city-steeped-in-ghost-lore/","http://ellicottcity.life/2018/01/15/top-4-most-haunted-ellicott-city/"]', 3),

  ('mt-ida-mansion', 'Mt. Ida', 'Ellicott City', '3691 Sarah''s Creek Drive', 'MD', 39.2688, -76.7972, 'mansion',
   'An 1828 mansion built for William Ellicott''s grandson, now the visitor center for Patapsco Female Institute Historic Park, haunted by the ghost of Miss Ida Tyson.',
   'Mt. Ida was built in 1828 for William Ellicott, grandson of the town''s co-founder Andrew Ellicott, and designed by architect Charles Timus. During the 1850s, Judge John Snowden Tyson and his family moved in, naming the mansion after his daughter Ida Tyson. Miss Ida lived in the house until she was 90 years old in the 1920s, and was known for keeping a ring of keys with her at all times. After her death, visitors and staff began hearing the distinctive jingling of keys as her ghost walks through the house. The phantom sounds are most commonly reported in the hallways and on the staircase. Miss Ida''s spirit is described as protective rather than menacing — a ''cleaning ghost'' who watches over her beloved home.',
   1828, 'https://midatlanticdaytrips.com/2022/09/walk-the-mile-with-the-most-ghosts-in-haunted-ellicott-city/',
   '["https://midatlanticdaytrips.com/2022/09/walk-the-mile-with-the-most-ghosts-in-haunted-ellicott-city/","https://stephanieverni.com/2011/11/14/ellicott-city-steeped-in-ghost-lore/"]', 2),

  ('wayside-inn-ellicott-city', 'The Wayside Inn', 'Ellicott City', '4344 Columbia Road', 'MD', 39.2635, -76.8027, 'hotel',
   'A Revolutionary War-era inn built around 1780, reportedly visited by George Washington and haunted by a woman whose perfume lingers in the hallways.',
   'The Wayside Inn was originally built around 1780 as a farmhouse on a profitable Ellicott City tobacco plantation. Local lore says the house harbored famous Revolutionary fighters passing through, including George Washington and John Quincy Adams. The farmhouse became an inn and public house in the early 1800s, and during the Civil War it may have provided rooms for Union soldiers garrisoned in town due to Ellicott City''s strategic railroad location. Guests and staff report the ghost of a woman who makes her presence known through disembodied footsteps, doors opening by themselves, and the scent of a woman''s perfume drifting through hallways when no one is present. One witness heard a door open followed by approaching footsteps, but found no one there. Known locally as "that house with the candles in the windows," many myths surround the famous candles, including the belief they signal the house is haunted.',
   1780, 'https://www.hauntedrooms.com/maryland/haunted-places/haunted-hotels/wayside-inn',
   '["https://www.hauntedrooms.com/maryland/haunted-places/haunted-hotels/wayside-inn","https://waysideinnmd.com/blog/haunted-ellicott-city/","https://www.marylandhauntedhouses.com/real-haunt/wayside-inn.html"]', 3),

-- ==========================================
-- WESTERN MARYLAND (~2 locations)
-- ==========================================

  ('jonathan-hager-house', 'Jonathan Hager House', 'Hagerstown', '110 Key Street', 'MD', 39.6375, -77.7257, 'museum',
   'The 1739 limestone homestead of Hagerstown''s founder, named by Forbes as Maryland''s most haunted place, with at least 13 documented deaths within its walls.',
   'Jonathan Hager built this limestone homestead in 1739 as a combination residence, trading post, and frontier fort in western Maryland. The house has nearly 2-foot-thick stone walls and two natural springs running through its cellar. At least 13 people are known to have died in the house over its 280+ year history. Since becoming a museum in 1962, visitors and staff have reported extensive paranormal activity: a cradle rocks on its own, a corn doll moves about the house unaided, a rocking chair moves without human aid, and temperatures rise and fall inexplicably. The Downin children''s spirits are blamed for cameras malfunctioning in the residence. A lady in green has been seen looking out the window or as a flash of green dress in the hall. A man in black is spotted around the house and elsewhere in City Park, sometimes sitting on the porch smoking a pipe. The city offers hour-long ghost tours that sell out annually.',
   1739, 'https://radiofreehubcity.com/2024/10/09/hager-house-one-of-marylands-most-haunted-places/',
   '["https://radiofreehubcity.com/2024/10/09/hager-house-one-of-marylands-most-haunted-places/","https://www.marylandhauntedhouses.com/real-haunt/johnathan-hager-house-museum.html","https://www.hagerstownmd.org/1129/Ghost-Tour"]', 3),

  ('millers-church', 'Miller''s Church', 'Hagerstown', 'Spielman Road', 'MD', 39.5917, -77.7483, 'cemetery',
   'A remote 19th-century church and cemetery in Washington County known for unexplained car trouble and paranormal encounters on the surrounding road.',
   'Miller''s Church sits on a lonely stretch of Spielman Road outside Hagerstown, surrounded by farmland and woods. The small church and its adjacent cemetery date to the 1800s and have long been the subject of local ghost stories. Visitors report their cars stalling or experiencing electrical problems when passing the church at night. Some have reported seeing figures moving among the gravestones after dark, and others describe an oppressive feeling of being watched when approaching the property. The most common account involves car headlights dimming or flickering near the cemetery entrance, returning to normal only after passing the church grounds. Local teenagers have long considered it a dare to visit after midnight.',
   1850, 'https://www.marylandhauntedhouses.com/real-haunt/millers-church.html',
   '["https://www.marylandhauntedhouses.com/real-haunt/millers-church.html","https://www.hagerstownmd.org/1129/Ghost-Tour"]', 2),

-- ==========================================
-- CENTRAL MARYLAND / DC SUBURBS (~3 locations)
-- ==========================================

  ('surratt-house-museum', 'Surratt House Museum', 'Clinton', '9110 Brandywine Road', 'MD', 38.7544, -76.8983, 'museum',
   'The 1852 home of Mary Surratt, the first woman executed by the US government, and a stop on John Wilkes Booth''s escape route after Lincoln''s assassination.',
   'John and Mary Surratt built this house in 1852, and it served as a tavern, post office, and polling place. The area was named Surrattsville in 1853. During the Civil War, the house became entangled in the plot to kidnap President Lincoln — weapons and supplies were hidden here. After shooting Lincoln at Ford''s Theatre on April 14, 1865, Booth''s first stop on his escape was the Surratt house to retrieve the hidden carbines. Mary Surratt was convicted of conspiracy and became the first woman executed by the US government. Museum director Laurie Verge, a self-described skeptic, admits she cannot explain the footsteps heard by multiple employees — on one occasion, five or six staff members all stopped talking and heard someone walk in the front door, down the hall, and out the back, but found no one. Verge herself has sensed a man walking out of a bedroom and staring at her. Mary Surratt''s apparition has been spotted floating around the staircase and on the porch.',
   1852, 'https://www.marylandhauntedhouses.com/real-haunt/surratt-house-museum.html',
   '["https://www.marylandhauntedhouses.com/real-haunt/surratt-house-museum.html","https://cnsmaryland.org/2009/10/23/lincoln-history-sparks-museums-most-haunting-tales/","https://en.wikipedia.org/wiki/Surratt_House_Museum"]', 3),

  ('glenn-dale-hospital', 'Glenn Dale Hospital', 'Glenn Dale', '5201 Glenn Dale Road', 'MD', 38.9836, -76.8206, 'hospital',
   'An abandoned 1930s tuberculosis sanatorium in Prince George''s County, closed since 1984, notorious for paranormal encounters and eerie phenomena.',
   'Glenn Dale Hospital was established in the early 1930s to combat the tuberculosis epidemic ravaging the Washington DC area. The sprawling campus included separate buildings for adults and children, connected by underground tunnels. The hospital treated thousands of TB patients over its decades of operation, and many died within its walls. After closing in 1984 due to asbestos contamination, the abandoned complex became one of Maryland''s most notorious haunted locations. Explorers who have entered the deteriorating buildings report hearing echoing cries and laughter in empty hallways, catching the scent of burning flesh, and encountering shadow figures in the underground tunnels. Cold spots are common throughout the children''s ward, and doors slam shut on their own. The property is now fenced off and patrolled, but its haunted reputation persists.',
   1934, 'https://patch.com/maryland/laurel/top-5-haunted-places-in-maryland-419ec447',
   '["https://patch.com/maryland/laurel/top-5-haunted-places-in-maryland-419ec447","https://www.marylandhauntedhouses.com/real-haunts/","https://strangertravelsusa.com/haunted-places-in-maryland/"]', 3),

  ('maryland-state-house', 'Maryland State House', 'Annapolis', '100 State Circle', 'MD', 38.9789, -76.4907, 'museum',
   'The oldest state capitol building still in continuous legislative use, haunted by the ghost of a plasterer who fell to his death while working on the dome.',
   'The Maryland State House was completed in 1772 and holds the distinction of being the oldest state capitol building still in continuous legislative use in the United States. It served as the nation''s capital from November 1783 to August 1784, where the Continental Congress ratified the Treaty of Paris ending the Revolutionary War. The building''s most famous ghost is Thomas Dance, a plasterer who fell to his death while working on the building''s iconic wooden dome in the late 1700s. Visitors and staff have reported seeing his apparition in the old Senate chamber, particularly near the dome area where he died. Some accounts describe a shadowy figure moving along the upper galleries, while others have heard unexplained thuds and the sound of tools dropping from above. The ghost is most active during renovation work on the building.',
   1772, 'https://www.hauntedrooms.com/maryland/haunted-places',
   '["https://www.hauntedrooms.com/maryland/haunted-places","https://patch.com/maryland/annapolis/these-are-creepiest-most-haunted-places-maryland"]', 2),

-- ==========================================
-- HAVRE DE GRACE (~2 locations)
-- ==========================================

  ('concord-point-lighthouse', 'Concord Point Lighthouse', 'Havre de Grace', '700 Concord Street', 'MD', 39.5375, -76.0894, 'other',
   'An 1827 granite lighthouse at the mouth of the Susquehanna River, haunted by the famous Perfumed Ghost and shadow figures in the lantern room.',
   'Built in 1827 using local granite from Port Deposit, the Concord Point Lighthouse guards the entrance to the Susquehanna River. Its first keeper was John O''Neill, a War of 1812 hero who single-handedly manned a cannon battery on Concord Point during the British attack on Havre de Grace in 1813. Four generations of the O''Neill family served as keepers. The first documented paranormal report dates from 1889, when a keeper described a figure with glowing eyes staring through the lantern room. The lighthouse''s most famous spirit is the Perfumed Ghost — a somber woman whose presence is announced by an overwhelming floral scent. Author Ed Okonowicz documented locals seeing a slow-moving shadow in the upper windows at night, and a dark figure has been encountered near the memorial cannon at the tower''s base. A murder victim''s body discovered on the grounds in 1994 may have added another spirit to the location.',
   1827, 'https://www.hauntscout.com/places/united-states/maryland/havre-de-grace/concord-point-lighthouse/',
   '["https://www.hauntscout.com/places/united-states/maryland/havre-de-grace/concord-point-lighthouse/","https://www.southernspiritguide.org/a-perfumed-ghost-havre-de-grace-maryland/","https://usghostadventures.com/havre-de-grace-ghost-tour/"]', 3),

  ('rodgers-house-havre-de-grace', 'Rodgers House', 'Havre de Grace', '226 North Washington Street', 'MD', 39.5411, -76.0917, 'mansion',
   'A Federal-era mansion built by Commodore John Rodgers, a War of 1812 naval hero, with reports of phantom footsteps and spectral figures on moonlit nights.',
   'The Rodgers House was built in the early 1800s for Commodore John Rodgers, one of the most distinguished naval officers of the early American republic. Rodgers commanded the frigate USS President and fired the first shots of the War of 1812. The mansion sits on a bluff overlooking the Chesapeake Bay near the site where British forces burned much of Havre de Grace in May 1813. Before the sun rose on May 3rd, 1813, the British launched a harrowing attack — few buildings survived and many residents died in the fiery confusion. Locals report seeing apparitions near the old pier tiers, leftovers from a 1900s boardwalk, walking over the place where the boardwalk used to be on moonlit nights. The Rodgers House itself has reports of phantom footsteps on its grand staircase and unexplained cold spots in the parlor rooms.',
   1810, 'https://usghostadventures.com/havre-de-grace-ghost-tour/',
   '["https://usghostadventures.com/havre-de-grace-ghost-tour/","https://www.havredehaunts.com/"]', 2),

-- ==========================================
-- EASTERN SHORE (~5 locations)
-- ==========================================

  ('old-brick-inn-st-michaels', 'Kemp House Inn', 'St. Michaels', '412 Talbot Street', 'MD', 38.7854, -76.2248, 'hotel',
   'An 1807 inn once owned by a Civil War soldier, haunted by arguing gentlemen, a blue ball of light, and the apparition of Robert E. Lee.',
   'The Kemp House Inn dates to 1807 and was once owned by a Civil War soldier. The historic bed and breakfast in St. Michaels is rumored to be haunted by at least three distinct spirits. Two gentlemen have been heard arguing in a room downstairs — their heated debate ceases whenever someone enters the room. A mysterious blue ball of light has been seen flying through the house, slamming doors in its wake. Most dramatically, the apparition of Robert E. Lee, who once stayed at the former home, has been spotted by multiple witnesses. Lee''s ghost is typically seen in full military dress, standing near the fireplace or ascending the staircase before vanishing.',
   1807, 'https://discover.hubpages.com/literature/Haunted-EasternShoreGhostsSpooksSpiritsandHauntingsonMarylandsEastern-Shore',
   '["https://discover.hubpages.com/literature/Haunted-EasternShoreGhostsSpooksSpiritsandHauntingsonMarylandsEastern-Shore","https://chesapeakeghosts.com/"]', 2),

  ('teackle-mansion', 'Teackle Mansion', 'Princess Anne', '11736 Mansion Street', 'MD', 38.2006, -75.9237, 'mansion',
   'A grand Neoclassical mansion built in 1802, haunted by the ghost of Elizabeth Teackle who walks the second-story windows at night in a long white dress.',
   'Littleton Dennis Teackle built this grand Neoclassical mansion in 1802 in Princess Anne on Maryland''s Eastern Shore. The symmetrical five-part structure was modeled after a Scottish manor and was one of the finest homes on the Delmarva Peninsula. Elizabeth Teackle, Littleton''s wife, became deeply attached to the home, and the family''s financial ruin and loss of the property devastated her. At night, an apparition can be seen walking from one side of the second story to the other — many believe this is Elizabeth, still pacing the halls of her beloved home. A former tenant reported waking to see a woman in a long white dress who walked through his door and over to the window before vanishing. The Princess Anne ghost tour, considered the most disturbing on the Eastern Shore, includes the mansion as a key stop.',
   1802, 'https://www.wmdt.com/2018/10/haunted-delmarva-princess-anne/',
   '["https://www.wmdt.com/2018/10/haunted-delmarva-princess-anne/","https://chesapeakeghosts.com/ghost-walk-guide/"]', 2),

  ('old-jail-princess-anne', 'Old Princess Anne Jail', 'Princess Anne', '30888 Church Street', 'MD', 38.1994, -75.9244, 'prison',
   'A stone-walled jail rebuilt after prisoners burned the original, now a police station where officers and dispatchers report encounters with a frightening female apparition.',
   'The original jail in Princess Anne was burned down by escaping prisoners, so its replacement was constructed with 18-inch-thick stone walls to prevent another breakout. The building later became the town''s police department, but its violent past left an indelible mark. Dispatchers working late-night shifts have reported hearing cell doors slamming in the now-empty jail section. Police officers have had paranormal encounters throughout the building. In one chilling incident, a child visiting the station reported seeing a frightening, sick-looking woman in the building — in a part of the structure where no one was present. The apparition is believed to be a former inmate who died in custody. Somerset County is considered one of the most paranormally active areas on the Eastern Shore.',
   1870, 'https://www.wmdt.com/2018/10/haunted-delmarva-princess-anne/',
   '["https://www.wmdt.com/2018/10/haunted-delmarva-princess-anne/","https://chesapeakeghosts.com/ghost-walk-guide/"]', 2),

  ('old-white-marsh-church', 'Old White Marsh Church', 'Trappe', '9015 White Marsh Road', 'MD', 38.6556, -76.0583, 'cemetery',
   'Maryland''s oldest Episcopal church, established in 1655, where the ghost of Hanna — buried alive in the 1720s — still walks home from the cemetery.',
   'Old White Marsh Episcopal Church first opened in 1655, making it one of the oldest churches in Maryland. The most famous ghost story dates to the 1720s when the rector''s wife, Hanna, fell into a deep coma and was declared dead. She was buried in the church cemetery, but that night graverobbers came to steal the ring from her finger. When they cut her hand to remove the ring, Hanna awoke from her coma. She climbed out of the coffin and walked home to the rectory, shocking her grieving husband. Hanna lived for many more years after her premature burial, but locals say her ghost still makes that same walk — from the cemetery back toward the rectory — on dark nights. Witnesses have reported a pale woman in colonial dress moving silently along the path between the graveyard and the old church.',
   1655, 'https://discover.hubpages.com/literature/Haunted-EasternShoreGhostsSpooksSpiritsandHauntingsonMarylandsEastern-Shore',
   '["https://discover.hubpages.com/literature/Haunted-EasternShoreGhostsSpooksSpiritsandHauntingsonMarylandsEastern-Shore","https://chesapeakeghosts.com/the-eastern-shore-of-maryland-and-its-ghosts/"]', 2),

  ('high-street-cambridge', 'High Street Historic District', 'Cambridge', 'High Street', 'MD', 38.5634, -76.0789, 'other',
   'Called the most haunted street in America with 14 haunted sites in just two city blocks, including the tale of Bloody Henny and the LeCompte Curse.',
   'High Street in Cambridge has been called "the most haunted street in the country" by Eastern Shore ghost tour author Mindie Burgoyne, with 14 documented haunted sites packed into just two city blocks. Dorchester County, with Cambridge as its county seat, is considered the most paranormally active area on the Eastern Shore. The street''s most famous legend is Bloody Henny and the LeCompte Curse — a tale involving a powerful planter family and a gruesome revenge that echoes through generations. At nearby Christ Church cemetery, a yew tree more than 200 years old has roots encroaching on a headstone from 1817, and when the wind blows, the tree is said to sing. The concentration of hauntings is attributed to Cambridge''s violent colonial history, its role in the slave trade, and the maritime deaths along the Choptank River.',
   1684, 'https://chesapeakeghosts.com/the-eastern-shore-of-maryland-and-its-ghosts/',
   '["https://chesapeakeghosts.com/the-eastern-shore-of-maryland-and-its-ghosts/","https://whatsupmag.com/news/tales-ghosts-maryland-s-eastern-shore-reveal-history-imagination/","https://shorebread.com/2016/10/11/40-ghost-tours-october-marylands-eastern-shore/"]', 3),

  ('denton-old-jail', 'Old Denton Jail', 'Denton', '207 Market Street', 'MD', 38.8843, -75.8271, 'prison',
   'A 19th-century jail on Maryland''s Eastern Shore, believed to be haunted by the ghost of executed murderer Wish Sheppard.',
   'The Old Denton Jail is considered one of the most haunted sites on Maryland''s Eastern Shore. The building is believed to be haunted by the ghost of Wish Sheppard, a man who was executed for murder in the 19th century. Staff and visitors report significant paranormal activity including cell doors slamming shut, disembodied voices echoing through the stone corridors, and the feeling of being watched in the basement cells. The jail sits near two very old graveyards, and the area around Market Street has additional reports of hauntings connected to the ghosts of doctors, sailors, sea captains, and senators who lived in the surrounding historic homes. Denton is also known for the disturbing legend of the Town Dog Killer, whose spirit is said to wander the streets at night.',
   1860, 'https://chesapeakeghosts.com/ghost-walk-guide/',
   '["https://chesapeakeghosts.com/ghost-walk-guide/","https://shorebread.com/2016/10/11/40-ghost-tours-october-marylands-eastern-shore/"]', 2);
