-- Connecticut Batch 2: 6 new places to reach 40 total
-- Sources: CTvisit, damnedct.com, hauntedplaces.org, cthauntedhouses.com, Atlas Obscura, heystamford.com

INSERT OR REPLACE INTO places (slug, name, city, state, latitude, longitude, category, year_established, ghost_story, source_count) VALUES
('bara-hack', 'Bara-Hack', 'Pomfret', 'CT', 41.8867, -71.9567, 'landmark', 1778, 'Bara-Hack, the "Village of Ghostly Voices," was settled in 1778 by two Welsh colonists who fled Rhode Island during the Revolutionary War. The tiny community of farms, a mill, and slave quarters along Nightingale Brook was abandoned by 1890—but the sounds of daily life never stopped. Visitors hear children laughing, mothers calling, dogs barking, cows lowing, and wagon wheels rumbling through empty forest. In 1971, paranormal investigator Paul Eno watched a bearded face hover over the cemetery wall for seven minutes, while a baby-like figure reclined in the branches of an elm tree. The site became so overrun with ghost hunters that it is now closed to the public, accessible only by special permit.', 3),

('hearthstone-castle', 'Hearthstone Castle', 'Danbury', 'CT', 41.4100, -73.4650, 'mansion', 1899, 'Hearthstone Castle, a sixteen-room stone fortress built between 1895 and 1899 for society photographer Elias Starr Sanford, sits abandoned in Danbury''s 722-acre Tarrywile Park with its roof collapsed and windows boarded. The rock was quarried on-site and transported on a small railroad built solely for construction, while all woodwork was imported from Italy. Now shadowy figures appear in the empty windows at night, and hikers on surrounding trails are pelted with rocks and sticks by unseen hands. A phantom black dog stalks the grounds, and one explorer reported seeing a glowing man running through the floor below. In the basement, visitors experience sudden temperature drops, panting breath sounds, and pairs of glowing eyes that vanish when illuminated.', 3),

('gunntown-cemetery', 'Gunntown Cemetery', 'Naugatuck', 'CT', 41.4856, -73.0550, 'cemetery', 1790, 'Dating to 1790 and named for descendants of London immigrant Jasper Gunn, Gunntown Cemetery is the final resting place of numerous Revolutionary War veterans—and was declared "officially haunted" by famed demonologists Ed and Lorraine Warren. A spectral man carrying a lantern leads a phantom horse across the grounds at night, a little boy plays near the back wall before vanishing when approached, and a black ghost dog appears and disappears in the mist. Unexplained music and children''s laughter echo between the weathered headstones, and paranormal investigators have captured numerous EVPs and photographed spirit orbs drifting among the graves. Lorraine Warren warned that dark energy lingers here—not from the dead, but from those who visit for dark purposes.', 3),

('palace-theatre-stamford', 'Palace Theatre', 'Stamford', 'CT', 41.0534, -73.5387, 'theater', 1893, 'The Palace Theatre in downtown Stamford, built in 1893, is haunted by the spirit of former owner Mary Vuono, who died in her apartment directly above the auditorium. Staff working alone after hours hear persistent whistling that follows them through the building, and theater seats flip up and down rapidly without anyone near them. Dark shadows slide along the walls of the auditorium and backstage corridors, moving against the direction of any light source. During a 2012 paranormal investigation, forty participants documented cold spots concentrated near the apartment stairwell and captured audio of a woman''s voice whispering what sounded like stage directions. The phenomena intensify during show weeks, as if Mary still watches over every performance from above.', 2),

('little-peoples-village', 'Little People''s Village', 'Middlebury', 'CT', 41.5286, -73.1136, 'landmark', NULL, 'Deep in the woods of Middlebury, a collection of crumbling miniature stone houses surrounds a full-sized stone throne—the remains of what locals call Little People''s Village. Legend says a man living in the forest began hearing voices of fairies commanding him to build houses for them. He obeyed, constructing tiny dwellings one after another, but the voices never stopped. They slowly drove him to madness and eventual suicide. The centerpiece is the "Death Throne"—anyone who sits upon it is said to die within seven years. Visitors report overwhelming feelings of dread near the structures, disembodied whispers in the trees, and cold spots that follow them along the path. The ruins of the builder''s own home still stand nearby, with a tunnel system running beneath the foundation.', 2),

('norwich-state-hospital', 'Norwich State Hospital', 'Norwich', 'CT', 41.5248, -72.0889, 'hospital', 1904, 'Norwich State Hospital for the Insane opened in 1904, built atop the remains of an ancient Native American village on a hillside overlooking the Thames River. For nearly a century it housed the criminally insane in the notorious Salmon Building, where patients were subjected to experimental treatments including lobotomies and insulin shock therapy. Since its closure, paranormal investigators have documented hundreds of unexplained events—a woman''s inconsolable sobbing echoes through empty corridors, the sounds of beeping equipment and rattling surgical tools emanate from long-gutted operating rooms, and shadow figures dart between doorways. Scratch marks appear on investigators'' arms after visiting the Salmon Building''s basement, and one team captured an EVP clearly stating "Get out of my room."', 3);
