-- Ohio Batch 2: 11 new places to reach 40 total
-- Sources: Ohio Exploration Society, hauntedplaces.org, hauntedrooms.com, ohiohauntedhouses.com, local news

INSERT OR REPLACE INTO places (slug, name, city, state, latitude, longitude, category, year_established, ghost_story, source_count) VALUES
('akron-civic-theatre', 'Akron Civic Theatre', 'Akron', 'OH', 41.0828, -81.5190, 'theater', 1929, 'The Akron Civic Theatre is haunted by at least three spirits. The most active is Fred, a lifelong custodian who died on the premises and still tends to his duties—reportedly attacking vandals who damage the building. A ghostly crying woman is sometimes seen along the canal that runs beneath the theater, and a well-dressed man in period clothing appears sitting alone in the balcony during performances, vanishing when approached.', 3),

('youngstown-playhouse', 'Youngstown Playhouse', 'Youngstown', 'OH', 41.1006, -80.6628, 'theater', 1924, 'The Youngstown Playhouse, once the nation''s largest community theatre, has been reporting paranormal activity for decades. A shadow man sits in the balcony during performances, visible to actors on stage. A half-seen face has startled stagehands in the light booth, and a mysterious white figure slides through closed doors. Staff report unexplained cold spots, ghostly music playing when the building is empty, and strange whispering in the wings.', 2),

('lafayette-hotel', 'Lafayette Hotel', 'Marietta', 'OH', 39.4145, -81.4550, 'hotel', 1918, 'The Lafayette Hotel in historic Marietta is haunted by the Hoag family, who once owned the building. Since their deaths, family members have been spotted in the basement level, where they harass employees by locking doors and shutting off lights. Mr. Hoag frequents the third floor, and guests have reported waking to see a well-dressed man standing at the foot of their bed before he fades away. The hotel sits near the confluence of the Ohio and Muskingum Rivers.', 3),

('sandusky-state-theater', 'Sandusky State Theater', 'Sandusky', 'OH', 41.4489, -82.7079, 'theater', 1928, 'The Sandusky State Theater harbors at least four spirits. An eyewitness cleaning the balcony watched a glowing light-blue figure wearing 1920s-era clothing walk across the stage, stop, look directly at them, then vanish. The projectionist heard someone whisper "Change the focus" repeatedly while alone in the booth—the projector then stopped on its own. Cold spots plague the backstage area, and seat cushions are found depressed as if someone just stood up.', 2),

('sandusky-county-jail', 'Sandusky County Historic Jail', 'Fremont', 'OH', 41.3503, -83.1188, 'prison', 1892, 'The first prisoner incarcerated in the Sandusky County Jail, George Thompson, was sentenced to death by hanging for murder. The execution was not clean—it took twenty agonizing minutes for him to die. Since then, paranormal investigators have emerged from the dungeon with unexplained scratches on their arms, and visitors report being touched by unseen hands. Cell doors slam shut on their own, and Thompson''s desperate gasping has been captured on audio recordings.', 3),

('everett-covered-bridge', 'Everett Covered Bridge', 'Peninsula', 'OH', 41.1872, -81.5567, 'bridge', 1870, 'The Everett Covered Bridge in the Cuyahoga Valley was rebuilt after a horse-drawn carriage was swept away when the river flooded the original crossing. Visitors report feeling an overwhelming sense of unease inside the bridge, especially at dusk. Ghostly vapors and partial apparitions have appeared in photographs taken at the site, and the sound of wooden wheels on planks is heard when no vehicles are present. Some claim to see a lantern light approaching from inside the bridge.', 2),

('butler-county-courthouse', 'Butler County Courthouse', 'Hamilton', 'OH', 39.3995, -84.5613, 'government', 1889, 'The Historic Butler County Courthouse in Hamilton has served as a courthouse, jail, and government center throughout its long history. Staff report seeing shadowy figures in the hallways after hours, hearing unexplainable footsteps in empty rooms, and feeling sudden temperature drops in specific corners. The building''s most persistent ghost is believed to be a former night watchman who was killed during a robbery in the 1860s, still making his rounds through the darkened corridors.', 2),

('edwin-shaw-hospital', 'Edwin Shaw Hospital', 'Lakemore', 'OH', 41.0203, -81.4350, 'hospital', 1908, 'Formerly the Springfield Lake Sanitarium, Edwin Shaw Hospital served as Summit County''s tuberculosis hospital for fifty years, housing patients who were essentially quarantined until they recovered or died. Employees reported doors opening and closing by themselves, ghostly footsteps echoing through empty wards, and occasional sightings of patients in hospital gowns wandering the halls. The sounds of coughing and labored breathing have been heard in rooms that have been empty for decades.', 2),

('wilson-hall-ohio-university', 'Wilson Hall', 'Athens', 'OH', 39.3255, -82.1013, 'university', 1964, 'Wilson Hall at Ohio University is so haunted that Room 428 was permanently sealed and declared uninhabitable. In the 1970s, two students died under mysterious circumstances in the room—one male student under unexplained conditions, and later a female student who reportedly practiced occult rituals including astral projection. Objects flew off shelves and shattered against walls, and the door slammed open and shut repeatedly. Students still report seeing a girl standing at the sealed room''s window. The building sits at the center of five cemeteries that form a pentagram on the map.', 3),

('riders-inn', 'Rider''s Inn', 'Painesville', 'OH', 41.7242, -81.2457, 'hotel', 1812, 'Rider''s Inn has been welcoming guests since 1812, first as a stagecoach stop, then as an Underground Railroad station, and later as a Prohibition-era speakeasy. The most famous ghost is Suzanne Rider, wife of founder Joseph, who still appears at the front door in her nightgown to let late-arriving guests inside. A Civil War soldier stands near the windows and waves at passersby, and a music box in the parlor starts playing on its own during paranormal investigations. Escaped slaves once hid in the basement, and their whispered prayers are occasionally still heard.', 3),

('oxford-light', 'Oxford Light', 'Oxford', 'OH', 39.5070, -84.7280, 'road', NULL, 'On Oxford-Milford Road outside Oxford, a ghostly light appears on dark nights where two forbidden lovers once met in secret. According to local legend, the boyfriend lost control of his vehicle at a sharp bend, crashed through a barbed wire fence, and was decapitated. His grief-stricken girlfriend later hanged herself in her family home. Drivers now report seeing a bobbing light along the roadside—said to be the boyfriend searching for his head—and a spectral figure of a young woman in white standing at the bend before vanishing from their headlights.', 2);
