-- Seed data for tour_operators table
-- Generated by researcher agent on 2026-01-22
--
-- Coverage: Top 10 most popular haunted destinations
-- 1. New Orleans, LA (8 operators)
-- 2. Savannah, GA (7 operators)
-- 3. Salem, MA (6 operators)
-- 4. Gettysburg, PA (6 operators)
-- 5. St. Augustine, FL (6 operators)
-- 6. Charleston, SC (5 operators)
-- 7. San Antonio, TX (6 operators)
-- 8. Key West, FL (5 operators)
-- 9. Chicago, IL (6 operators)
-- 10. Nashville/Franklin, TN (6 operators)
--
-- Total: 61 tour operators

-- =====================================================
-- NEW ORLEANS, LA - French Quarter, cemetery, voodoo tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('French Quarter Phantoms', 'New Orleans', 'LA',
   'https://www.frenchquarterphantoms.com/',
   'https://www.frenchquarterphantoms.com/ghost-and-vampire-tour',
   'Award-winning ghost tour voted #1 Haunted Tour in New Orleans 8 years in a row. Featured in TripAdvisor Top Ten Ghost Tours in the World. Tours depart from The Voodoo Lounge and include a two-for-one hurricane drink special.',
   '$22-25', 'walking, vampire, voodoo, garden district', TRUE),

  ('Haunted History Tours', 'New Orleans', 'LA',
   'https://hauntedhistorytours.com/',
   'https://hauntedhistorytours.com/',
   'The original New Orleans ghost tour company since 1995. Featured on A&E, History Channel, Discovery Channel, and recommended by Travel Channel as the #1 tour in New Orleans. Offers ghost, vampire, voodoo, cemetery, and pub crawl tours.',
   '$22-35', 'walking, vampire, voodoo, cemetery, pub crawl, bus', TRUE),

  ('Ghost City Tours', 'New Orleans', 'LA',
   'https://ghostcitytours.com/new-orleans/',
   'https://ghostcitytours.com/ticket-sales/',
   'Offers the Ghosts of New Orleans Tour (all-ages), Killers and Thrillers (adults-only), and Haunted Pub Crawl. 97% of guests give highest ratings. No price fluctuation during busy seasons.',
   '$19.95-30', 'walking, pub crawl, adults-only', TRUE),

  ('US Ghost Adventures', 'New Orleans', 'LA',
   'https://usghostadventures.com/new-orleans-ghost-tour/',
   'https://usghostadventures.com/new-orleans-ghost-tour/',
   'National ghost tour company with entertaining, historic tours of the French Quarter. Claims New Orleans is the most haunted city on earth. Offers both family-friendly and adults-only options.',
   '$25-35', 'walking, pub crawl', FALSE),

  ('Nightly Spirits', 'New Orleans', 'LA',
   'https://nightlyspirits.com/new-orleans-ghost-tours/',
   'https://nightlyspirits.com/new-orleans-ghost-tours/',
   'Rated #1 Ghost Tour in America by USA Today. Haunted pub tours stop at 3-4 famous bars while sharing ghost stories and local history. 2.5-hour tours through the French Quarter.',
   '$28-35', 'pub crawl, walking', FALSE),

  ('Gators and Ghosts', 'New Orleans', 'LA',
   'https://www.gatorsandghosts.com/',
   'https://www.gatorsandghosts.com/',
   'Authentic New Orleans experiences with local experts. Over 3,000+ five-star reviews. Offers both swamp adventures and ghost tours for a complete Louisiana experience.',
   '$25-40', 'walking, swamp combo', FALSE),

  ('Witches Brew Tours', 'New Orleans', 'LA',
   'https://www.witchesbrewtours.com/',
   'https://www.witchesbrewtours.com/',
   'Highly-rated French Quarter, Voodoo and Cemetery Tour described as three tours in one. Guides are great storytellers known for knowledgeable, funny, and spooky stories. Visits Jackson Square, Pharmacy Museum, and Lafitte Blacksmith Shop.',
   '$25-35', 'walking, voodoo, cemetery', FALSE),

  ('Two Chicks Walking Tours', 'New Orleans', 'LA',
   'https://www.twochickswalkingtours.com/',
   'https://www.twochickswalkingtours.com/',
   'Locally owned female-operated tour company ranked in Yelps Top 10. Offers intimate walking tours through the French Quarter with a focus on storytelling and local expertise.',
   '$25-30', 'walking, history, ghost', FALSE);

-- =====================================================
-- SAVANNAH, GA - One of Americas most haunted cities
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Genteel and Bard', 'Savannah', 'GA',
   'https://genteelandbard.com/',
   'https://genteelandbard.com/',
   'Rated #1 guide and best Savannah tours with 5 stars on TripAdvisor and Yelp. Named one of the spookiest ghost tours in the world. Guides use microphones for clear audio on all tours.',
   '$30-40', 'walking, history, ghost', TRUE),

  ('Blue Orb Tours', 'Savannah', 'GA',
   'https://blueorbtours.com/',
   'https://blueorbtours.com/',
   'Top 10 Ghost Tour in the World by TripAdvisor Editorial. Top 3 Ghost Tours in USA by USA Today Fan Poll multiple years. Offers Adults Only (18+), Family/All Ages, and Private Party options.',
   '$10-30', 'walking, adults-only, family', TRUE),

  ('Ghost City Tours', 'Savannah', 'GA',
   'https://ghostcitytours.com/ghost-tours/savannah-ghost-tours/',
   'https://ghostcitytours.com/ticket-sales/',
   '97% highest ratings on review websites. Beyond Good and Evil Tour blends humor, macabre, voodoo, and local folklore. Conde Nast agrees they have the best pub crawl in Savannah.',
   '$19.95-30', 'walking, pub crawl, adults-only', TRUE),

  ('Ghosts and Gravestones', 'Savannah', 'GA',
   'https://www.ghostsandgravestones.com/savannah',
   'https://www.trolleytours.com/savannah/ghosts-gravestones-tour',
   'Old Town Trolley Tours nighttime experience. Featured on The Today Show and Travel Channel. Exclusive nighttime entry to Andrew Low House and Perkins and Sons Ship Chandlery. Over 30 years in operation.',
   '$35-45', 'trolley, historic sites', FALSE),

  ('Sixth Sense Tours', 'Savannah', 'GA',
   'https://www.6thsenseworld.com/',
   'https://www.6thsenseworld.com/',
   'Female-owned business offering unique content different from typical tours. Visits the Espy House and discusses old Candler tunnels. Perfect for those wanting a different perspective.',
   '$25-35', 'walking, historic', FALSE),

  ('Hearse Ghost Tours', 'Savannah', 'GA',
   'https://www.savannahhearse.com/',
   'https://www.savannahhearse.com/',
   'Unique opportunity to tour Savannahs strangest sites via a funeral hearse. Sets this tour apart with its eerie vehicle and attention to spooky detail.',
   '$35-50', 'hearse ride, unique', FALSE),

  ('The Ghostwalker Tour', 'Savannah', 'GA',
   'https://www.ghostwalkersavannah.com/',
   'https://www.ghostwalkersavannah.com/',
   'Excellent alcohol-free option with tours capped at 15 attendees for a more personal, interactive experience. Great for families or those avoiding bar stops.',
   '$25-30', 'walking, family-friendly', FALSE);

-- =====================================================
-- SALEM, MA - Witch history, October peak season
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Salem Historical Tours / Haunted Footsteps', 'Salem', 'MA',
   'https://www.salemhistoricaltours.com/',
   'https://www.salemhistoricaltours.com/',
   'Salems Original ghostly tour since 1997. Oldest established professional walking tour in the Witch City. Lantern-lit strolls through historic Salem with multiple daily departures October through January.',
   '$20-30', 'walking, lantern, history', TRUE),

  ('Spellbound Tours', 'Salem', 'MA',
   'https://spellboundtours.com/',
   'https://spellboundtours.com/',
   'Salems original and longest-running haunted ghost tour founded in 2000 by a certified parapsychologist. Only tour company that has done paranormal investigation at all sites visited. Voodoo, vampires, and witch trial history.',
   '$7-21', 'walking, paranormal, witch trials', TRUE),

  ('Witch City Walking Tours', 'Salem', 'MA',
   'https://witchcitywalkingtours.com/',
   'https://witchcitywalkingtours.com/',
   'Adults-only spooky walking tour visiting Salems darkest corners. 400-year-old cemeteries, haunted homes, and 2 of the most haunted hotels in America. Sinister tales of deception, torture, and murder.',
   '$25-35', 'walking, adults-only, cemetery', TRUE),

  ('Salem Ghosts', 'Salem', 'MA',
   'https://salemghosts.com/',
   'https://salemghosts.com/',
   'Visits the citys most haunted and historic sites, following spectral footsteps of judges, witches, and the wrongly condemned. Nightly tours rain or shine. Meets outside the John Ward House.',
   '$25-30', 'walking, witch history', FALSE),

  ('Wicked Awesome Tours', 'Salem', 'MA',
   'https://www.tripadvisor.com/AttractionProductReview-g60954-d25177177-Wicked_Awesome_Tours_Witch_Trial_History_and_Salem_Haunts-Salem_Massachusetts.html',
   'https://www.viator.com/Salem',
   'Balances historical facts with local legends for both informative and entertaining experience. 4.9 rating from over 700 reviews. Witch trial history combined with ghost stories.',
   '$35-40', 'walking, history, ghost', FALSE),

  ('Salem Night Tour', 'Salem', 'MA',
   'https://www.salemnighttour.com/',
   'https://www.salemnighttour.com/',
   'Voted one of the 10 best ghost tours in the US five years in a row. Features dramatic storytelling and historic accuracy. Perfect for understanding both witch trial history and modern hauntings.',
   '$20-30', 'walking, night tour', FALSE);

-- =====================================================
-- GETTYSBURG, PA - Civil War battlefield ghost tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Mark Nesbitts Ghosts of Gettysburg', 'Gettysburg', 'PA',
   'https://ghostsofgettysburg.com/',
   'https://ghostsofgettysburg.com/our-tours/',
   'The original Ghost Tour in Gettysburg by former Park Ranger and author Mark Nesbitt. Based on the bestselling Ghosts of Gettysburg book series. Period-dressed guides with candlelit lanterns. 75-minute tours through downtown.',
   '$5-17.50', 'walking, lantern, author-led', TRUE),

  ('Gettysburg Battlefield Tours / Ghostly Images', 'Gettysburg', 'PA',
   'https://www.gettysburgbattlefieldtours.com/ghost-tours/',
   'https://www.gettysburgbattlefieldtours.com/ghost-tours/',
   'Only ghost tour that takes you inside two historic haunted homes. Offers Spirits of Jennie Wade Tour, Haunted Orphanage Tour, Ghost Bus Tours, midnight tours, and professional ghost hunts with Black Lantern Paranormal.',
   '$20-75', 'walking, bus, paranormal investigation', TRUE),

  ('Ghost City Tours', 'Gettysburg', 'PA',
   'https://ghostcitytours.com/gettysburg/',
   'https://ghostcitytours.com/gettysburg/blood-battlefield-tour/',
   'Blood on the Battlefield is Gettysburgs #1 adults-only ghost tour with unmatched 4.8-star rating. Explores darker truths of human nature and horrors of war. Starts at Ghost City Store on Lincoln Square.',
   '$19.95-30', 'walking, adults-only, battlefield', TRUE),

  ('US Ghost Adventures', 'Gettysburg', 'PA',
   'https://usghostadventures.com/gettysburg-ghost-tour/',
   'https://usghostadventures.com/gettysburg-ghost-tour/',
   'Private battlefield tours with expert licensed battlefield guides covering every iconic location. Also offers paranormal investigations at Jennie Wade birthplace. Part of national ghost tour network.',
   '$25-100', 'walking, battlefield, investigation', FALSE),

  ('Civil War Ghosts', 'Gettysburg', 'PA',
   'https://gettysburgghosts.com/',
   'https://gettysburgghosts.com/',
   'Nightly ghost tours rain or shine exploring the haunted Welty House and Historic Jennie Wade Birthplace. Little Round Top featured as one of Americas most hallowed and haunting sites.',
   '$20-35', 'walking, battlefield, historic homes', FALSE),

  ('Farnsworth House Ghost Tours', 'Gettysburg', 'PA',
   'https://www.farnsworthhouseinn.com/',
   'https://www.farnsworthhouseinn.com/',
   'Tours of one of the most haunted buildings in Gettysburg, an actual Civil War-era inn still in operation. Confederate sharpshooters occupied the house during battle. Unique indoor haunted experience.',
   '$15-30', 'walking, indoor, historic inn', FALSE);

-- =====================================================
-- ST. AUGUSTINE, FL - Oldest city in America
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('GhoSt Augustine', 'St. Augustine', 'FL',
   'https://ghostaugustine.com/',
   'https://ghostaugustine.com/',
   'Founded in 2001, independently-owned ghost tour company. Original non-theatrical tours for those wanting to avoid large crowds. Featured on My Ghost Story and Most Terrifying Places in America. Offers Pub Hearse Ride and ParaForce Investigations.',
   '$25-85', 'walking, pub crawl, hearse, investigation', TRUE),

  ('Ghost City Tours', 'St. Augustine', 'FL',
   'https://ghostcitytours.com/st-augustine/',
   'https://ghostcitytours.com/ticket-sales/',
   '#1 rated family-friendly ghost tour with near-perfect 4.9-star rating. Trusted by hundreds of thousands of guests since 2020. Also offers highest-rated Haunted Pub Crawl with 4.7 stars.',
   '$19.95-30', 'walking, pub crawl, family', TRUE),

  ('Ghosts and Gravestones', 'St. Augustine', 'FL',
   'https://www.ghostsandgravestones.com/st-augustine',
   'https://www.trolleytours.com/st-augustine/ghosts-gravestones-tour',
   'Old Town Trolley frightseeing adventure including Old Jail After Dark paranormal investigation. Old Jail listed on Florida and National Register of Haunted Places, built by same company that built Alcatraz.',
   '$30-55', 'trolley, investigation, jail', TRUE),

  ('Nightly Spirits', 'St. Augustine', 'FL',
   'https://nightlyspirits.com/st-augustine-ghost-tours/',
   'https://nightlyspirits.com/st-augustine-ghost-tours/',
   'Historic Haunted Booze and Boos Tours visiting spookiest places while stopping at several local bars. Also offers all-ages ghost tour that is not super frightening for families.',
   '$28-35', 'pub crawl, walking, family', FALSE),

  ('A Ghostly Encounter', 'St. Augustine', 'FL',
   'https://www.aghostlyencounter.com/',
   'https://www.aghostlyencounter.com/',
   'Ranked in Yelps Top 10 Ghost Tours. Intimate walking tours with knowledgeable local guides sharing 450+ years of St. Augustine ghost stories and history.',
   '$20-30', 'walking, history', FALSE),

  ('St. Augustine Lighthouse Dark of the Moon', 'St. Augustine', 'FL',
   'https://www.staugustinelighthouse.org/',
   'https://www.staugustinelighthouse.org/visit/events/',
   'Official ghost tour of the haunted St. Augustine Lighthouse. Dark of the Moon tours explore the lighthouse after hours with stories of the Pittee girls who drowned during construction.',
   '$25-40', 'lighthouse, paranormal', FALSE);

-- =====================================================
-- CHARLESTON, SC - Historic district tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Bulldog Tours', 'Charleston', 'SC',
   'https://www.bulldogtours.com/',
   'https://www.bulldogtours.com/tours/ghost',
   'Voted Charlestons #1 tour company. Only company with exclusive access to the citys dungeon and historic graveyard. Offers Ghost and Dungeon, Ghost and Graveyard, Dark Side of Charleston (Rated R), and Haunted Jail tours.',
   '$29-39', 'walking, dungeon, cemetery, jail', TRUE),

  ('Ghost City Tours', 'Charleston', 'SC',
   'https://ghostcitytours.com/charleston/',
   'https://ghostcitytours.com/ticket-sales/',
   'Death and Depravity Ghost Tour is Charlestons #1 adults-only tour with unmatched 4.9-star rating. Highest-rated ghost tour since 2016. Also offers top-rated Haunted Pub Crawl.',
   '$19.95-30', 'walking, pub crawl, adults-only', TRUE),

  ('Nightly Spirits', 'Charleston', 'SC',
   'https://nightlyspirits.com/charleston-ghost-tours/',
   'https://nightlyspirits.com/charleston-ghost-tours/',
   'Voted top 3 ghost tour in America by USA Today multiple years. 2.5-hour ghostly pub crawl through the historic district. Best ghost tour experience in the deep South.',
   '$28-35', 'pub crawl, walking', TRUE),

  ('Ghosts of Charleston', 'Charleston', 'SC',
   'https://www.ghostsofcharleston.com/',
   'https://www.ghostsofcharleston.com/',
   'One of the oldest ghost tour companies in Charleston. Featured in Yelps Top 10. Walking tours through the historic district sharing tales of Civil War, pirates, and plantation ghosts.',
   '$25-35', 'walking, history', FALSE),

  ('Old Charleston Walking Tours', 'Charleston', 'SC',
   'https://www.oldcharlestonwalkingtours.com/',
   'https://www.oldcharlestonwalkingtours.com/',
   'Pleasing Terrors ghost tour featured in Yelps Top 10. Licensed guides share Charleston dark history including the Old Jail, Lavinia Fisher, and Battery ghosts.',
   '$25-35', 'walking, history, jail', FALSE);

-- =====================================================
-- SAN ANTONIO, TX - Alamo area tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Alamo City Ghost Tours', 'San Antonio', 'TX',
   'https://alamocityghosttours.com/',
   'https://alamocityghosttours.com/',
   'Tours start at San Fernando Cathedral with state-of-the-art ghost-hunting equipment. Explores ghostly legends and paranormal activity around the Alamo, downtown churches, and River Walk.',
   '$25-40', 'walking, equipment, paranormal', TRUE),

  ('RJA Ghost Tours', 'San Antonio', 'TX',
   'https://www.rjaghosttours.com/',
   'https://www.rjaghosttours.com/',
   'Authentic ghost tours led by Certified Paranormal Investigators. Nightly tours in San Antonio covering the Alamo hauntings, local history, folklore, and mysterious locations.',
   '$25-35', 'walking, paranormal investigation', TRUE),

  ('River City Ghosts', 'San Antonio', 'TX',
   'https://rivercityghosts.com',
   'https://rivercityghosts.com',
   'Explores haunted San Antonio including Alamo ghosts and the Menger Hotel where history never checks out. Nightly tours rain or shine meeting at 320 Bonham San Antonio.',
   '$25-35', 'walking, history', TRUE),

  ('Bad Wolf Ghost Tours / Sisters Grimm', 'San Antonio', 'TX',
   'https://badwolfghosttours.com/',
   'https://badwolfghosttours.com/home/san-ghost-walk/',
   'San Antonio Ghost Walk explores downtown oldest and most haunted locations including the Alamo and River Walk. Also offers Haunted Pub Crawl (21+) and Haunted Dinner Tour at Emily Morgan Hotel.',
   '$25-65', 'walking, pub crawl, dinner tour', FALSE),

  ('US Ghost Adventures', 'San Antonio', 'TX',
   'https://usghostadventures.com/san-antonio-ghost-tour/',
   'https://usghostadventures.com/san-antonio-ghost-tour/',
   'One-hour tours covering downtown San Antonio haunted history. The Alamo featured as one of the most haunted places in the United States with unexplained phenomena for over 150 years.',
   '$25-30', 'walking, history', FALSE),

  ('The Alamo Ghost Hunt Tour', 'San Antonio', 'TX',
   'https://www.tripadvisor.com/Attraction_Review-g60956-d1371280-Reviews-The_Alamo_Ghost_Hunt_Tour-San_Antonio_Texas.html',
   'https://www.viator.com/San-Antonio',
   'Interactive ghost hunt using EMF devices and dowsing rods. Well-informed guides share history of old buildings and the Alamo. Considered one of the best things to do in San Antonio.',
   '$30-45', 'walking, ghost hunt, equipment', FALSE);

-- =====================================================
-- KEY WEST, FL - Island ghost tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Key West Ghost and Mysteries Tour', 'Key West', 'FL',
   'https://keywestghostandmysteriestour.com/',
   'https://keywestghostandmysteriestour.com/',
   'Over 20 years researching Key Wests haunted history. Personal and interactive tours with guides sharing documented and personal paranormal experiences. Great historical facts plus ghostly activity.',
   '$25-35', 'walking, history', TRUE),

  ('Sloans Key West Ghost Tours / Haunted Key West', 'Key West', 'FL',
   'https://www.hauntedkeywest.com/',
   'https://www.hauntedkeywest.com/ghost-tours',
   'Only tour that lets you meet Robert the Doll, the worlds most haunted doll. Run by David L. Sloan and team. Offers VIP Fort East Martello Ghost Tour, Robert the Doll Experience, and firehouse investigations.',
   '$25-75', 'walking, Robert the Doll, investigation', TRUE),

  ('Ghosts and Gravestones Key West', 'Key West', 'FL',
   'https://www.ghostsandgravestones.com/key-west',
   'https://www.trolleytours.com/key-west/ghosts-gravestones-tour',
   'Voted Top Ten Best Ghost Tour by USA Today Readers Choice. Trolley of the Doomed experience with 17th-century grave digger guide. Includes stop at Key West Shipwreck Treasure Museum.',
   '$35-45', 'trolley, theatrical', TRUE),

  ('Key West Ghost Hunt', 'Key West', 'FL',
   'https://ghosthuntkeywest.com/',
   'https://ghosthuntkeywest.com/',
   'The original and best haunted tours in Key West with ghost hunting equipment provided. Interactive paranormal experiences exploring the Island of Bones.',
   '$30-45', 'walking, ghost hunt, equipment', FALSE),

  ('Ghost Tour Key West', 'Key West', 'FL',
   'https://www.ghostkeywest.com/',
   'https://www.ghostkeywest.com/',
   'Established tour company exploring Old Town Key West after dark. Stories of pirates, wreckers, and island spirits. Name Key West derives from cayo hueso meaning island of bones.',
   '$25-35', 'walking, history', FALSE);

-- =====================================================
-- CHICAGO, IL - Gangster history, cemetery tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Chicago Gangsters and Ghosts Tours', 'Chicago', 'IL',
   'https://gangstersandghosts.com/',
   'https://gangstersandghosts.com/',
   'Step back a century into lawless Chicago where crime syndicates fought for the Northside and Southside. Historical tour bringing ghost stories to life with gangster history from the Roaring Twenties.',
   '$25-35', 'walking, gangster, history', TRUE),

  ('American Ghost Walks - Chicago Hauntings', 'Chicago', 'IL',
   'https://www.americanghostwalks.com/chicago',
   'https://www.americanghostwalks.com/chicago',
   'Now in 24th year offering Original Chicago Hauntings Ghost Bus Tour. 3-hour luxury coach tour visiting Iroquois Theater, St. Valentines Day Massacre, Congress Plaza Hotel. Multiple bus and walking options.',
   '$34.99-89', 'bus, walking, cemetery, pub', TRUE),

  ('US Ghost Adventures', 'Chicago', 'IL',
   'https://usghostadventures.com/chicago-ghost-tour/',
   'https://usghostadventures.com/chicago-ghost-tour/',
   'Ghost tours exploring gangsters, ghouls, and haunted history. Walking tours through downtown Chicago covering speakeasies, Al Capone hangouts, and haunted landmarks.',
   '$25-35', 'walking, gangster', TRUE),

  ('Nightly Spirits', 'Chicago', 'IL',
   'https://nightlyspirits.com/chicago-ghost-tours/',
   'https://nightlyspirits.com/chicago-ghost-tours/',
   'Ghostly pub tours exploring haunted bars, alleys, and buildings. Visit Prohibition-era sites frequented by John Dillinger and Al Capone. 2.5-hour tours with drinks at each bar.',
   '$28-35', 'pub crawl, gangster', FALSE),

  ('Wateriders Ghosts and Gangsters Kayak Tour', 'Chicago', 'IL',
   'https://wateriders.com/',
   'https://wateriders.com/',
   'Unique nighttime kayak tour down the Chicago River learning about the citys Wild West days and rise of mobsters like Al Capone. Two-hour tour includes life vest, paddle, and guide.',
   '$55-75', 'kayak, river, gangster', FALSE),

  ('Chicago Crime Tours', 'Chicago', 'IL',
   'https://www.chicagocrimetours.com/',
   'https://www.chicagocrimetours.com/',
   'Bus tours focusing on Chicagos organized crime history. Visit sites connected to Al Capone, John Dillinger, and the St. Valentines Day Massacre. Historical true crime combined with ghost stories.',
   '$40-60', 'bus, crime history', FALSE);

-- =====================================================
-- NASHVILLE / FRANKLIN, TN - Civil War history tours
-- =====================================================

INSERT OR REPLACE INTO tour_operators (name, city, state, website, booking_url, description, price_range, tour_types, featured)
VALUES
  ('Franklin on Foot', 'Franklin', 'TN',
   'https://www.franklinonfoot.com/',
   'https://www.franklinonfoot.com/ghosttour',
   'Sharing local ghost stories since 2003. Haunted Franklin tour explores ghosts on brick-lined streets including Civil War spy spirits, Confederate soldiers, and departed socialites. 90-minute tours.',
   '$20-30', 'walking, Civil War, history', TRUE),

  ('Ghost City Tours - Franklin', 'Franklin', 'TN',
   'https://ghostcitytours.com/franklin/',
   'https://ghostcitytours.com/franklin/ghosts-franklin-tour/',
   'Ghosts of Franklin Tour through the heart of town where echoes of Civil War still resonate. Visit sites where thousands of soldiers died in just five hours during one of the wars bloodiest battles.',
   '$19.95-30', 'walking, Civil War, battlefield', TRUE),

  ('Amerighost Tours', 'Nashville', 'TN',
   'https://www.amerighost.com/nashville-ghost-tours',
   'https://www.amerighost.com/nashville-ghost-tours',
   'First locally owned Nashville ghost tour since 2003. Offers Haunted Downtown (lantern tour of Ryman, Capitol, Printers Alley), Haunted Tavern Tour, and Haunted Hearse Tour in 10-passenger converted hearse.',
   '$17-35', 'walking, hearse, pub crawl', TRUE),

  ('US Ghost Adventures', 'Nashville', 'TN',
   'https://usghostadventures.com/nashville-ghost-tour/',
   'https://usghostadventures.com/nashville-ghost-tour/',
   'One-hour tours covering Nashvilles Civil War haunted history. Features The Gray Man sightings at Ryman Auditorium. Buildings transformed into makeshift hospitals still harbor restless spirits.',
   '$25-30', 'walking, Civil War', FALSE),

  ('Franklin Walking Tours', 'Franklin', 'TN',
   'https://franklinwalkingtours.com/',
   'https://franklinwalkingtours.com/franklin-ghost-tours-crime-and-hauntings-told-by-franklins-top-guides/',
   'Top local tour provider for Civil War history, crime, and ghost tours. Annual Tombstone Tales in the old cemetery. Expert guides sharing Franklins dark history.',
   '$20-30', 'walking, cemetery, Civil War', FALSE),

  ('Lizzie Borden Ghost Tours - Franklin', 'Franklin', 'TN',
   'https://lizzie-borden.com/ghost-tours/franklin/',
   'https://lizzie-borden.com/ghost-tours/franklin/',
   'Haunted Franklin tour exploring how the Civil War transformed this quiet village into a city of woe. Second Battle of Franklin left 10,000 soldiers dead with buildings converted to blood-spattered hospitals.',
   '$25-35', 'walking, Civil War, history', FALSE);
