-- Seed data for Tennessee haunted places (batch 2)
-- Generated by researcher agent on 2026-01-23
-- Adds 15 new places to bring TN from 25 to 40

-- ==========================================
-- RED BOILING SPRINGS / MIDDLE TN (~3 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url, sources, source_count)
VALUES
  ('thomas-house-hotel', 'Thomas House Hotel', 'Red Boiling Springs', '520 East Main Street', 'TN', 36.5339, -85.8489, 'hotel',
   'A historic 1890 resort hotel ranked #2 on CNN''s Most Haunted Spots in America, built atop an underground spring on an ancient Native American trail.',
   'Originally built in 1890 as the Cloyd Brothers Hotel, this resort spa catered to wealthy Tennesseans drawn to Red Boiling Springs'' mineral waters — even President Woodrow Wilson visited. A fire destroyed the original in 1924, and it was rebuilt in 1927 with over fifty rooms. The hotel sits atop an underground spring and limestone, at the intersection of two creeks and a crossroad following an ancient Indian trail. Over its history, the property has witnessed three fires, numerous deaths, suspected murders, accidents, and even housed a cult. Guests and staff report doors opening and closing on their own, apparitions drifting through hallways, children''s laughter in empty rooms, and disembodied whistling. The ghost of a young girl named Sarah frequents the White Hallway and Room 37. The spirit of Mr. Cloyd wanders the halls whistling and has been captured on camera as a tall shadowy figure. Featured on Paranormal State, Portals to Hell, and Ghost Hunters.',
   1890, 'https://www.tennesseehauntedhouses.com/real-haunt/thomas-house-hotel.html',
   '["https://www.tennesseehauntedhouses.com/real-haunt/thomas-house-hotel.html","https://gatlinburghaunts.com/the-thomas-house-hotel/","https://www.onlyinyourstate.com/stays/tennessee/thomas-house-hotel-haunting-tn"]', 3),

  ('shiloh-national-military-park', 'Shiloh National Military Park', 'Shiloh', '1055 Pittsburg Landing Road', 'TN', 35.1439, -88.3306, 'battlefield',
   'Site of one of the Civil War''s bloodiest battles with over 23,000 casualties in two days, where a pond still reportedly turns red with phantom blood.',
   'The Battle of Shiloh on April 6-7, 1862 resulted in over 23,000 casualties and was one of the bloodiest engagements of the Civil War. The Shiloh National Cemetery holds over 3,500 Union soldiers and is considered the most haunted spot on the 5,000-acre park. The most famous paranormal phenomenon is Bloody Pond — during the battle, wounded soldiers from both sides crawled to this pond to drink and clean their wounds, and many died there, turning the water red. To this day, the pond is said to randomly turn a reddish hue, an eerie echo of that horrific day. Visitors report hearing phantom gunfire, drums, and anguished cries across the battlefield at dawn. Apparitions of soldiers have been seen marching in formation near the Peach Orchard, and the Hornet''s Nest area — where fighting was most intense — produces feelings of dread and unexplained cold spots.',
   1894, 'https://www.tn.gov/tourism/news/2022/10/3/experience-tennessees-ghost-stories-at-these-haunted-destinations.html',
   '["https://www.tn.gov/tourism/news/2022/10/3/experience-tennessees-ghost-stories-at-these-haunted-destinations.html","https://tnecd.com/news/7-scariest-places-in-tennessee/","https://www.tnvacation.com/trip-inspiration/articles/fright-tennessees-creepiest-haunted-locations"]', 3),

  ('cragfont', 'Cragfont', 'Castalian Springs', '200 Cragfont Road', 'TN', 36.3856, -86.2764, 'mansion',
   'A 1798 frontier mansion built by General James Winchester, one of Tennessee''s finest examples of late Georgian architecture, haunted by its builder''s ghost.',
   'Cragfont was built between 1798 and 1802 by General James Winchester, a Revolutionary War veteran and one of the founders of Memphis. The limestone mansion is considered one of the finest examples of late Georgian architecture in Tennessee. Winchester was captured during the War of 1812 at the River Raisin Massacre, where hundreds of his men were killed. He returned a broken man and died at Cragfont in 1826. His ghost is said to still walk the grounds, particularly near the family cemetery where he is buried. Visitors and staff at the historic house museum report hearing heavy boots on the wooden floors when no one else is in the building, doors that refuse to stay closed, and a tall male figure seen looking out the upstairs windows at dusk. Cold spots are common in Winchester''s former study.',
   1798, 'https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall',
   '["https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall","https://www.tennesseehauntedhouses.com/real-haunts/"]', 2),

-- ==========================================
-- KNOXVILLE / EAST TN (~2 locations)
-- ==========================================

  ('baker-peters-house', 'Baker Peters House', 'Knoxville', '9000 Kingston Pike', 'TN', 35.9345, -84.0486, 'mansion',
   'An 1840 Greek Revival antebellum home where Dr. James Baker was shot through his barricaded bedroom door by Union troops in 1863, now a restaurant haunted by his son''s ghost.',
   'Dr. James Harvey Baker, a Confederate supporter, built this two-story Greek Revival mansion in 1840 on what was then rural farmland along Kingston Pike. In June 1863, raiding Union troops marched down Kingston Pike and entered the home, mortally wounding Dr. Baker by shooting through the barricaded door of his bedroom — the bullet-scarred door remains in the building today. His son Abner, a Confederate soldier, returned in 1865 and shot a man named William Hall in downtown Knoxville. An angry mob of Unionists overran the jail that night, dragged Abner outside, and hanged him from a tree. These violent deaths left an indelible mark. Staff and visitors report seeing Abner''s apparition leaning on the staircase railing and in upstairs windows. A cold hand grabs shoulders from behind, glasses fall from shelves, lights switch on and off, objects move, and whispered voices echo through empty rooms. The basement, which once served as slave quarters, produces particularly intense feelings of unease.',
   1840, 'https://kprcrew.com/portfolio/history-of-the-baker-peters-house-in-knoxville-tn/',
   '["https://kprcrew.com/portfolio/history-of-the-baker-peters-house-in-knoxville-tn/","https://www.tennesseehauntedhouses.com/real-haunt/baker-peters-mansion.html","https://gatlinburghaunts.com/haunted-history-of-the-baker-peters-house-in-knoxville-tn/"]', 3),

  ('mabry-hazen-house', 'Mabry-Hazen House', 'Knoxville', '1711 Dandridge Avenue', 'TN', 35.9706, -83.8931, 'mansion',
   'An 1858 hilltop mansion that served as headquarters for both Confederate and Union forces during the Civil War, with three generations of the family buried on the grounds.',
   'Perched on Mabry''s Hill overlooking downtown Knoxville, this Italianate mansion was built in 1858 by Joseph Alexander Mabry Jr. The house''s strategic hilltop position made it valuable during the Civil War — it served as headquarters for both Confederate and Union forces at different points during the conflict. Three generations of the Mabry-Hazen family lived and died in the house, and many are buried in the family cemetery on the grounds. Joseph Mabry and his son were both killed in a downtown Knoxville shootout in 1882. The museum staff report hearing footsteps on the upper floors when the building is empty, and visitors have photographed unexplained mists and orbs near the family cemetery. The rocking chair in the parlor has been observed moving on its own, and the smell of pipe tobacco occasionally wafts through the hallways.',
   1858, 'https://www.visitknoxville.com/blog/post/haunted-places-in-knoxville/',
   '["https://www.visitknoxville.com/blog/post/haunted-places-in-knoxville/","https://www.tennesseehauntedhouses.com/real-haunts/"]', 2),

-- ==========================================
-- CHATTANOOGA AREA (~2 locations)
-- ==========================================

  ('hales-bar-dam', 'Hales Bar Dam', 'Guild', '1265 Hales Bar Road', 'TN', 35.0572, -85.5356, 'other',
   'A cursed 1913 hydroelectric dam on the Tennessee River, built on sacred Native American land, plagued by construction deaths and now one of Tennessee''s most haunted sites.',
   'Construction began in 1905 on what would become one of America''s first major multipurpose dams. Legend holds that War Chief Dragging Canoe cursed this sacred land during the 1775 Treaty of Sycamore Shoals. The curse seemed to manifest immediately — a boiler explosion killed one worker, a falling derrick crushed two others, drownings occurred, and murders plagued the construction camps. The dam leaked from the day it opened in 1913 despite two decades of repair attempts by the TVA, leading to its replacement by Nickajack Dam in 1967. The abandoned powerhouse is now considered one of Tennessee''s most haunted locations. Shadow figures move through the tunnels, and investigators have documented apparitions of former construction workers. The second floor is notorious for encounters with the ghost of a young woman who met a violent end. Children''s spirits are connected to a tragic tunnel flooding incident. Featured on Ghost Adventures and Ghost Hunters.',
   1913, 'https://www.hauntedrooms.com/tennessee/haunted-places/hales-bar-dam',
   '["https://www.hauntedrooms.com/tennessee/haunted-places/hales-bar-dam","https://www.chattanoogan.com/2020/10/23/416850/Jerry-Summers-Hales-Bar-Ghost.aspx","https://kprcrew.com/portfolio/history-of-hales-bar-dam/"]', 3),

  ('lookout-mountain-battlefield', 'Lookout Mountain Battlefield', 'Chattanooga', '110 Point Park Road', 'TN', 35.0094, -85.3428, 'battlefield',
   'Site of the 1863 Battle Above the Clouds during the Civil War, where phantom soldiers are seen marching through fog on the mountainside.',
   'On November 24, 1863, Union forces under General Joseph Hooker attacked Confederate positions on Lookout Mountain in what became known as the Battle Above the Clouds — so named because low-hanging clouds obscured the fighting from observers below. The battle was part of the larger Chattanooga Campaign that broke the Confederate siege of the city. Hundreds of soldiers died on the mountain''s steep slopes. Visitors to Point Park and the surrounding trails report seeing ghostly soldiers marching through the fog, particularly on misty autumn mornings that mirror the conditions of the original battle. The sound of distant musket fire and shouted commands echo across the bluffs. Near Cravens House, which served as a field hospital, visitors have reported the smell of blood and antiseptic, and shadow figures are seen in the windows at twilight.',
   1863, 'https://www.visitchattanooga.com/blog/post/off-the-haunted-path-spooky-adventures-for-october/',
   '["https://www.visitchattanooga.com/blog/post/off-the-haunted-path-spooky-adventures-for-october/","https://tnecd.com/news/7-scariest-places-in-tennessee/"]', 2),

-- ==========================================
-- NASHVILLE AREA (~3 locations)
-- ==========================================

  ('tennessee-state-prison', 'Tennessee State Prison', 'Nashville', '7475 Cockrill Bend Boulevard', 'TN', 36.2000, -86.8778, 'prison',
   'A castle-like Gothic prison built in 1898, operational for nearly 100 years housing Tennessee''s most dangerous criminals, with reports of screams echoing through empty cell blocks.',
   'Built in 1898, the Tennessee State Prison''s imposing Gothic architecture — with its castle-like turrets and massive stone walls — housed some of the state''s most dangerous criminals for nearly 100 years. The prison witnessed riots, executions, and countless violent deaths within its walls before closing in 1992. During its operation, inmates endured brutal conditions including overcrowding, minimal sanitation, and violence. Since its closure, the abandoned prison has become one of Nashville''s most notorious haunted locations. Visitors on paranormal tours report hearing the sounds of cell bars clunking shut, blood-curdling screams echoing through empty corridors, and heavy footsteps pacing in vacant cell blocks. Shadow figures have been seen in the guard towers, and the execution chamber produces intense feelings of dread. The prison has been used as a filming location for movies including The Green Mile and Walk the Line.',
   1898, 'https://www.tn.gov/tourism/news/2022/10/3/experience-tennessees-ghost-stories-at-these-haunted-destinations.html',
   '["https://www.tn.gov/tourism/news/2022/10/3/experience-tennessees-ghost-stories-at-these-haunted-destinations.html","https://www.tnvacation.com/trip-inspiration/articles/fright-tennessees-creepiest-haunted-locations"]', 2),

  ('fort-negley', 'Fort Negley', 'Nashville', '1100 Fort Negley Boulevard', 'TN', 36.1392, -86.7767, 'battlefield',
   'The largest inland stone fortification built during the Civil War, constructed by Union forces using conscripted labor including freed slaves, many of whom died during construction.',
   'Fort Negley was built in 1862 by Union forces occupying Nashville, making it the largest inland stone fortification constructed during the Civil War. The fort was built using conscripted labor — roughly 2,800 men, including freed and escaped slaves, prisoners of war, and poor white laborers. Conditions were brutal: inadequate food, clothing, and shelter combined with back-breaking quarry work led to hundreds of deaths. Many workers were buried in unmarked graves on the hillside surrounding the fort. The site sat abandoned for decades before becoming a city park. Visitors report seeing shadowy figures of laborers carrying stones on the hillside paths, particularly at dusk. The sound of picks striking rock echoes from the old quarry area when no one is present. Cold spots are frequent near the unmarked burial areas, and some visitors report an overwhelming sense of sorrow near the fort''s foundation walls.',
   1862, 'https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall',
   '["https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall","https://www.tennesseehauntedhouses.com/real-haunts/"]', 2),

  ('two-rivers-mansion', 'Two Rivers Mansion', 'Nashville', '3130 McGavock Pike', 'TN', 36.1967, -86.6556, 'mansion',
   'An 1859 Italianate mansion built for the McGavock family, survivors of the nearby Battle of Stones River, where ghostly music plays from the empty ballroom.',
   'David McGavock built Two Rivers Mansion in 1859, combining Italianate architecture with the grandeur of the antebellum South. The McGavock family endured the Civil War on their property — the nearby Battle of Stones River in 1862-63 left thousands dead within earshot of the mansion. Family members helped tend to wounded soldiers from both sides. After the war, the mansion became known for its lavish parties and musical entertainment in the grand ballroom. Today, staff and visitors report hearing phantom piano music emanating from the empty ballroom, particularly in the evening hours. A woman in a Civil War-era dress has been seen looking out the second-floor windows. Doors throughout the mansion open and close on their own, and footsteps are heard on the grand staircase when the building is unoccupied.',
   1859, 'https://www.tennesseehauntedhouses.com/real-haunts/',
   '["https://www.tennesseehauntedhouses.com/real-haunts/","https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall"]', 2),

-- ==========================================
-- GATLINBURG / SMOKY MOUNTAINS (~3 locations)
-- ==========================================

  ('greenbrier-restaurant', 'The Greenbrier Restaurant', 'Gatlinburg', '370 Newman Road', 'TN', 35.7264, -83.5117, 'restaurant',
   'A rustic mountain restaurant haunted by the ghost of Lydia, a young woman who hanged herself after being jilted at the altar in 1939.',
   'The Greenbrier Restaurant is one of the most famous haunted locations in Gatlinburg, housed in a rustic building surrounded by the Smoky Mountains. The ghost story centers on Lydia, a young woman who was left at the altar by her fiance in 1939. Devastated by the public humiliation, Lydia hanged herself in the building. Her fiance''s body was later found mangled nearby by what appeared to be a mountain cat — locals whispered it was Lydia''s revenge from beyond the grave. Staff and diners have reported seeing Lydia''s apparition in the dining room, particularly near the spot where she died. Tables are found rearranged after closing, glasses slide across the bar, and a woman''s sobbing has been heard in the upper floors late at night. The temperature drops noticeably near the back staircase, even in summer.',
   1939, 'https://www.cabinsusa.com/smoky-mountains-blog/post/17/top-10-haunted-places-in-the-smoky-mountains.php',
   '["https://www.cabinsusa.com/smoky-mountains-blog/post/17/top-10-haunted-places-in-the-smoky-mountains.php","https://www.gatlinburg.com/blog/post/ghosts-of-gatlinburg-10-haunted-places-to-visit-this-fall/","https://gatlinburghaunts.com/top-10-most-haunted-places-in-gatlinburg/"]', 3),

  ('white-oak-flats-cemetery', 'White Oak Flats Cemetery', 'Gatlinburg', '539 Historic Nature Trail', 'TN', 35.7128, -83.5128, 'cemetery',
   'One of Tennessee''s oldest cemeteries established in 1830, the original burial ground for Gatlinburg''s pioneer settlers, with reports of voices and apparitions among the weathered stones.',
   'Established in 1830, White Oak Flats Cemetery is one of the oldest burial grounds in Tennessee and served as the primary cemetery for Gatlinburg''s earliest settlers. The cemetery sits on a small hill in the heart of downtown Gatlinburg, surrounded by the tourist district — a jarring juxtaposition of the modern and the ancient. Many of the headstones are so weathered they are no longer legible, and several unmarked graves dot the hillside. Visitors have reported hearing whispered voices near the older graves, especially after dark. Apparitions of figures in pioneer-era clothing have been seen walking between the headstones. Photography taken at the cemetery frequently captures unexplained light anomalies and mists. Local ghost tour guides consider it one of the most reliably active paranormal sites in the Smoky Mountains.',
   1830, 'https://www.gatlinburg.com/blog/post/ghosts-of-gatlinburg-10-haunted-places-to-visit-this-fall/',
   '["https://www.gatlinburg.com/blog/post/ghosts-of-gatlinburg-10-haunted-places-to-visit-this-fall/","https://gatlinburghaunts.com/top-10-most-haunted-places-in-gatlinburg/"]', 2),

  ('elkmont-ghost-town', 'Elkmont Ghost Town', 'Gatlinburg', 'Elkmont Road', 'TN', 35.6528, -83.5822, 'other',
   'An abandoned early 1900s logging town inside Great Smoky Mountains National Park, where empty cottages and a crumbling hotel harbor restless spirits of former residents.',
   'Elkmont was once a thriving logging community in the early 1900s that later became a summer resort for Knoxville''s elite. When Great Smoky Mountains National Park was established in 1934, residents were given lifetime leases that gradually expired. By the early 2000s, the last residents had left, and the town''s cottages, clubhouses, and hotel fell into ruin. The Wonderland Hotel, the community''s centerpiece, partially collapsed before being demolished. Walking through Elkmont''s abandoned streets, visitors report hearing laughter, music, and conversation from the empty cottages — echoes of the resort''s lively past. Apparitions have been seen on the porches of the remaining structures, and some hikers have reported encountering a well-dressed couple on the road who vanish when approached. The site is particularly active on summer evenings, when the town would have been full of vacationers.',
   1908, 'https://www.cabinsusa.com/smoky-mountains-blog/post/17/top-10-haunted-places-in-the-smoky-mountains.php',
   '["https://www.cabinsusa.com/smoky-mountains-blog/post/17/top-10-haunted-places-in-the-smoky-mountains.php","https://www.pigeonforge.com/smoky-mountain-legends/"]', 2),

-- ==========================================
-- EAST TN / JONESBOROUGH / GALLATIN (~2 locations)
-- ==========================================

  ('chester-inn', 'Chester Inn', 'Jonesborough', '116 West Main Street', 'TN', 36.2942, -82.4733, 'hotel',
   'Tennessee''s oldest town features this 1797 inn where Presidents Jackson, Polk, and Johnson all stayed — and where giggling phantom women are heard by male guests at night.',
   'The Chester Inn was built in 1797 in Jonesborough, Tennessee''s oldest town (founded 1779). The inn hosted three future presidents: Andrew Jackson, James K. Polk, and Andrew Johnson, as well as countless travelers on the Great Stage Road connecting Virginia to Tennessee. Named a Travel Channel Top Ten Haunted Town in America, Jonesborough''s ghost stories center on this historic inn. Male visitors sleeping in the inn have reported hearing giggling women in the late hours of the night, particularly when a train passes by — female guests never hear the laughter. The phantom women are rumored to be spirits of ''ladies of ill-repute'' who once entertained travelers at the establishment. Staff have also reported doors opening on their own, unexplained footsteps in the hallways, and cold spots in the upstairs guest rooms.',
   1797, 'https://jonesborough.com/31118-2/',
   '["https://jonesborough.com/31118-2/","https://www.tn.gov/tourism/news/2022/10/3/experience-tennessees-ghost-stories-at-these-haunted-destinations.html"]', 2),

  ('gallatin-town-square', 'Gallatin Town Square', 'Gallatin', '118 West Main Street', 'TN', 36.3883, -86.4467, 'other',
   'Called the Most Haunted Public Square in America, this historic downtown district hosts documented paranormal activity in multiple buildings dating to the early 1800s.',
   'Downtown Gallatin''s public square has earned the reputation as the Most Haunted Public Square in America, with multiple buildings around the square reporting paranormal activity. The town was founded in 1802 and served as an important stop between Nashville and Kentucky. During the Civil War, Gallatin was occupied by both sides and witnessed skirmishes that left soldiers dead in the streets. The square''s historic buildings — many dating to the early 1800s — harbor spirits from two centuries of commerce, conflict, and tragedy. Business owners report merchandise falling from shelves, unexplained footsteps in upstairs offices after hours, and shadow figures moving past windows of closed shops. The Gallatin Ghost Walks, held on weekends in October, take visitors through and around the square, sharing the documented encounters that earned this distinction.',
   1802, 'https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall',
   '["https://www.tnvacation.com/articles/meet-tennessees-ghosts-fall","https://www.tn.gov/tourism/news/2022/10/3/experience-tennessees-ghost-stories-at-these-haunted-destinations.html"]', 2);
