-- Seed data for South Carolina haunted places (batch 2)
-- Generated by researcher agent on 2026-01-23
-- Adds 13 new places to bring SC from 27 to 40

-- ==========================================
-- GEORGETOWN (~3 locations)
-- ==========================================

INSERT OR REPLACE INTO places (slug, name, city, address, state, latitude, longitude, category, description, ghost_story, year_established, source_url, sources, source_count)
VALUES
  ('kaminski-house-museum', 'Kaminski House Museum', 'Georgetown', '1003 Front Street', 'SC', 33.3716, -79.2847, 'mansion',
   'A 1769 Georgian mansion overlooking the Sampit River, built by the wealthiest merchant in Georgetown, haunted by a heartbroken woman and a grieving orphan boy.',
   'Built in 1769 by Paul Trapier, dubbed "The King of Georgetown" for his vast wealth, this Georgian-style home overlooks the Sampit River in Georgetown''s historic district. The house passed through many hands before being purchased by Harold and Julia Kaminski in 1931. Two distinct ghost stories haunt the property. The first involves an 8-year-old boy left in the care of the owners while his family sailed abroad — the family was lost at sea, and the young boy died of grief inside the home. His small spirit still appears on occasion. The second story centers on a young woman who fell in love with a sea captain who brought her a bottle of exotic perfume. When she saw him leave a tavern with another woman, heartbroken, she poisoned herself by drinking the perfume. Her spirit has been spotted watching from the window on summer nights, and the scent of perfume sometimes wafts through empty rooms.',
   1769, 'https://www.southcarolinahauntedhouses.com/real-haunt/watermankaminski-house.html',
   '["https://www.southcarolinahauntedhouses.com/real-haunt/watermankaminski-house.html","https://www.southernspiritguide.org/ghosts-of-georgetown-south-carolina/","https://www.hauntedplaces.org/georgetown-sc/"]', 3),

  ('georgetown-lighthouse', 'Georgetown Lighthouse', 'Georgetown', 'North Island', 'SC', 33.2242, -79.1833, 'other',
   'An 1811 lighthouse on remote North Island, one of the oldest light stations in South Carolina, haunted by a keeper killed during its reconstruction after the Civil War.',
   'The Georgetown Lighthouse has been guiding ships into Winyah Bay since 1811, making it one of the oldest light stations in South Carolina. The original tower was destroyed during the Civil War, and the current 87-foot structure was built in 1869. During construction of the replacement lighthouse, a keeper was killed in an accident. His ghost is said to haunt the tower, with lighthouse visitors reporting footsteps on the iron spiral staircase when no one else is present. The lantern room occasionally glows with an unexplained light even though the original lamp was removed decades ago. Located on remote North Island, accessible only by boat, the isolation adds to the eerie atmosphere. Fishermen passing at night have reported seeing a figure in the tower window and hearing distant shouts carried across the water.',
   1811, 'https://discoversouthcarolina.com/articles/hunting-for-ghosts-in-georgetown',
   '["https://discoversouthcarolina.com/articles/hunting-for-ghosts-in-georgetown","https://www.hauntedplaces.org/georgetown-sc/"]', 2),

  ('the-hermitage-alice-flagg', 'The Hermitage', 'Murrells Inlet', '683 Hermitage Drive', 'SC', 33.5483, -79.0494, 'mansion',
   'A plantation home where young Alice Flagg died of heartbreak in 1849 after her brother forbade her love affair, her ghost still wanders in a white dress seeking her lost engagement ring.',
   'The Hermitage plantation near Murrells Inlet was home to the wealthy Flagg family in the mid-1800s. Young Alice Flagg fell deeply in love with a turpentine merchant — a man her physician brother Dr. Allard Flagg considered beneath the family''s station. When Dr. Flagg discovered Alice wearing the man''s engagement ring on a chain around her neck, he tore it away and sent her back to boarding school in Charleston. Alice fell gravely ill with malaria and was brought home, but died in 1849 at just 16 years old, never recovering her ring. Her ghost, dressed in a flowing white gown, has been seen wandering the grounds of The Hermitage and nearby All Saints Cemetery, eternally searching for her lost ring. Visitors to her grave leave rings on her headstone, and those who walk around it 13 times counter-clockwise at midnight reportedly encounter her spirit.',
   1840, 'https://usghostadventures.com/haunted-stories/haunted-south-carolina-are-you-afraid-of-the-dark/',
   '["https://usghostadventures.com/haunted-stories/haunted-south-carolina-are-you-afraid-of-the-dark/","https://discoversouthcarolina.com/articles/hunting-for-ghosts-in-georgetown","https://www.hauntedrooms.com/south-carolina/haunted-places"]', 3),

-- ==========================================
-- GREENVILLE / SPARTANBURG (~5 locations)
-- ==========================================

  ('westin-poinsett-hotel', 'Westin Poinsett Hotel', 'Greenville', '120 South Main Street', 'SC', 34.8510, -82.4001, 'hotel',
   'A grand 1925 hotel in downtown Greenville where guests report unexplained knocks in empty hallways and encounters with the ghost of an elderly man who appears in their rooms.',
   'The Westin Poinsett Hotel opened in 1925 as one of the finest hotels in the upstate, a 12-story landmark in the heart of downtown Greenville. Named for Joel Poinsett, the South Carolina statesman who introduced the poinsettia to America, the hotel has hosted countless guests over its century of operation. Guests report hearing knocks and noises in empty hallways, particularly on the upper floors late at night. Multiple guests have reported waking to find the apparition of an elderly man standing in their room, watching them before fading away. The identity of the ghost is unknown, though some speculate it may be a former long-term resident who died in the hotel. Staff have reported elevators stopping at floors where no one called them, and housekeeping has found rooms disturbed after being cleaned when no guests had access.',
   1925, 'https://kiddingaroundgreenville.com/haunted-places-in-the-upstate',
   '["https://kiddingaroundgreenville.com/haunted-places-in-the-upstate","https://sctravelguide.com/2018/06/11/haunted-places-in-upstate-sc/"]', 2),

  ('springwood-cemetery', 'Springwood Cemetery', 'Greenville', '1000 East Washington Street', 'SC', 34.8517, -82.3847, 'cemetery',
   'A historic downtown Greenville cemetery haunted by Fannie Heldmann, who drowned herself in the Reedy River in 1889 to escape an arranged marriage.',
   'Springwood Cemetery is the oldest and largest public cemetery in Greenville, established in the 1820s and containing the remains of many of the city''s most prominent citizens. The cemetery''s most famous ghost is Fannie Heldmann, whose father insisted she marry his business partner. Fannie was repulsed by the arrangement and reportedly went insane planning the unwanted wedding. In 1889, she drowned herself in the Reedy River rather than go through with the marriage. Her spirit is said to haunt both the cemetery where she is buried and the banks of the Reedy River nearby. Visitors have reported seeing a young woman in Victorian-era clothing walking among the older graves at twilight, and some have heard crying near her headstone. The cemetery is also known for unexplained cold spots and the feeling of being followed along its winding paths.',
   1829, 'https://livingupstatesc.com/the-spooky-and-supernatural-of-upstate-south-carolina/',
   '["https://livingupstatesc.com/the-spooky-and-supernatural-of-upstate-south-carolina/","https://gvltoday.6amcity.com/scary-stories-greenville-sc"]', 2),

  ('greenville-tb-hospital', 'Greenville Tuberculosis Hospital', 'Greenville', '400 Herdklotz Park Drive', 'SC', 34.8683, -82.3739, 'hospital',
   'The ruins of a former tuberculosis hospital and asylum in Greenville, where shadow figures still wander the grounds and screams echo from the destroyed building.',
   'The Greenville Tuberculosis Hospital began treating TB patients in the early 1900s but later also served as an insane asylum and prisoner release facility. The combination of suffering, death, and institutionalization left a dark mark on the property. Though the main hospital building burned down years ago, the grounds — now Herdklotz Park — remain one of the most investigated paranormal sites in upstate South Carolina. Strange sounds including banging, screaming, and the clanging of bells have been heard and even recorded by paranormal teams. Shadow figures are seen wandering the park area, particularly near where the hospital once stood. Visitors report an overwhelming sense of dread near the old building foundations, and electronic equipment frequently malfunctions on the grounds.',
   1910, 'https://kiddingaroundgreenville.com/haunted-places-in-the-upstate',
   '["https://kiddingaroundgreenville.com/haunted-places-in-the-upstate","https://sctravelguide.com/2018/06/11/haunted-places-in-upstate-sc/"]', 2),

  ('oakwood-cemetery-spartanburg', 'Oakwood Cemetery', 'Spartanburg', '800 North Church Street', 'SC', 34.9567, -81.9283, 'cemetery',
   'Known locally as Hell''s Gate, this Spartanburg cemetery is haunted by the Lady in White — a young bride who died on her wedding day and was buried in her wedding dress.',
   'Oakwood Cemetery in Spartanburg, considered one of the most actively haunted places in South Carolina, has earned the nickname Hell''s Gate among locals. The cemetery''s most famous spirit is the Lady in White — a young woman who died on her wedding day and was buried in her wedding dress. Her ghostly figure has been seen walking among the graves in a flowing white gown, particularly on moonlit nights. Paranormal investigators report an unusually high concentration of activity: cold spots appear without explanation, camera and phone batteries drain rapidly, and children''s laughter echoes from sections where young ones are buried. Visitors have photographed plumes of unexplained smoke and fog, and many report the intense feeling of being watched. A young boy''s voice has been heard asking to be played with near the children''s section.',
   1870, 'https://www.southcarolinahauntedhouses.com/real-haunts/',
   '["https://www.southcarolinahauntedhouses.com/real-haunts/","https://livingupstatesc.com/the-spooky-and-supernatural-of-upstate-south-carolina/","https://sctravelguide.com/2018/06/11/haunted-places-in-upstate-sc/"]', 3),

  ('fosters-tavern-spartanburg', 'Foster''s Tavern', 'Spartanburg', '295 East Main Street', 'SC', 34.9499, -81.9208, 'restaurant',
   'A historic Spartanburg landmark where phantom footsteps echo from empty staircases and the sound of ghostly horses pound on the roof.',
   'Foster''s Tavern is one of Spartanburg''s oldest and most historic landmarks, serving the community since the early days of the city. The tavern has long been known for its paranormal activity, which staff and patrons have reported for generations. Footsteps are heard on empty staircases throughout the building, particularly after closing time. Most bizarrely, the sound of horses galloping across the roof has been reported by multiple witnesses — a phenomenon that has never been explained. Some speculate the horse sounds are connected to the building''s history as a coach stop, where horses and riders were a constant presence. Doors open and close without explanation, and staff have reported feeling cold breath on their necks while working alone in the kitchen. The building''s age and connection to colonial-era travel routes contribute to its haunted reputation.',
   1807, 'https://livingupstatesc.com/the-spooky-and-supernatural-of-upstate-south-carolina/',
   '["https://livingupstatesc.com/the-spooky-and-supernatural-of-upstate-south-carolina/","https://www.southcarolinahauntedhouses.com/real-haunts/"]', 2),

-- ==========================================
-- AIKEN AREA (~2 locations)
-- ==========================================

  ('hotel-aiken', 'Hotel Aiken', 'Aiken', '235 Richland Avenue West', 'SC', 33.5604, -81.7217, 'hotel',
   'An 1898 hotel where Room 302 is haunted by a suicide victim, a stooped old woman appears to guests, and a ghostly prankster moves housekeeping carts and hides cell phones.',
   'Built in 1898, Hotel Aiken is one of the most actively haunted hotels in South Carolina. Room 302 is the epicenter of activity — a man committed suicide by leaping from the window, and guests have since reported seeing the ghost of a stooped-over old woman in the room. The second floor is particularly active: in Room 207, a door opened by itself at 5 AM followed by voices and a baby crying, despite no guests being on that floor. Housekeepers working the second floor hear whispers from empty rooms and find their carts mysteriously moved. One guest reported their cell phone being repeatedly hidden in different spots around the room. Between 1 and 2 AM, guests have heard an old-fashioned phone ringing faintly despite no phone being in the room, along with faint music box melodies and muffled conversation. Shadow figures have been seen flitting past in the hallways.',
   1898, 'https://www.southcarolinahauntedhouses.com/real-haunt/holley-house--hotel-aiken.html',
   '["https://www.southcarolinahauntedhouses.com/real-haunt/holley-house--hotel-aiken.html","https://www.hauntedplaces.org/aiken-sc/","https://kicks99.com/2023/09/13/the-spooky-ghosts-of-aiken-south-carolina/"]', 3),

  ('graniteville-cemetery', 'Graniteville Cemetery', 'Graniteville', 'Canal Street', 'SC', 33.5639, -81.8089, 'cemetery',
   'A 19th-century mill town cemetery near Aiken where a witch ghost places flowers on children''s graves and screams echo from unmarked burial sites on full-moon nights.',
   'Graniteville Cemetery serves the historic textile mill town founded in 1845 by William Gregg, one of the first planned industrial communities in the South. The cemetery contains the remains of generations of mill workers, many of whom died young from the harsh working conditions of 19th-century textile manufacturing. Late at night, visitors have reported sightings of a spectral woman — described as a witch ghost — who walks through the cemetery placing flowers on children''s graves. The back section of the cemetery, where unmarked graves are located, is particularly active: screams, gunshots, and laughter can all be heard on cold full-moon nights. The area''s tragic history includes not just industrial deaths but also the devastating 2005 train derailment that released toxic chlorine gas and killed 9 people near the cemetery, potentially adding more restless spirits to an already haunted ground.',
   1845, 'https://www.scprai.org/hauntingsa_g.html',
   '["https://www.scprai.org/hauntingsa_g.html","https://www.hauntedplaces.org/haunted-places-in-aiken-county-south-carolina/"]', 2),

-- ==========================================
-- CAMDEN / SUMMERVILLE (~3 locations)
-- ==========================================

  ('quaker-cemetery-camden', 'Old Quaker Cemetery', 'Camden', 'Campbell Street', 'SC', 34.2464, -80.6072, 'cemetery',
   'South Carolina''s oldest inland city features this colonial-era burial ground where the ghost of a Revolutionary War camp follower still searches for her British soldier lover.',
   'Camden, founded in 1732, is the oldest inland city in South Carolina and saw significant action during the Revolutionary War. The Old Quaker Cemetery, also known as the Camden Presbyterian Cemetery, dates to the colonial period. According to local tradition, a woman followed her lover in the British Army during the Revolution, searching through the wilderness to Camden. She died before finding him and was buried under cover of darkness by King Haigler''s men — an American Catawba Indian chief who befriended European settlers. Her ghost can be seen walking the streets and roads in and near Camden, still searching for her lost soldier. The cemetery itself, with its weathered colonial-era headstones, produces feelings of unease after dark. Visitors have reported seeing a woman in period dress walking between the graves and along nearby streets, vanishing when approached.',
   1750, 'https://www.hauntedplaces.org/camden-sc/',
   '["https://www.hauntedplaces.org/camden-sc/","https://quartermasterproperties.com/real-haunted-places-in-south-carolina/"]', 2),

  ('summerville-light', 'Summerville Light', 'Summerville', 'Old Trolley Road', 'SC', 33.0183, -80.1756, 'other',
   'A mysterious floating light hovering over abandoned railroad tracks, believed to be the ghost of a woman searching for her decapitated husband with a phantom lantern.',
   'On the old railroad tracks near Summerville, a mysterious floating light has been reported for over a century. Legend holds that a railroad worker was decapitated in a train accident, and his wife took a lantern to the tracks each night searching for his body. She eventually died of grief, but her phantom lantern still bobs along the tracks on dark nights. The light appears as a warm, yellowish glow that moves slowly above the rail bed, sometimes approaching witnesses before vanishing. USGS seismologist Susan Hough has offered a scientific explanation — suggesting the lights may be caused by earthquake activity, as many sightings coincide with periods of seismic stress in the region. However, locals insist the phenomenon is clearly supernatural, as the light sometimes responds to observers, approaching when called to and retreating when chased.',
   1900, 'https://www.smithsonianmag.com/smart-news/the-ghost-haunting-this-south-carolina-town-might-have-an-earthly-explanation-scientist-says-180985975/',
   '["https://www.smithsonianmag.com/smart-news/the-ghost-haunting-this-south-carolina-town-might-have-an-earthly-explanation-scientist-says-180985975/","https://www.southcarolinahauntedhouses.com/real-haunts/"]', 2),

  ('hobkirk-hill-battlefield', 'Hobkirk Hill Battlefield', 'Camden', 'Broad Street', 'SC', 34.2606, -80.6078, 'battlefield',
   'Site of the 1781 Battle of Hobkirk''s Hill during the Revolutionary War, where phantom soldiers march through the pines and the clash of muskets echoes at dawn.',
   'On April 25, 1781, British forces under Lord Rawdon surprised American troops under General Nathanael Greene on Hobkirk''s Hill just outside Camden. The battle resulted in an American retreat with significant casualties on both sides. The hillside battlefield, now partially covered by residential development, retains pockets of undisturbed ground where soldiers fell. Residents living near the battlefield report hearing the sound of musket fire and shouted commands at dawn, particularly in April near the anniversary of the battle. Phantom soldiers in Revolutionary War-era uniforms have been seen marching through the pine trees along the old battle lines. The area around the historical marker on Broad Street is known for unexplained cold spots and a heavy feeling of dread. Camden''s role as a major British military post during the war — with two major battles and the execution of numerous patriots — contributes to the area''s overall haunted reputation.',
   1781, 'https://www.hauntedplaces.org/camden-sc/',
   '["https://www.hauntedplaces.org/camden-sc/","https://quartermasterproperties.com/real-haunted-places-in-south-carolina/"]', 2);
