-- New York Batch 2: 8 new places to reach 40 total
-- Sources: Haunted History Trail of NY, hauntedplaces.org, hauntedrooms.com, hvmag.com, visitbinghamton.org, ghostquest.net

INSERT OR REPLACE INTO places (slug, name, city, state, latitude, longitude, category, year_established, ghost_story, source_count) VALUES
('durand-eastman-park', 'Durand Eastman Park', 'Rochester', 'NY', 43.2364, -77.5556, 'park', 1907, 'For decades, a spectral woman in white has been spotted along the dark roadways of Durand Eastman Park near Lake Ontario. Known as the White Lady, she is believed to be the ghost of a mother whose daughter was murdered by her boyfriend and thrown into one of the park''s lakes. The grieving mother searched the shores for her daughter''s body before taking her own life, and now she walks the lakefront paths accompanied by two ghostly white dogs. She appears on foggy nights, approaching male visitors with hostility—police officers have reported unexplainable encounters while patrolling the park after dark.', 3),

('belhurst-castle', 'Belhurst Castle', 'Geneva', 'NY', 42.8584, -76.9861, 'hotel', 1889, 'Belhurst Castle, built on the shores of Seneca Lake between 1885 and 1889, is haunted by Isabella, a beautiful opera singer who fled to America from Spain with her forbidden lover. They built a secret tunnel beneath the estate to escape if authorities came, but when police finally arrived, the tunnel collapsed as the couple tried to flee—burying Isabella alive. Her ghost, the White Lady of Belhurst, is now seen walking the shores of Seneca Lake in a flowing white gown. Inside the castle, showers turn on by themselves in guest rooms, bottles and glasses fly across the bar, and tablecloths are found mysteriously knotted around chandeliers. USA Today ranked Belhurst among the most haunted hotels in the country.', 3),

('historic-huguenot-street', 'Historic Huguenot Street', 'New Paltz', 'NY', 41.7517, -74.0866, 'historical', 1678, 'The oldest continuously inhabited street in America, Historic Huguenot Street spans seven stone houses built by French Huguenot settlers in the 1700s—each with its own resident ghost. In the Freer House, Ms. Annie DuBois threw herself down a well in her white gown upon hearing her young lover had died, and visitors still see her sobbing at the well''s edge. In the Abraham Hasbrouck House, a child''s bones were discovered in the basement after a clairvoyant resident described visions of a buried child—the remains crumbled before they could be identified. Howard Grimm, an 82-year-old board member murdered by an axe-wielding intruder in 1970, walks the street at night. Ghost lights are left burning in every house to keep the friendly spirits company.', 3),

('phelps-mansion', 'Phelps Mansion', 'Binghamton', 'NY', 42.0975, -75.9110, 'mansion', 1870, 'Built in 1870 for Sherman D. Phelps, the fifth mayor of Binghamton, the Phelps Mansion carries a dark curse—every family member who lived in the house died within twelve years of moving in. Today, visitors witness apparitions wearing period-appropriate clothing drifting through the halls. A grandfather clock that has never been wound chimes at random hours, doors swing open and slam shut on their own, and the heavy sensation of invisible figures passing through rooms stops visitors in their tracks. Candlelight tours held each October often produce new encounters, with guests reporting cold touches and whispered voices in the darkened Victorian rooms.', 2),

('lily-dale-assembly', 'Lily Dale Assembly', 'Lily Dale', 'NY', 42.3519, -79.3279, 'landmark', 1879, 'Lily Dale, a gated spiritualist community of 275 residents founded in 1879, is the only town in America where registered mediums outnumber regular citizens. At the end of a wooded trail in Leolyn Woods stands Inspiration Stump, a sacred monument where mediums channel the dead during twice-daily summer ceremonies—paranormal investigators consider it a spiritual vortex where the barrier between worlds is thinnest. In the Assembly Hall, a bearded man in Victorian-era glasses materializes during sessions, watched by visitors who feel sudden cold spots wrap around them. The community''s connection to the Fox Sisters, founders of American spiritualism, deepens its reputation as a place where the living and dead coexist.', 3),

('hudson-river-state-hospital', 'Hudson River State Hospital', 'Poughkeepsie', 'NY', 41.6891, -73.8955, 'hospital', 1873, 'The Hudson River State Hospital, built in 1873 as a High Victorian Gothic psychiatric complex designed by Frederick Clarke Withers, housed thousands of patients for over a century before closing in 2003. The massive building fell into ruin after abandonment, and a 2007 lightning strike set fire to several wings. Staff who worked the night shift during the hospital''s final decades reported hearing tortured cries echoing through empty wards, wheelchairs rolling down hallways on their own, and the rattling of door handles in locked rooms. Patients in hospital gowns have been photographed in windows of floors that were sealed off years before the building closed.', 2),

('george-eastman-museum', 'George Eastman Museum', 'Rochester', 'NY', 43.1550, -77.5816, 'museum', 1905, 'The Colonial Revival mansion at 900 East Avenue was built in 1905 for George Eastman, founder of Eastman Kodak. On March 14, 1932, the 77-year-old Eastman shot himself in his upstairs bedroom, leaving a note reading ''My work is done. Why wait?'' The museum, which opened in 1949 as the world''s oldest photography museum, is now haunted by Eastman''s restless spirit. Staff and visitors report seeing a tall, elderly male apparition in the gardens and hallways, feeling an invisible presence accompany them through rooms, and encountering cold spots near the second-floor bedroom where he died. The elevator occasionally operates on its own, stopping at floors no one selected.', 2),

('bird-and-bottle-inn', 'The Bird & Bottle Inn', 'Garrison', 'NY', 41.3794, -73.9326, 'restaurant', 1761, 'The Bird & Bottle Inn in Garrison has stood since 1761, first as Warren''s Tavern serving travelers on the Albany Post Road during the Revolutionary War. The property''s most persistent ghost is Emily Warren, a woman who lived at the inn in the 18th century and died under mysterious circumstances. She appears after closing time, wandering the upstairs hallways in period dress and rearranging objects in the tavern below. Guests staying overnight have woken to find their belongings moved to different locations, doors locked from the inside of empty rooms, and the smell of lavender perfume lingering in the halls. Continental Army soldiers once used the building as a meeting place, and their heavy bootfalls are occasionally heard on the stairs.', 2);
