-- Louisiana Images Update - Wikipedia/Wikimedia Commons
-- Generated by researcher agent on 2026-01-16
-- Replaced existing images with authentic Wikipedia images

-- Total: 37 Louisiana places updated with Wikimedia Commons images

-- Plantations (8)
-- oak-alley-plantation - Oak Alley Plantation, Louisiana (Scott Oldham).jpg
-- myrtles-plantation - Myrtles Plantation.jpg
-- nottoway-plantation - Nottoway Plantation.JPG
-- destrehan-plantation - Destrehan Manor House 20070706.jpg
-- san-francisco-plantation - San Francisco Plantaion House from River Road Levee, February 2021.jpg
-- houmas-house - Houmas House Plantation 02.jpg
-- madewood-plantation - Madewood house.jpg
-- woodland-plantation - Woodland Plantation, La Place Louisiana 01.jpg
-- magnolia-plantation-natchitoches - Log house in the Cane River Creole National Historical Park.jpg

-- French Quarter Hotels (7)
-- hotel-monteleone - Exterior of Hotel Monteleone.jpg
-- bourbon-orleans-hotel - Bourbon Orleans Hotel decorated for Mardi Gras - New Orleans French Quarter 01.jpg
-- omni-royal-orleans - Omni royal hotel.jpg
-- le-pavillon-hotel - Le Pavillon New Orleans.JPG
-- hotel-provincial - New Orleans - French Quarter "Hotel Provincial Courtyard" 2019.jpg
-- place-darmes-hotel - Place d'Armes Hotel - New Orleans French Quarter May 2011.jpg
-- andrew-jackson-hotel - Andrew Jackson Hotel, New Orleans.jpg

-- French Quarter Restaurants/Bars (4)
-- antoines-restaurant - FQ8Oct07AntoinesBalcony.jpg
-- arnauds-restaurant - ArnaudsBienvilleNOLA2009.JPG
-- old-absinthe-house - Absinthe House Corner 2.JPG
-- lafittes-blacksmith-shop - LafittesCarriage1May2004.jpg

-- French Quarter Mansions/Historic Houses (6)
-- lalaurie-mansion - The LaLaurie Mansion.jpg
-- beauregard-keyes-house - FQ29Jan07BeauregardHouse3.jpg
-- gallier-house - GallierHouseBelowA.jpg
-- hermann-grima-house - Hermann-Grima House New Orleans.jpg
-- sultans-palace - Frances Benjamin Johnston, House of the Turk, Dauphine Street, New Orleans, 1937-8.jpg
-- muriels-jackson-square - Muriel's New Orleans, August 2022.jpg

-- French Quarter Other (4)
-- pharmacy-museum - New Orleans Pharmacy Museum.jpg
-- old-ursuline-convent - Ursuline Convent, New Orleans French Quarter, April 2023.jpg
-- st-louis-cemetery-no-1 - St. Louis Cemetery No 1 New Orleans, 27 August 2022 - 01.jpg
-- st-louis-cemetery-no-2 - New Orleans - St. Louis Cemetery No. 2, July 1985.jpg
-- st-louis-cemetery-no-3 - Grieving mother statue, St Louis Cemetery 3, New Orleans, Louisiana, USA.jpg
-- marie-laveau-house - Site of Marie Laveau's Home.jpg

-- Baton Rouge (3)
-- old-state-capitol - Old Louisiana state capitol, west side.jpg
-- pentagon-barracks - Pentagon Barracks (Baton Rouge), 2013.jpg
-- lsu-indian-mounds - LSU Campus Indian Mounds.jpg
-- hilton-baton-rouge-capitol-center - Heidelberg-Hilton Capitol Park, Baton Rouge.jpg

-- Shreveport (2)
-- shreveport-municipal-auditorium - Shreveport September 2015 102 (Shreveport Municipal Auditorium).jpg
-- logan-mansion - Shreveport September 2015 099 (Logan Mansion).jpg

-- Natchitoches (1)
-- front-street-natchitoches - Natchitoches, Louisiana 1993 - 2nd Street.jpg

-- Saenger Theatre (1)
-- saenger-theatre-new-orleans - CanalElkSanger.jpg
