-- Update Texas images with authentic Wikipedia/Wikimedia Commons photos
-- Generated by researcher agent on 2026-01-16

-- San Antonio
UPDATE places SET image_url = 'places/crockett-hotel.jpg' WHERE slug = 'crockett-hotel';
UPDATE places SET image_url = 'places/emily-morgan-hotel.jpg' WHERE slug = 'emily-morgan-hotel';
UPDATE places SET image_url = 'places/st-anthony-hotel.jpg' WHERE slug = 'st-anthony-hotel';
UPDATE places SET image_url = 'places/mission-san-jose.jpg' WHERE slug = 'mission-san-jose';
UPDATE places SET image_url = 'places/mission-espada.jpg' WHERE slug = 'mission-espada';
UPDATE places SET image_url = 'places/san-fernando-cathedral.jpg' WHERE slug = 'san-fernando-cathedral';

-- Galveston
UPDATE places SET image_url = 'places/1894-grand-opera-house.jpg' WHERE slug = '1894-grand-opera-house';

-- Houston
UPDATE places SET image_url = 'places/julia-ideson-building.jpg' WHERE slug = 'julia-ideson-building';
UPDATE places SET image_url = 'places/spaghetti-warehouse-houston.jpg' WHERE slug = 'spaghetti-warehouse-houston';

-- Austin
UPDATE places SET image_url = 'places/austin-state-hospital.jpg' WHERE slug = 'austin-state-hospital';
UPDATE places SET image_url = 'places/oakwood-cemetery.jpg' WHERE slug = 'oakwood-cemetery';

-- Waco
UPDATE places SET image_url = 'places/waco-hippodrome-theatre.jpg' WHERE slug = 'waco-hippodrome-theatre';
UPDATE places SET image_url = 'places/dr-pepper-museum.jpg' WHERE slug = 'dr-pepper-museum';
UPDATE places SET image_url = 'places/alico-building-waco.jpg' WHERE slug = 'alico-building-waco';
UPDATE places SET image_url = 'places/cameron-park-waco.jpg' WHERE slug = 'cameron-park-waco';

-- El Paso
UPDATE places SET image_url = 'places/plaza-theatre-el-paso.jpg' WHERE slug = 'plaza-theatre-el-paso';
UPDATE places SET image_url = 'places/camino-real-hotel.jpg' WHERE slug = 'camino-real-hotel';
UPDATE places SET image_url = 'places/concordia-cemetery.jpg' WHERE slug = 'concordia-cemetery';

-- Fort Worth
UPDATE places SET image_url = 'places/thistle-hill.jpg' WHERE slug = 'thistle-hill';

-- Jefferson
UPDATE places SET image_url = 'places/excelsior-house.jpg' WHERE slug = 'excelsior-house';
UPDATE places SET image_url = 'places/the-grove.jpg' WHERE slug = 'the-grove';

-- West Texas
UPDATE places SET image_url = 'places/marfa-lights.jpg' WHERE slug = 'marfa-lights';
UPDATE places SET image_url = 'places/terlingua-ghost-town.jpg' WHERE slug = 'terlingua-ghost-town';
UPDATE places SET image_url = 'places/gage-hotel.jpg' WHERE slug = 'gage-hotel';
UPDATE places SET image_url = 'places/fort-phantom-hill.jpg' WHERE slug = 'fort-phantom-hill';
UPDATE places SET image_url = 'places/baker-hotel.jpg' WHERE slug = 'baker-hotel';

-- Other
UPDATE places SET image_url = 'places/yorktown-memorial-hospital.jpg' WHERE slug = 'yorktown-memorial-hospital';
