-- New Jersey haunted places image updates
-- Generated by researcher agent on 2026-01-22
-- Sources: Wikipedia/Wikimedia Commons

-- Lighthouses
UPDATE places SET image_url = 'places/absecon-lighthouse.jpg' WHERE slug = 'absecon-lighthouse';
UPDATE places SET image_url = 'places/barnegat-lighthouse.jpg' WHERE slug = 'barnegat-lighthouse';
UPDATE places SET image_url = 'places/cape-may-lighthouse.jpg' WHERE slug = 'cape-may-lighthouse';

-- Princeton Area
UPDATE places SET image_url = 'places/nassau-hall-princeton.jpg' WHERE slug = 'nassau-hall-princeton';
UPDATE places SET image_url = 'places/nassau-inn-princeton.jpg' WHERE slug = 'nassau-inn-princeton';
UPDATE places SET image_url = 'places/rockefeller-college-princeton.jpg' WHERE slug = 'rockefeller-college-princeton';
UPDATE places SET image_url = 'places/princeton-cemetery.jpg' WHERE slug = 'princeton-cemetery';
UPDATE places SET image_url = 'places/thomas-clarke-house.jpg' WHERE slug = 'thomas-clarke-house';

-- Mansions
UPDATE places SET image_url = 'places/ringwood-manor.jpg' WHERE slug = 'ringwood-manor';
UPDATE places SET image_url = 'places/ford-mansion.jpg' WHERE slug = 'ford-mansion';
UPDATE places SET image_url = 'places/emlen-physick-estate.jpg' WHERE slug = 'emlen-physick-estate';
UPDATE places SET image_url = 'places/the-hermitage.jpg' WHERE slug = 'the-hermitage';
UPDATE places SET image_url = 'places/proprietary-house.jpg' WHERE slug = 'proprietary-house';
UPDATE places SET image_url = 'places/smithville-mansion.jpg' WHERE slug = 'smithville-mansion';
UPDATE places SET image_url = 'places/southern-mansion-cape-may.jpg' WHERE slug = 'southern-mansion-cape-may';
UPDATE places SET image_url = 'places/jonathan-pitney-house.jpg' WHERE slug = 'jonathan-pitney-house';
UPDATE places SET image_url = 'places/spy-house.jpg' WHERE slug = 'spy-house';

-- Prisons/Hospitals
UPDATE places SET image_url = 'places/burlington-county-prison.jpg' WHERE slug = 'burlington-county-prison';
UPDATE places SET image_url = 'places/greystone-park-psychiatric.jpg' WHERE slug = 'greystone-park-psychiatric';
UPDATE places SET image_url = 'places/trenton-psychiatric-hospital.jpg' WHERE slug = 'trenton-psychiatric-hospital';
UPDATE places SET image_url = 'places/essex-county-hospital-overbrook.jpg' WHERE slug = 'essex-county-hospital-overbrook';

-- Parks/Historic Sites
UPDATE places SET image_url = 'places/jockey-hollow.jpg' WHERE slug = 'jockey-hollow';
UPDATE places SET image_url = 'places/branch-brook-park.jpg' WHERE slug = 'branch-brook-park';
UPDATE places SET image_url = 'places/allaire-village.jpg' WHERE slug = 'allaire-village';
UPDATE places SET image_url = 'places/batsto-village.jpg' WHERE slug = 'batsto-village';
UPDATE places SET image_url = 'places/clinton-furnace.jpg' WHERE slug = 'clinton-furnace';
UPDATE places SET image_url = 'places/devils-tree.jpg' WHERE slug = 'devils-tree';

-- Roads/Other
UPDATE places SET image_url = 'places/clinton-road.jpg' WHERE slug = 'clinton-road';

-- Hotels - Cape May
UPDATE places SET image_url = 'places/congress-hall-cape-may.jpg' WHERE slug = 'congress-hall-cape-may';
UPDATE places SET image_url = 'places/chalfonte-hotel.jpg' WHERE slug = 'chalfonte-hotel';
UPDATE places SET image_url = 'places/hotel-macomber.jpg' WHERE slug = 'hotel-macomber';
UPDATE places SET image_url = 'places/flanders-hotel.jpg' WHERE slug = 'flanders-hotel';
UPDATE places SET image_url = 'places/resorts-casino-hotel.jpg' WHERE slug = 'resorts-casino-hotel';

-- Universities
UPDATE places SET image_url = 'places/centenary-university.jpg' WHERE slug = 'centenary-university';
UPDATE places SET image_url = 'places/kendall-hall-trenton-state.jpg' WHERE slug = 'kendall-hall-trenton-state';
