-- Update Florida haunted places with Wikipedia/Wikimedia Commons images
-- Generated by researcher agent on 2026-01-16
-- 27 places with authentic Wikipedia images

-- St. Augustine
UPDATE places SET image_url = 'places/castillo-de-san-marcos.jpg' WHERE slug = 'castillo-de-san-marcos';
UPDATE places SET image_url = 'places/st-augustine-lighthouse.jpg' WHERE slug = 'st-augustine-lighthouse';
UPDATE places SET image_url = 'places/huguenot-cemetery.jpg' WHERE slug = 'huguenot-cemetery';
UPDATE places SET image_url = 'places/old-jail-st-augustine.jpg' WHERE slug = 'old-jail-st-augustine';
UPDATE places SET image_url = 'places/spanish-military-hospital.jpg' WHERE slug = 'spanish-military-hospital';
UPDATE places SET image_url = 'places/casa-monica-hotel.jpg' WHERE slug = 'casa-monica-hotel';
UPDATE places SET image_url = 'places/flagler-college.jpg' WHERE slug = 'flagler-college';
UPDATE places SET image_url = 'places/lightner-museum.jpg' WHERE slug = 'lightner-museum';
UPDATE places SET image_url = 'places/tolomato-cemetery.jpg' WHERE slug = 'tolomato-cemetery';

-- Key West
UPDATE places SET image_url = 'places/captain-tonys-saloon.jpg' WHERE slug = 'captain-tonys-saloon';
UPDATE places SET image_url = 'places/audubon-house-key-west.jpg' WHERE slug = 'audubon-house-key-west';

-- Tampa/St. Pete area
UPDATE places SET image_url = 'places/don-cesar-hotel.jpg' WHERE slug = 'don-cesar-hotel';
UPDATE places SET image_url = 'places/cuban-club.jpg' WHERE slug = 'cuban-club';
UPDATE places SET image_url = 'places/tampa-theatre.jpg' WHERE slug = 'tampa-theatre';
UPDATE places SET image_url = 'places/plant-hall.jpg' WHERE slug = 'plant-hall';
UPDATE places SET image_url = 'places/henry-plant-museum.jpg' WHERE slug = 'henry-plant-museum';
UPDATE places SET image_url = 'places/may-stringer-house.jpg' WHERE slug = 'may-stringer-house';
UPDATE places SET image_url = 'places/ybor-city-museum.jpg' WHERE slug = 'ybor-city-museum';

-- Miami/South Florida
UPDATE places SET image_url = 'places/biltmore-hotel.jpg' WHERE slug = 'biltmore-hotel';
UPDATE places SET image_url = 'places/deering-estate.jpg' WHERE slug = 'deering-estate';
UPDATE places SET image_url = 'places/coral-castle.jpg' WHERE slug = 'coral-castle';
UPDATE places SET image_url = 'places/stranahan-house.jpg' WHERE slug = 'stranahan-house';
UPDATE places SET image_url = 'places/vizcaya-museum.jpg' WHERE slug = 'vizcaya-museum';

-- Orlando/Cassadaga area
UPDATE places SET image_url = 'places/devils-millhopper.jpg' WHERE slug = 'devils-millhopper';

-- Pensacola/North Florida
UPDATE places SET image_url = 'places/pensacola-lighthouse.jpg' WHERE slug = 'pensacola-lighthouse';
UPDATE places SET image_url = 'places/fort-pickens.jpg' WHERE slug = 'fort-pickens';
UPDATE places SET image_url = 'places/kingsley-plantation.jpg' WHERE slug = 'kingsley-plantation';
UPDATE places SET image_url = 'places/koreshan-state-park.jpg' WHERE slug = 'koreshan-state-park';
