-- Update images for MA, VA, IL, NY, OH haunted places
-- Generated by researcher agent on 2026-01-16
-- Using Wikipedia/Wikimedia Commons images

-- Massachusetts (MA)
UPDATE places SET image_url = 'places/lizzie-borden-house.jpg' WHERE slug = 'lizzie-borden-house';
UPDATE places SET image_url = 'places/omni-parker-house.jpg' WHERE slug = 'omni-parker-house';
UPDATE places SET image_url = 'places/hawthorne-hotel.jpg' WHERE slug = 'hawthorne-hotel';
UPDATE places SET image_url = 'places/house-of-seven-gables.jpg' WHERE slug = 'house-of-seven-gables';
UPDATE places SET image_url = 'places/peabody-essex-museum.jpg' WHERE slug = 'peabody-essex-museum';
UPDATE places SET image_url = 'places/houghton-mansion.jpg' WHERE slug = 'houghton-mansion';
UPDATE places SET image_url = 'places/longfellow-house.jpg' WHERE slug = 'longfellow-house';
UPDATE places SET image_url = 'places/danvers-state-hospital.jpg' WHERE slug = 'danvers-state-hospital';
UPDATE places SET image_url = 'places/fort-warren.jpg' WHERE slug = 'fort-warren';
UPDATE places SET image_url = 'places/hoosac-tunnel.jpg' WHERE slug = 'hoosac-tunnel';
UPDATE places SET image_url = 'places/concords-colonial-inn.jpg' WHERE slug = 'concords-colonial-inn';
UPDATE places SET image_url = 'places/fenway-park.jpg' WHERE slug = 'fenway-park';
UPDATE places SET image_url = 'places/old-south-meeting-house.jpg' WHERE slug = 'old-south-meeting-house';
UPDATE places SET image_url = 'places/paul-revere-house.jpg' WHERE slug = 'paul-revere-house';
UPDATE places SET image_url = 'places/uss-constitution.jpg' WHERE slug = 'uss-constitution';

-- Virginia (VA)
UPDATE places SET image_url = 'places/monticello.jpg' WHERE slug = 'monticello';
UPDATE places SET image_url = 'places/fort-monroe.jpg' WHERE slug = 'fort-monroe';
UPDATE places SET image_url = 'places/colonial-williamsburg-governors-palace.jpg' WHERE slug = 'colonial-williamsburg-governors-palace';
UPDATE places SET image_url = 'places/peyton-randolph-house.jpg' WHERE slug = 'peyton-randolph-house';
UPDATE places SET image_url = 'places/hollywood-cemetery.jpg' WHERE slug = 'hollywood-cemetery';
UPDATE places SET image_url = 'places/gadsbys-tavern.jpg' WHERE slug = 'gadsbys-tavern';
UPDATE places SET image_url = 'places/virginia-state-capitol.jpg' WHERE slug = 'virginia-state-capitol';
UPDATE places SET image_url = 'places/cavalier-hotel.jpg' WHERE slug = 'cavalier-hotel';
UPDATE places SET image_url = 'places/natural-bridge.jpg' WHERE slug = 'natural-bridge';
UPDATE places SET image_url = 'places/kenmore-plantation.jpg' WHERE slug = 'kenmore-plantation';
UPDATE places SET image_url = 'places/bruton-parish-church.jpg' WHERE slug = 'bruton-parish-church';

-- Illinois (IL)
UPDATE places SET image_url = 'places/biograph-theater.jpg' WHERE slug = 'biograph-theater';
UPDATE places SET image_url = 'places/graceland-cemetery.jpg' WHERE slug = 'graceland-cemetery';
UPDATE places SET image_url = 'places/lincoln-home.jpg' WHERE slug = 'lincoln-home';
UPDATE places SET image_url = 'places/the-drake-hotel.jpg' WHERE slug = 'the-drake-hotel';
UPDATE places SET image_url = 'places/resurrection-cemetery.jpg' WHERE slug = 'resurrection-cemetery';
UPDATE places SET image_url = 'places/rialto-square-theatre.jpg' WHERE slug = 'rialto-square-theatre';
UPDATE places SET image_url = 'places/holy-name-cathedral.jpg' WHERE slug = 'holy-name-cathedral';
UPDATE places SET image_url = 'places/dana-thomas-house.jpg' WHERE slug = 'dana-thomas-house';
UPDATE places SET image_url = 'places/wrigley-field.jpg' WHERE slug = 'wrigley-field';

-- New York (NY)
UPDATE places SET image_url = 'places/the-dakota.jpg' WHERE slug = 'the-dakota';
UPDATE places SET image_url = 'places/fort-ticonderoga.jpg' WHERE slug = 'fort-ticonderoga';
UPDATE places SET image_url = 'places/hotel-chelsea.jpg' WHERE slug = 'hotel-chelsea';
UPDATE places SET image_url = 'places/brooklyn-bridge.jpg' WHERE slug = 'brooklyn-bridge';
UPDATE places SET image_url = 'places/ellis-island.jpg' WHERE slug = 'ellis-island';
UPDATE places SET image_url = 'places/sleepy-hollow-cemetery.jpg' WHERE slug = 'sleepy-hollow-cemetery';
UPDATE places SET image_url = 'places/new-york-state-capitol.jpg' WHERE slug = 'new-york-state-capitol';
UPDATE places SET image_url = 'places/buffalo-central-terminal.jpg' WHERE slug = 'buffalo-central-terminal';
UPDATE places SET image_url = 'places/merchants-house-museum.jpg' WHERE slug = 'merchants-house-museum';
UPDATE places SET image_url = 'places/kings-park-psychiatric-center.jpg' WHERE slug = 'kings-park-psychiatric-center';
UPDATE places SET image_url = 'places/belasco-theatre.jpg' WHERE slug = 'belasco-theatre';
UPDATE places SET image_url = 'places/tarrytown-music-hall.jpg' WHERE slug = 'tarrytown-music-hall';

-- Ohio (OH)
UPDATE places SET image_url = 'places/ohio-state-reformatory.jpg' WHERE slug = 'ohio-state-reformatory';
UPDATE places SET image_url = 'places/franklin-castle.jpg' WHERE slug = 'franklin-castle';
UPDATE places SET image_url = 'places/cincinnati-music-hall.jpg' WHERE slug = 'cincinnati-music-hall';
UPDATE places SET image_url = 'places/lake-view-cemetery.jpg' WHERE slug = 'lake-view-cemetery';
UPDATE places SET image_url = 'places/athens-lunatic-asylum.jpg' WHERE slug = 'athens-lunatic-asylum';
UPDATE places SET image_url = 'places/squires-castle.jpg' WHERE slug = 'squires-castle';
UPDATE places SET image_url = 'places/thurber-house.jpg' WHERE slug = 'thurber-house';
UPDATE places SET image_url = 'places/buxton-inn.jpg' WHERE slug = 'buxton-inn';
