-- Update North Carolina places with Wikipedia/Wikimedia Commons images
-- Generated by researcher agent on 2026-01-22

-- Asheville Area
UPDATE places SET image_url = 'places/biltmore-estate.jpg' WHERE slug = 'biltmore-estate';
UPDATE places SET image_url = 'places/thomas-wolfe-memorial.jpg' WHERE slug = 'thomas-wolfe-memorial';
UPDATE places SET image_url = 'places/brown-mountain-lights.jpg' WHERE slug = 'brown-mountain-lights';
UPDATE places SET image_url = 'places/balsam-mountain-inn.jpg' WHERE slug = 'balsam-mountain-inn';

-- Wilmington Area
UPDATE places SET image_url = 'places/battleship-north-carolina.jpg' WHERE slug = 'battleship-north-carolina';
UPDATE places SET image_url = 'places/bellamy-mansion.jpg' WHERE slug = 'bellamy-mansion';
UPDATE places SET image_url = 'places/thalian-hall.jpg' WHERE slug = 'thalian-hall';
UPDATE places SET image_url = 'places/burgwin-wright-house.jpg' WHERE slug = 'burgwin-wright-house';

-- Outer Banks / Coastal
UPDATE places SET image_url = 'places/cape-hatteras-lighthouse.jpg' WHERE slug = 'cape-hatteras-lighthouse';
UPDATE places SET image_url = 'places/currituck-beach-lighthouse.jpg' WHERE slug = 'currituck-beach-lighthouse';
UPDATE places SET image_url = 'places/ocracoke-lighthouse.jpg' WHERE slug = 'ocracoke-lighthouse';
UPDATE places SET image_url = 'places/bodie-island-lighthouse.jpg' WHERE slug = 'bodie-island-lighthouse';
UPDATE places SET image_url = 'places/roanoke-island.jpg' WHERE slug = 'roanoke-island';
UPDATE places SET image_url = 'places/old-burying-ground-beaufort.jpg' WHERE slug = 'old-burying-ground-beaufort';

-- Raleigh / Triangle Area
UPDATE places SET image_url = 'places/north-carolina-state-capitol.jpg' WHERE slug = 'north-carolina-state-capitol';
UPDATE places SET image_url = 'places/mordecai-house.jpg' WHERE slug = 'mordecai-house';
UPDATE places SET image_url = 'places/carolina-inn.jpg' WHERE slug = 'carolina-inn';

-- Winston-Salem / Piedmont
UPDATE places SET image_url = 'places/old-salem-single-brothers-house.jpg' WHERE slug = 'old-salem-single-brothers-house';
UPDATE places SET image_url = 'places/korners-folly.jpg' WHERE slug = 'korners-folly';
UPDATE places SET image_url = 'places/devils-tramping-ground.jpg' WHERE slug = 'devils-tramping-ground';

-- Charlotte / Southern Piedmont
UPDATE places SET image_url = 'places/green-park-inn.jpg' WHERE slug = 'green-park-inn';
