-- Update Pennsylvania place images with Wikipedia/Wikimedia Commons sources
-- Generated by researcher agent on 2026-01-16

-- Philadelphia Area
UPDATE places SET image_url = 'places/eastern-state-penitentiary.jpg' WHERE slug = 'eastern-state-penitentiary';
UPDATE places SET image_url = 'places/fort-mifflin.jpg' WHERE slug = 'fort-mifflin';
UPDATE places SET image_url = 'places/betsy-ross-house.jpg' WHERE slug = 'betsy-ross-house';
UPDATE places SET image_url = 'places/independence-hall.jpg' WHERE slug = 'independence-hall';
UPDATE places SET image_url = 'places/carpenters-hall.jpg' WHERE slug = 'carpenters-hall';
UPDATE places SET image_url = 'places/city-tavern.jpg' WHERE slug = 'city-tavern';
UPDATE places SET image_url = 'places/first-bank-united-states.jpg' WHERE slug = 'first-bank-united-states';
UPDATE places SET image_url = 'places/laurel-hill-cemetery.jpg' WHERE slug = 'laurel-hill-cemetery';

-- Pittsburgh Area
UPDATE places SET image_url = 'places/carnegie-library-oakland.jpg' WHERE slug = 'carnegie-library-oakland';
UPDATE places SET image_url = 'places/national-aviary.jpg' WHERE slug = 'national-aviary';
UPDATE places SET image_url = 'places/allegheny-county-jail.jpg' WHERE slug = 'allegheny-county-jail';

-- Gettysburg Area
UPDATE places SET image_url = 'places/sachs-covered-bridge.jpg' WHERE slug = 'sachs-covered-bridge';
UPDATE places SET image_url = 'places/dobbin-house-tavern.jpg' WHERE slug = 'dobbin-house-tavern';
UPDATE places SET image_url = 'places/cashtown-inn.jpg' WHERE slug = 'cashtown-inn';
UPDATE places SET image_url = 'places/little-round-top.jpg' WHERE slug = 'little-round-top';
UPDATE places SET image_url = 'places/devils-den.jpg' WHERE slug = 'devils-den';

-- Central Pennsylvania
UPDATE places SET image_url = 'places/fort-hunter-mansion.jpg' WHERE slug = 'fort-hunter-mansion';
UPDATE places SET image_url = 'places/fulton-theatre.jpg' WHERE slug = 'fulton-theatre';

-- Gettysburg Additional
UPDATE places SET image_url = 'places/soldiers-national-museum.jpg' WHERE slug = 'soldiers-national-museum';

-- Other Pennsylvania Locations
UPDATE places SET image_url = 'places/centralia.jpg' WHERE slug = 'centralia';
UPDATE places SET image_url = 'places/jean-bonnet-tavern.jpg' WHERE slug = 'jean-bonnet-tavern';
UPDATE places SET image_url = 'places/golden-plough-tavern.jpg' WHERE slug = 'golden-plough-tavern';
UPDATE places SET image_url = 'places/houdini-museum.jpg' WHERE slug = 'houdini-museum';
UPDATE places SET image_url = 'places/pennhurst-asylum.jpg' WHERE slug = 'pennhurst-asylum';
UPDATE places SET image_url = 'places/church-brew-works.jpg' WHERE slug = 'church-brew-works';
