-- Update Kentucky haunted places images
-- Generated by researcher agent on 2026-01-22
-- Images sourced from Wikipedia/Wikimedia Commons

-- Waverly Hills Sanatorium - from Wikipedia
UPDATE places SET image_url = 'places/waverly-hills-sanatorium.jpg' WHERE slug = 'waverly-hills-sanatorium';

-- Bobby Mackey's Music World - from Wikipedia
UPDATE places SET image_url = 'places/bobby-mackeys-music-world.jpg' WHERE slug = 'bobby-mackeys-music-world';

-- Liberty Hall - from Wikipedia
UPDATE places SET image_url = 'places/liberty-hall.jpg' WHERE slug = 'liberty-hall';

-- Mammoth Cave - from Wikipedia
UPDATE places SET image_url = 'places/mammoth-cave.jpg' WHERE slug = 'mammoth-cave';

-- Buffalo Trace Distillery - from Wikipedia
UPDATE places SET image_url = 'places/buffalo-trace-distillery.jpg' WHERE slug = 'buffalo-trace-distillery';

-- Seelbach Hilton Hotel - from Wikipedia
UPDATE places SET image_url = 'places/seelbach-hilton-hotel.jpg' WHERE slug = 'seelbach-hilton-hotel';

-- Mary Todd Lincoln House - from Wikipedia
UPDATE places SET image_url = 'places/mary-todd-lincoln-house.jpg' WHERE slug = 'mary-todd-lincoln-house';

-- Ashland Henry Clay Estate - from Wikipedia
UPDATE places SET image_url = 'places/ashland-henry-clay-estate.jpg' WHERE slug = 'ashland-henry-clay-estate';

-- Perryville Battlefield - from Wikipedia (historic illustration)
UPDATE places SET image_url = 'places/perryville-battlefield.jpg' WHERE slug = 'perryville-battlefield';

-- Cave Hill Cemetery - from Wikipedia
UPDATE places SET image_url = 'places/cave-hill-cemetery.jpg' WHERE slug = 'cave-hill-cemetery';

-- Old Talbott Tavern - from Wikipedia
UPDATE places SET image_url = 'places/old-talbott-tavern.jpg' WHERE slug = 'old-talbott-tavern';

-- My Old Kentucky Home - from Wikipedia
UPDATE places SET image_url = 'places/my-old-kentucky-home.jpg' WHERE slug = 'my-old-kentucky-home';

-- White Hall State Historic Site - from Wikipedia
UPDATE places SET image_url = 'places/white-hall.jpg' WHERE slug = 'white-hall';

-- Belle of Louisville - from Wikipedia
UPDATE places SET image_url = 'places/belle-of-louisville.jpg' WHERE slug = 'belle-of-louisville';

-- Lexington Opera House - from Wikipedia
UPDATE places SET image_url = 'places/lexington-opera-house.jpg' WHERE slug = 'lexington-opera-house';

-- Lexington Cemetery - from Wikipedia
UPDATE places SET image_url = 'places/lexington-cemetery.jpg' WHERE slug = 'lexington-cemetery';

-- Frankfort Cemetery - from Wikipedia
UPDATE places SET image_url = 'places/frankfort-cemetery.jpg' WHERE slug = 'frankfort-cemetery';

-- Speed Art Museum - from Wikipedia
UPDATE places SET image_url = 'places/speed-art-museum.jpg' WHERE slug = 'speed-art-museum';

-- Lost River Cave - from Wikipedia
UPDATE places SET image_url = 'places/lost-river-cave.jpg' WHERE slug = 'lost-river-cave';

-- Shaker Village of Pleasant Hill - from Wikimedia Commons
UPDATE places SET image_url = 'places/shaker-village-pleasant-hill.jpg' WHERE slug = 'shaker-village-pleasant-hill';

-- Octagon Hall Museum - from Wikipedia
UPDATE places SET image_url = 'places/octagon-hall.jpg' WHERE slug = 'octagon-hall';

-- Camp Nelson National Monument - from Wikipedia
UPDATE places SET image_url = 'places/camp-nelson.jpg' WHERE slug = 'camp-nelson';

-- Old State Capitol Building - from Wikipedia
UPDATE places SET image_url = 'places/old-state-capitol.jpg' WHERE slug = 'old-state-capitol';

-- Colville Covered Bridge - from Wikipedia
UPDATE places SET image_url = 'places/colville-covered-bridge.jpg' WHERE slug = 'colville-covered-bridge';

-- Old Fort Harrod State Park - from Wikipedia
UPDATE places SET image_url = 'places/old-fort-harrod.jpg' WHERE slug = 'old-fort-harrod';

-- Conrad-Caldwell House - from Wikimedia Commons
UPDATE places SET image_url = 'places/conrad-caldwell-house.jpg' WHERE slug = 'conrad-caldwell-house';

-- Louisville Palace Theatre - from Wikimedia Commons
UPDATE places SET image_url = 'places/louisville-palace-theatre.jpg' WHERE slug = 'louisville-palace-theatre';

-- Hunt-Morgan House - from Wikimedia Commons
UPDATE places SET image_url = 'places/hunt-morgan-house.jpg' WHERE slug = 'hunt-morgan-house';

-- Transylvania University Old Morrison - from Wikimedia Commons
UPDATE places SET image_url = 'places/transylvania-university.jpg' WHERE slug = 'transylvania-university';

-- Bodley-Bullock House - from Wikimedia Commons
UPDATE places SET image_url = 'places/bodley-bullock-house.jpg' WHERE slug = 'bodley-bullock-house';

-- The Carneal House - from Wikimedia Commons
UPDATE places SET image_url = 'places/carneal-house.jpg' WHERE slug = 'carneal-house';

-- Booth Memorial Hospital - from Wikimedia Commons
UPDATE places SET image_url = 'places/booth-memorial-hospital.jpg' WHERE slug = 'booth-memorial-hospital';
